import {
  decimalPercentLesson,
  lesson,
  levelReviewLesson,
  mcScene,
  nlScene,
  percentFractionLesson,
  percentOfLesson,
} from "./_helpers";

/** Level 3 — Tenths, hundredths and decimals */
export const MATH_PERCENTS_LEVEL_3_SEEDS = [
  lesson(
    3,
    "percentages-as-tenths",
    "Percentages as Tenths",
    "beginner",
    [
      mcScene(
        "l3-tenth-1",
        "Link",
        "10% equals…",
        ["1 tenth", "10 tenths", "1 hundredth", "10 wholes"],
        "1 tenth",
        "l3_tenth_link",
        { correct: "10% = 0.1 = one tenth.", incorrect: "10% is 1/10.", hint: "1 tenth." },
      ),
      mcScene(
        "l3-tenth-2",
        "30%",
        "30% equals how many tenths?",
        ["3", "30", "0.3", "300"],
        "3",
        "l3_tenth_30",
        { correct: "30% = 3 tenths.", incorrect: "Each 10% is one tenth.", hint: "3." },
      ),
      nlScene(
        "l3-tenth-3",
        "Place 0.3",
        "Place 0.3 on the number line from 0 to 1.",
        0.3,
        "l3_tenth_nl",
        { correct: "0.3 = 30%.", incorrect: "Three tenths.", hint: "0.3." },
      ),
    ],
    mcScene(
      "l3-tenth-final",
      "Mastery check",
      "50% = ? tenths",
      ["5", "50", "0.5", "1"],
      "5",
      "l3_tenth_mastery",
      { correct: "5 tenths.", incorrect: "Half = 5 tenths.", hint: "5." },
    ),
  ),
  lesson(
    3,
    "percentages-as-hundredths",
    "Percentages as Hundredths",
    "beginner",
    [
      mcScene(
        "l3-hund-1",
        "Definition",
        "1% equals…",
        ["1 hundredth", "1 tenth", "1 whole", "100 wholes"],
        "1 hundredth",
        "l3_hundredth_def",
        { correct: "1% = 0.01.", incorrect: "Percent → hundredths.", hint: "1 hundredth." },
      ),
      mcScene(
        "l3-hund-2",
        "Count",
        "45% equals how many hundredths?",
        ["45", "4.5", "0.45", "450"],
        "45",
        "l3_hundredth_45",
        { correct: "45 hundredths.", incorrect: "Percent number = hundredths count.", hint: "45." },
      ),
      nlScene(
        "l3-hund-3",
        "Place 0.07",
        "Place 0.07 (7%) on the number line.",
        0.07,
        "l3_hundredth_nl",
        { correct: "7%.", incorrect: "Seven hundredths.", hint: "0.07." },
      ),
    ],
    mcScene(
      "l3-hund-final",
      "Mastery check",
      "8% = ? hundredths",
      ["8", "80", "0.8", "800"],
      "8",
      "l3_hund_mastery",
      { correct: "8 hundredths.", incorrect: "8.", hint: "8." },
    ),
  ),
  percentOfLesson(3, "finding-the-percentage", "Finding the Percentage", 15, 200),
  decimalPercentLesson(3, "percentages-as-decimals", "Percentages as Decimals", 35),
  percentOfLesson(3, "calculating-the-percentage", "Calculating the Percentage", 12, 250),
];
