import {
  compoundChangeLesson,
  lesson,
  levelReviewLesson,
  mcScene,
  sortScene,
} from "./_helpers";

/** Level 5 — Compound changes */
export const MATH_PERCENTS_LEVEL_5_SEEDS = [
  compoundChangeLesson(5, "compound-calculations", "Compound Calculations", 100, 10, 10),
  lesson(
    5,
    "splitting-percent-changes",
    "Splitting Percent Changes",
    "intermediate",
    [
      mcScene(
        "l5-split-1",
        "Two-step sale",
        "20% off then 10% off applies to…",
        ["The price after the first discount", "The original only", "The sum of percents", "Zero"],
        "The price after the first discount",
        "l5_split_apply",
        { correct: "Second percent hits the new price.", incorrect: "Sequential application.", hint: "After first discount." },
      ),
      sortScene(
        "l5-split-2",
        "Order",
        "Order: $100 with 20% off then 10% off.",
        ["New = $80", "20% off $100", "10% off $80", "New = $72"],
        ["20% off $100", "New = $80", "10% off $80", "New = $72"],
        "l5_split_order",
        { correct: "$100 → $80 → $72.", incorrect: "Apply each step in order.", hint: "Sequential." },
      ),
      mcScene(
        "l5-split-3",
        "Compare",
        "20% + 10% off at once (30% off) vs sequential — usually…",
        ["Sequential is a smaller final discount", "Always equal", "Sequential costs more", "Impossible"],
        "Sequential is a smaller final discount",
        "l5_split_compare",
        { correct: "10% off $80 < 10% off $100 in effect.", incorrect: "Second discount is smaller base.", hint: "Smaller discount." },
      ),
    ],
    mcScene(
      "l5-split-final",
      "Mastery check",
      "$50 with 10% off then 10% off = ?",
      ["$40.50", "$45", "$40", "$41"],
      "$40.50",
      "l5_split_mastery",
      { correct: "$50 → $45 → $40.50.", incorrect: "Apply twice.", hint: "$40.50." },
    ),
  ),
  compoundChangeLesson(5, "growing-and-shrinking", "Growing and Shrinking", 200, 15, -10),
  lesson(
    5,
    "exponential-growth",
    "Exponential Growth",
    "intermediate",
    [
      mcScene(
        "l5-exp-1",
        "Repeated growth",
        "$100 growing 10% per year for 2 years (compound) ≈ ?",
        ["$121", "$120", "$110", "$100"],
        "$121",
        "l5_exp_2yr",
        { correct: "100 × 1.1 × 1.1 = 121.", incorrect: "Multiply by 1.1 twice.", hint: "$121." },
      ),
      mcScene(
        "l5-exp-2",
        "Pattern",
        "Repeated equal percent growth creates…",
        ["Exponential growth", "Linear growth", "No change", "Always halving"],
        "Exponential growth",
        "l5_exp_pattern",
        { correct: "Each step multiplies by the same factor.", incorrect: "Compound = exponential.", hint: "Exponential." },
      ),
      mcScene(
        "l5-exp-3",
        "Multiplier",
        "10% growth each period uses multiplier…",
        ["1.1", "0.1", "1.01", "10"],
        "1.1",
        "l5_exp_mult",
        { correct: "1 + 0.10 = 1.1.", incorrect: "Add percent as decimal to 1.", hint: "1.1." },
      ),
    ],
    mcScene(
      "l5-exp-final",
      "Mastery check",
      "Population doubles each year — after 3 years starting at 100?",
      ["800", "300", "400", "600"],
      "800",
      "l5_exp_mastery",
      { correct: "100 → 200 → 400 → 800 (100% growth).", incorrect: "Double three times.", hint: "800." },
    ),
  ),
];
