import { graphInequalityLesson, lesson, mcScene, segScene } from "./_helpers";

/** Level 4 — Inequalities on the coordinate plane */
export const MATH_COORD_LEVEL_4_SEEDS = [
  graphInequalityLesson(4, "y-inequalities", "y Inequalities", "y", 2, "gt"),
  graphInequalityLesson(4, "x-inequalities", "x Inequalities", "x", -1, "lt"),
  lesson(
    4,
    "identifying-regions",
    "Identifying Regions",
    "intermediate",
    [
      mcScene(
        "l4-reg-1",
        "Half-plane",
        "y > 3 describes all points…",
        ["Above the line y = 3", "Below y = 3", "Left of x = 3", "On y = 3 only"],
        "Above the line y = 3",
        "l4_region_y",
        { correct: "Greater y → above.", incorrect: "> means higher.", hint: "Above." },
      ),
      mcScene(
        "l4-reg-2",
        "Vertical strip",
        "x < 0 describes all points…",
        ["Left of the y-axis", "Right of the y-axis", "Below the x-axis", "Above the x-axis"],
        "Left of the y-axis",
        "l4_region_x",
        { correct: "Negative x → left half-plane.", incorrect: "x < 0.", hint: "Left." },
      ),
      segScene(
        "l4-reg-3",
        "Combine",
        "y ≤ 1 includes points where…",
        [
          { id: "yes", label: "y is 1 or less" },
          { id: "no", label: "y is greater than 1" },
          { id: "eq", label: "y is exactly 2" },
        ],
        "yes",
        "l4_region_lte",
        { correct: "≤ includes the boundary.", incorrect: "On or below y = 1.", hint: "y ≤ 1." },
      ),
    ],
    mcScene(
      "l4-reg-final",
      "Mastery check",
      "x ≥ 2 describes points…",
      ["Right of x = 2 (including the line)", "Left of x = 2", "Above y = 2", "Below y = 2"],
      "Right of x = 2 (including the line)",
      "l4_reg_mastery",
      { correct: "x ≥ 2 → right half-plane.", incorrect: "Greater or equal x.", hint: "Right side." },
    ),
  ),
  graphInequalityLesson(4, "or-equal-to", "Or Equal To", "y", -2, "gte"),
  lesson(
    4,
    "marking-boundaries",
    "Marking Boundaries",
    "intermediate",
    [
      mcScene(
        "l4-mark-1",
        "Solid vs dashed",
        "y ≥ x uses a ___ boundary at y = x.",
        ["Solid (included)", "Dashed (excluded)", "No boundary", "Dotted only"],
        "Solid (included)",
        "l4_boundary_solid",
        { correct: "≥ includes points on the line.", incorrect: "Equal sign → solid line.", hint: "Solid." },
      ),
      mcScene(
        "l4-mark-2",
        "Strict inequality",
        "y < 4 uses a ___ boundary at y = 4.",
        ["Dashed (excluded)", "Solid (included)", "No line", "Double line"],
        "Dashed (excluded)",
        "l4_boundary_dashed",
        { correct: "< excludes the boundary.", incorrect: "Strict → not included.", hint: "Dashed." },
      ),
      mcScene(
        "l4-mark-3",
        "Test boundary",
        "Is (2, 2) on the boundary of x = 2?",
        ["Yes", "No", "Only for y > 0", "Cannot tell"],
        "Yes",
        "l4_boundary_test",
        { correct: "x = 2 satisfies x = 2.", incorrect: "On the vertical line.", hint: "Yes." },
      ),
    ],
    mcScene(
      "l4-mark-final",
      "Mastery check",
      "Does (3, 3) satisfy y > 3?",
      ["No", "Yes", "On the boundary", "Both yes and no"],
      "No",
      "l4_mark_mastery",
      { correct: "y = 3 is not greater than 3.", incorrect: "Strict > excludes equal.", hint: "No." },
    ),
  ),
  lesson(
    4,
    "accounting-inequalities",
    "Accounting Inequalities",
    "intermediate",
    [
      mcScene(
        "l4-acct-1",
        "Budget cap",
        "Spending (x, y) must satisfy x + y ≤ 100. Point (40, 50)?",
        ["Satisfies (90 ≤ 100)", "Violates", "On boundary only", "Undefined"],
        "Satisfies (90 ≤ 100)",
        "l4_acct_sum",
        { correct: "40 + 50 = 90 ≤ 100.", incorrect: "Add coordinates.", hint: "Under budget." },
      ),
      mcScene(
        "l4-acct-2",
        "Minimum sales",
        "Region x ≥ 10 means at least 10 units sold in x-direction…",
        ["Yes", "No", "Exactly 10 only", "Less than 10"],
        "Yes",
        "l4_acct_min",
        { correct: "x ≥ 10 is a minimum threshold.", incorrect: "≥ means at least.", hint: "Yes." },
      ),
      mcScene(
        "l4-acct-3",
        "Feasible point",
        "Which point satisfies x ≥ 0 and y ≥ 0 (first quadrant including axes)?",
        ["(0, 5)", "(−1, 2)", "(2, −3)", "(−2, −1)"],
        "(0, 5)",
        "l4_acct_quad",
        { correct: "Non-negative x and y.", incorrect: "Quadrant I + axes.", hint: "(0, 5)." },
      ),
    ],
    mcScene(
      "l4-acct-final",
      "Mastery check",
      "Profit requires y > 0. Which point works?",
      ["(2, 3)", "(2, 0)", "(2, −1)", "(−1, 3)"],
      "(2, 3)",
      "l4_acct_mastery",
      { correct: "y = 3 > 0.", incorrect: "Positive y needed.", hint: "(2, 3)." },
    ),
  ),
];
