import {
  graphScene,
  lesson,
  levelReviewLesson,
  matchScene,
  mcScene,
  plotPointLesson,
  QUADRANT1_BOUNDS,
} from "./_helpers";

/** Level 1 — Coordinates: pairs, axes, plotting in quadrant I. */
export const MATH_COORD_LEVEL_1_SEEDS = [
  lesson(
    1,
    "coordinates",
    "Coordinates",
    "beginner",
    [
      mcScene(
        "l1-coord-1",
        "What is a coordinate?",
        "A coordinate plane uses two numbers to describe…",
        ["A location", "A length only", "An angle only", "A fraction"],
        "A location",
        "l1_coord_intro",
        { correct: "An (x, y) address on the plane.", incorrect: "Two axes locate a point.", hint: "Location." },
      ),
      mcScene(
        "l1-coord-2",
        "Two numbers",
        "Every point needs how many coordinates?",
        ["2", "1", "3", "0"],
        "2",
        "l1_coord_count",
        { correct: "x and y — two values.", incorrect: "Horizontal and vertical.", hint: "2." },
      ),
      graphScene(
        "l1-coord-3",
        "First plot",
        "Place (1, 1) on the grid.",
        1,
        1,
        "l1_coord_plot",
        { correct: "(1, 1) — one right, one up.", incorrect: "x=1, y=1.", hint: "(1, 1)." },
        QUADRANT1_BOUNDS,
      ),
    ],
    graphScene(
      "l1-coord-final",
      "Mastery check",
      "Plot (2, 3).",
      2,
      3,
      "l1_coord_mastery",
      { correct: "(2, 3).", incorrect: "Two right, three up.", hint: "(2, 3)." },
      QUADRANT1_BOUNDS,
    ),
  ),
  lesson(
    1,
    "coordinate-pairs",
    "Coordinate Pairs",
    "beginner",
    [
      mcScene(
        "l1-pair-1",
        "Ordered pair",
        "(4, 2) means…",
        ["x = 4, y = 2", "x = 2, y = 4", "x = 4 only", "y = 2 only"],
        "x = 4, y = 2",
        "l1_pair_order",
        { correct: "x first, y second.", incorrect: "Order matters.", hint: "4 across, 2 up." },
      ),
      matchScene(
        "l1-pair-2",
        "Match pairs",
        "Match each description to its coordinate pair.",
        [
          { id: "a", label: "(3, 5)" },
          { id: "b", label: "(5, 3)" },
          { id: "c", label: "(0, 4)" },
        ],
        [
          { id: "s1", label: "3 right, 5 up" },
          { id: "s2", label: "5 right, 3 up" },
          { id: "s3", label: "On the y-axis at 4" },
        ],
        { s1: "a", s2: "b", s3: "c" },
        "l1_pair_match",
        { correct: "Each pair matches its move.", incorrect: "x is horizontal first.", hint: "Order is (x, y)." },
      ),
      graphScene("l1-pair-3", "Plot (3, 5)", "Place (3, 5).", 3, 5, "l1_pair_plot", {
        correct: "(3, 5).",
        incorrect: "3 across, 5 up.",
        hint: "(3, 5).",
      }),
    ],
    graphScene("l1-pair-final", "Mastery check", "Plot (4, 1).", 4, 1, "l1_pair_mastery", {
      correct: "(4, 1).",
      incorrect: "4 right, 1 up.",
      hint: "(4, 1).",
    }),
  ),
  lesson(
    1,
    "axes",
    "Axes",
    "beginner",
    [
      mcScene(
        "l1-axes-1",
        "Horizontal axis",
        "The horizontal axis is usually labeled…",
        ["x", "y", "z", "t"],
        "x",
        "l1_axes_x",
        { correct: "x runs left-right.", incorrect: "Horizontal → x.", hint: "x." },
      ),
      mcScene(
        "l1-axes-2",
        "Vertical axis",
        "The vertical axis is usually labeled…",
        ["y", "x", "z", "r"],
        "y",
        "l1_axes_y",
        { correct: "y runs up-down.", incorrect: "Vertical → y.", hint: "y." },
      ),
      mcScene(
        "l1-axes-3",
        "Origin",
        "Where the axes cross is called the…",
        ["Origin", "Vertex", "Center", "Pair"],
        "Origin",
        "l1_axes_origin",
        { correct: "(0, 0) — the origin.", incorrect: "Axes meet at (0, 0).", hint: "Origin." },
      ),
    ],
    mcScene(
      "l1-axes-final",
      "Mastery check",
      "A point on the x-axis has y = …",
      ["0", "1", "x", "undefined"],
      "0",
      "l1_axes_mastery",
      { correct: "y = 0 on the x-axis.", incorrect: "No vertical offset.", hint: "0." },
    ),
  ),
  plotPointLesson(1, "x-and-y-coordinates", "x and y Coordinates", 2, 4),
  plotPointLesson(1, "plotting-points", "Plotting Points", 5, 2),
  plotPointLesson(1, "identifying-points", "Identifying Points", 3, 3),
  lesson(
    1,
    "applied-coordinates",
    "Applied Coordinates",
    "beginner",
    [
      mcScene(
        "l1-app-1",
        "Map grid",
        "A treasure is 4 blocks east and 2 blocks north from town (0, 0). Coordinates?",
        ["(4, 2)", "(2, 4)", "(4, −2)", "(−4, 2)"],
        "(4, 2)",
        "l1_applied_map",
        { correct: "East → x, North → y.", incorrect: "4 right, 2 up.", hint: "(4, 2)." },
      ),
      graphScene("l1-app-2", "Mark the treasure", "Plot the treasure at (4, 2).", 4, 2, "l1_applied_plot", {
        correct: "(4, 2).",
        incorrect: "Four east, two north.",
        hint: "(4, 2).",
      }),
      mcScene(
        "l1-app-3",
        "Delivery stop",
        "A stop at (1, 5) is how far north of the origin?",
        ["5 units", "1 unit", "6 units", "0 units"],
        "5 units",
        "l1_applied_north",
        { correct: "y = 5 → 5 units north.", incorrect: "Read the y-value.", hint: "5." },
      ),
    ],
    graphScene("l1-app-final", "Mastery check", "Plot the library at (5, 4).", 5, 4, "l1_applied_mastery", {
      correct: "(5, 4).",
      incorrect: "5 east, 4 north.",
      hint: "(5, 4).",
    }),
  ),
  levelReviewLesson(1, "level-check", "Level Check", [
    { prompt: "Horizontal axis?", choices: ["x", "y", "z", "0"], answer: "x" },
    { prompt: "(2, 5) means…", choices: ["x=2, y=5", "x=5, y=2", "x=2 only", "y=5 only"], answer: "x=2, y=5" },
    { prompt: "Origin coordinates?", choices: ["(0, 0)", "(1, 1)", "(0, 1)", "(1, 0)"], answer: "(0, 0)" },
    { prompt: "Plot (3, 2): x is…", choices: ["3", "2", "5", "0"], answer: "3" },
  ]),
];
