import {
  coordDistanceLesson,
  FULL_PLANE_BOUNDS,
  graphScene,
  lesson,
  mcScene,
  plotPointLesson,
} from "./_helpers";

/** Level 5 — Distance on the coordinate plane */
export const MATH_COORD_LEVEL_5_SEEDS = [
  lesson(
    5,
    "distance-from-axes",
    "Distance From Axes",
    "intermediate",
    [
      mcScene(
        "l5-axis-1",
        "From x-axis",
        "Point (4, −3) is how far from the x-axis?",
        ["3 units", "4 units", "5 units", "7 units"],
        "3 units",
        "l5_dist_xaxis",
        { correct: "|y| = 3.", incorrect: "Vertical distance = |y|.", hint: "3." },
      ),
      mcScene(
        "l5-axis-2",
        "From y-axis",
        "Point (−5, 2) is how far from the y-axis?",
        ["5 units", "2 units", "7 units", "3 units"],
        "5 units",
        "l5_dist_yaxis",
        { correct: "|x| = 5.", incorrect: "Horizontal distance = |x|.", hint: "5." },
      ),
      graphScene(
        "l5-axis-3",
        "Plot and measure",
        "Plot (3, −4). Its distance from the x-axis is |y| = 4.",
        3,
        -4,
        "l5_axis_plot",
        { correct: "(3, −4) — 4 below x-axis.", incorrect: "y = −4.", hint: "(3, −4)." },
        FULL_PLANE_BOUNDS,
      ),
    ],
    mcScene(
      "l5-axis-final",
      "Mastery check",
      "(−2, 6) is how far from the y-axis?",
      ["2 units", "6 units", "8 units", "4 units"],
      "2 units",
      "l5_axis_mastery",
      { correct: "|−2| = 2.", incorrect: "Horizontal distance from y-axis.", hint: "2." },
    ),
  ),
  coordDistanceLesson(5, "distance-between-points", "Distance Between Points", 0, 0, 3, 4),
  lesson(
    5,
    "absolute-value",
    "Absolute Value",
    "intermediate",
    [
      mcScene(
        "l5-abs-1",
        "Distance as absolute value",
        "Distance from (2, 0) to the y-axis equals |x| = …",
        ["2", "−2", "0", "4"],
        "2",
        "l5_abs_x",
        { correct: "|2| = 2.", incorrect: "Distance is non-negative.", hint: "2." },
      ),
      mcScene(
        "l5-abs-2",
        "From a line",
        "Distance from (1, −5) to the x-axis is…",
        ["5", "−5", "1", "6"],
        "5",
        "l5_abs_y",
        { correct: "|−5| = 5.", incorrect: "|y| gives vertical distance.", hint: "5." },
      ),
      mcScene(
        "l5-abs-3",
        "Pythagorean link",
        "Distance from origin to (3, 4) is √(3² + 4²) = …",
        ["5", "7", "12", "1"],
        "5",
        "l5_abs_hyp",
        { correct: "3-4-5 triangle.", incorrect: "√(9+16) = 5.", hint: "5." },
      ),
    ],
    mcScene(
      "l5-abs-final",
      "Mastery check",
      "|−6| as distance from y-axis for (−6, 1)?",
      ["6", "−6", "1", "7"],
      "6",
      "l5_abs_mastery",
      { correct: "6 units left of y-axis.", incorrect: "|x| = 6.", hint: "6." },
    ),
  ),
  lesson(
    5,
    "selecting-for-distance",
    "Selecting for Distance",
    "intermediate",
    [
      mcScene(
        "l5-sel-1",
        "Same distance",
        "Which point is also 5 units from the origin?",
        ["(3, 4)", "(5, 0)", "(1, 1)", "(2, 2)"],
        "(3, 4)",
        "l5_sel_same",
        { correct: "3² + 4² = 25 → distance 5.", incorrect: "Use distance formula.", hint: "(3, 4)." },
      ),
      mcScene(
        "l5-sel-2",
        "Closer to axis",
        "Which is closer to the x-axis: (2, 1) or (2, −7)?",
        ["(2, 1)", "(2, −7)", "Equal", "Neither"],
        "(2, 1)",
        "l5_sel_axis",
        { correct: "|1| < |−7|.", incorrect: "Compare |y|.", hint: "(2, 1)." },
      ),
      mcScene(
        "l5-sel-3",
        "Farthest",
        "Which point is farthest from (0, 0)?",
        ["(−4, −4)", "(1, 0)", "(0, 2)", "(2, 1)"],
        "(−4, −4)",
        "l5_sel_far",
        { correct: "√(32) ≈ 5.66 — largest.", incorrect: "Compare distances.", hint: "(−4, −4)." },
      ),
    ],
    mcScene(
      "l5-sel-final",
      "Mastery check",
      "Points equidistant from x = 0 have the same…",
      ["|x|", "y", "x + y", "x − y"],
      "|x|",
      "l5_sel_mastery",
      { correct: "Same horizontal distance from y-axis.", incorrect: "|x| matches.", hint: "|x|." },
    ),
  ),
  plotPointLesson(5, "giving-coordinates", "Giving Coordinates", -3, 5, FULL_PLANE_BOUNDS, "intermediate"),
  lesson(
    5,
    "temperature-differences",
    "Temperature Differences",
    "intermediate",
    [
      mcScene(
        "l5-temp-1",
        "City A vs B",
        "City A at (2, 8) and City B at (2, 3) on a map (x = longitude offset, y = °C). Temperature difference?",
        ["5°C", "8°C", "3°C", "11°C"],
        "5°C",
        "l5_temp_diff",
        { correct: "8 − 3 = 5 (same x, compare y).", incorrect: "Vertical distance on chart.", hint: "5°." },
      ),
      mcScene(
        "l5-temp-2",
        "Below zero",
        "City at (1, −4) vs (1, 2). Difference in °C?",
        ["6°C", "2°C", "−6°C", "4°C"],
        "6°C",
        "l5_temp_neg",
        { correct: "2 − (−4) = 6.", incorrect: "Subtract y-values.", hint: "6." },
      ),
      graphScene(
        "l5-temp-3",
        "Plot readings",
        "Plot the warmer city at (1, 2).",
        1,
        2,
        "l5_temp_plot",
        { correct: "(1, 2).", incorrect: "Higher y = warmer.", hint: "(1, 2)." },
        FULL_PLANE_BOUNDS,
      ),
    ],
    mcScene(
      "l5-temp-final",
      "Mastery check",
      "Points (3, 5) and (3, −1) differ by how many degrees?",
      ["6", "4", "5", "2"],
      "6",
      "l5_temp_mastery",
      { correct: "5 − (−1) = 6.", incorrect: "|Δy| = 6.", hint: "6." },
    ),
  ),
];
