import {
  FULL_PLANE_BOUNDS,
  graphScene,
  horizontalLineLesson,
  lesson,
  mcScene,
  verticalLineLesson,
} from "./_helpers";

/** Level 3 — Lines on the coordinate plane */
export const MATH_COORD_LEVEL_3_SEEDS = [
  lesson(
    3,
    "from-points-to-lines",
    "From Points to Lines",
    "intermediate",
    [
      mcScene(
        "l3-ptl-1",
        "Collinear",
        "Two points determine a…",
        ["Line", "Circle", "Single point", "Plane only"],
        "Line",
        "l3_points_line",
        { correct: "Two distinct points define one line.", incorrect: "Connect the dots.", hint: "Line." },
      ),
      graphScene(
        "l3-ptl-2",
        "First point",
        "Place (1, 2) as the first point on a line.",
        1,
        2,
        "l3_first_point",
        { correct: "(1, 2).", incorrect: "Start the line here.", hint: "(1, 2)." },
        FULL_PLANE_BOUNDS,
      ),
      graphScene(
        "l3-ptl-3",
        "Second point",
        "Place (4, 2) — same y as (1, 2), forming a horizontal line.",
        4,
        2,
        "l3_second_point",
        { correct: "Same y → horizontal segment.", incorrect: "y = 2 for both.", hint: "(4, 2)." },
        FULL_PLANE_BOUNDS,
        [{ x1: 1, y1: 2, x2: 4, y2: 2 }],
      ),
    ],
    mcScene(
      "l3-ptl-final",
      "Mastery check",
      "Points (2, 5) and (6, 5) lie on a ___ line.",
      ["Horizontal", "Vertical", "Diagonal", "Curved"],
      "Horizontal",
      "l3_ptl_mastery",
      { correct: "Same y = 5.", incorrect: "Constant y.", hint: "Horizontal." },
    ),
  ),
  horizontalLineLesson(3, "horizontal-lines", "Horizontal Lines", 3),
  verticalLineLesson(3, "vertical-lines", "Vertical Lines", -2),
  lesson(
    3,
    "horizontal-and-vertical-lines",
    "Horizontal and Vertical Lines",
    "intermediate",
    [
      mcScene(
        "l3-both-1",
        "Identify horizontal",
        "Which equation is a horizontal line?",
        ["y = 4", "x = 4", "y = x", "x + y = 0"],
        "y = 4",
        "l3_both_horiz",
        { correct: "y constant → horizontal.", incorrect: "Flat line at y = 4.", hint: "y = 4." },
      ),
      mcScene(
        "l3-both-2",
        "Identify vertical",
        "Which equation is a vertical line?",
        ["x = −1", "y = −1", "y = x", "x = y"],
        "x = −1",
        "l3_both_vert",
        { correct: "x constant → vertical.", incorrect: "Upright at x = −1.", hint: "x = −1." },
      ),
      graphScene(
        "l3-both-3",
        "Intersection",
        "Lines x = 2 and y = −1 cross at (2, −1). Plot that point.",
        2,
        -1,
        "l3_both_cross",
        { correct: "(2, −1) is the intersection.", incorrect: "x from vertical, y from horizontal.", hint: "(2, −1)." },
        FULL_PLANE_BOUNDS,
        [
          { x1: 2, y1: -5, x2: 2, y2: 5 },
          { x1: -5, y1: -1, x2: 5, y2: -1 },
        ],
      ),
    ],
    mcScene(
      "l3-both-final",
      "Mastery check",
      "Where do x = 0 and y = 0 meet?",
      ["(0, 0)", "(0, 1)", "(1, 0)", "Nowhere"],
      "(0, 0)",
      "l3_both_mastery",
      { correct: "The origin.", incorrect: "Both axes at zero.", hint: "(0, 0)." },
    ),
  ),
  lesson(
    3,
    "interpreting-lines",
    "Interpreting Lines",
    "intermediate",
    [
      mcScene(
        "l3-int-1",
        "Reading y = −2",
        "Every point on y = −2 has…",
        ["y-coordinate −2", "x-coordinate −2", "x = y", "x + y = 2"],
        "y-coordinate −2",
        "l3_interpret_y",
        { correct: "Horizontal line 2 below x-axis.", incorrect: "y is always −2.", hint: "y = −2." },
      ),
      mcScene(
        "l3-int-2",
        "Reading x = 3",
        "Every point on x = 3 has…",
        ["x-coordinate 3", "y-coordinate 3", "y = 3x", "x = −3"],
        "x-coordinate 3",
        "l3_interpret_x",
        { correct: "Vertical line 3 right of origin.", incorrect: "x is always 3.", hint: "x = 3." },
      ),
      mcScene(
        "l3-int-3",
        "On the line",
        "Which point is on both x = 3 and y = −2?",
        ["(3, −2)", "(−2, 3)", "(3, 2)", "(−3, −2)"],
        "(3, −2)",
        "l3_interpret_both",
        { correct: "Intersection at (3, −2).", incorrect: "x = 3 and y = −2.", hint: "(3, −2)." },
      ),
    ],
    graphScene(
      "l3-int-final",
      "Mastery check",
      "On y = 1, plot (−2, 1).",
      -2,
      1,
      "l3_int_mastery",
      { correct: "(−2, 1) on the horizontal line.", incorrect: "y must be 1.", hint: "(−2, 1)." },
      FULL_PLANE_BOUNDS,
      [{ x1: -5, y1: 1, x2: 5, y2: 1 }],
    ),
  ),
];
