import {
  FULL_PLANE_BOUNDS,
  graphScene,
  lesson,
  levelReviewLesson,
  mcScene,
  plotPointLesson,
  quadrantLesson,
  segScene,
} from "./_helpers";

/** Level 2 — The 4 Quadrants */
export const MATH_COORD_LEVEL_2_SEEDS = [
  lesson(
    2,
    "negative-coordinates",
    "Negative Coordinates",
    "beginner",
    [
      mcScene(
        "l2-neg-1",
        "Left of origin",
        "A negative x-value means the point is…",
        ["Left of the y-axis", "Right of the y-axis", "Above the x-axis", "At the origin"],
        "Left of the y-axis",
        "l2_neg_x",
        { correct: "x < 0 → left.", incorrect: "Negative x is west.", hint: "Left." },
      ),
      mcScene(
        "l2-neg-2",
        "Below origin",
        "A negative y-value means the point is…",
        ["Below the x-axis", "Above the x-axis", "On the y-axis", "At (0, 0)"],
        "Below the x-axis",
        "l2_neg_y",
        { correct: "y < 0 → down.", incorrect: "Negative y is south.", hint: "Below." },
      ),
      graphScene(
        "l2-neg-3",
        "Plot (−2, 3)",
        "Place (−2, 3) on the full plane.",
        -2,
        3,
        "l2_neg_plot",
        { correct: "2 left, 3 up.", incorrect: "(−2, 3).", hint: "Quadrant II." },
        FULL_PLANE_BOUNDS,
      ),
    ],
    graphScene("l2-neg-final", "Mastery check", "Plot (−4, −1).", -4, -1, "l2_neg_mastery", {
      correct: "(−4, −1) in quadrant III.",
      incorrect: "4 left, 1 down.",
      hint: "(−4, −1).",
    }, FULL_PLANE_BOUNDS),
  ),
  lesson(
    2,
    "selecting-quadrants",
    "Selecting Quadrants",
    "beginner",
    [
      mcScene(
        "l2-sel-1",
        "Quadrant count",
        "How many quadrants does a coordinate plane have?",
        ["4", "2", "3", "8"],
        "4",
        "l2_quad_count",
        { correct: "Four regions by axis signs.", incorrect: "Axes split the plane into 4.", hint: "4." },
      ),
      segScene(
        "l2-sel-2",
        "Quadrant I signs",
        "Quadrant I has…",
        [
          { id: "pp", label: "x ≥ 0 and y ≥ 0" },
          { id: "np", label: "x < 0 and y ≥ 0" },
          { id: "nn", label: "x < 0 and y < 0" },
        ],
        "pp",
        "l2_quad1_signs",
        { correct: "Both coordinates non-negative.", incorrect: "Upper-right region.", hint: "Both +." },
      ),
      mcScene(
        "l2-sel-3",
        "Which quadrant?",
        "(−3, 2) is in quadrant…",
        ["II", "I", "III", "IV"],
        "II",
        "l2_quad_pick",
        { correct: "x negative, y positive → II.", incorrect: "Left and up.", hint: "II." },
      ),
    ],
    mcScene(
      "l2-sel-final",
      "Mastery check",
      "(5, −2) is in quadrant…",
      ["IV", "I", "II", "III"],
      "IV",
      "l2_sel_mastery",
      { correct: "x positive, y negative → IV.", incorrect: "Right and down.", hint: "IV." },
    ),
  ),
  quadrantLesson(2, "points-in-quadrants", "Points in Quadrants", -3, 4),
  plotPointLesson(2, "plotting-negative-coordinates", "Plotting Negative Coordinates", -5, -2),
  plotPointLesson(2, "identifying-more-points", "Identifying More Points", 4, -3),
  lesson(
    2,
    "city-temperatures",
    "City Temperatures",
    "intermediate",
    [
      mcScene(
        "l2-city-1",
        "Below freezing",
        "A city at (−2, 5) on a climate chart: x = months below average, y = °C. x = −2 means…",
        ["2 months below average", "2 months above", "−2°C", "5 months below"],
        "2 months below average",
        "l2_city_x",
        { correct: "Negative x → below average time.", incorrect: "Read x meaning.", hint: "2 months below." },
      ),
      mcScene(
        "l2-city-2",
        "Warm reading",
        "Point (1, −3): y = −3 means temperature…",
        ["3° below zero", "3° above zero", "At zero", "3 months cold"],
        "3° below zero",
        "l2_city_y",
        { correct: "y = −3 → below 0°C.", incorrect: "Negative y on temp axis.", hint: "Below zero." },
      ),
      graphScene(
        "l2-city-3",
        "Plot the reading",
        "Mark (−1, −4) for a cold, below-average month.",
        -1,
        -4,
        "l2_city_plot",
        { correct: "(−1, −4) in quadrant III.", incorrect: "1 left, 4 down.", hint: "(−1, −4)." },
        FULL_PLANE_BOUNDS,
      ),
    ],
    mcScene(
      "l2-city-final",
      "Mastery check",
      "Which point shows a warm month (y > 0) with below-average timing (x < 0)?",
      ["(−2, 4)", "(2, 4)", "(−2, −4)", "(2, −4)"],
      "(−2, 4)",
      "l2_city_mastery",
      { correct: "Quadrant II.", incorrect: "x < 0, y > 0.", hint: "(−2, 4)." },
    ),
  ),
  levelReviewLesson(2, "level-check", "Level Check", [
    { prompt: "(−1, −1) quadrant?", choices: ["III", "I", "II", "IV"], answer: "III" },
    { prompt: "Negative x means…", choices: ["Left of y-axis", "Right of y-axis", "Above x-axis", "Origin"], answer: "Left of y-axis" },
    { prompt: "(0, −3) lies on…", choices: ["y-axis", "x-axis", "origin", "diagonal"], answer: "y-axis" },
    { prompt: "Quadrant IV signs?", choices: ["x+, y−", "x−, y+", "x+, y+", "x−, y−"], answer: "x+, y−" },
  ]),
];
