import {
  findPartsLesson,
  lesson,
  mcScene,
  scaleRatioLesson,
  sortScene,
} from "./_helpers";

/** Level 3 — Scaling ratios */
export const MATH_PROP_LEVEL_3_SEEDS = [
  lesson(
    3,
    "scaling-down-to-scale-up",
    "Scaling Down to Scale Up",
    "intermediate",
    [
      mcScene(
        "l3-sdsu-1",
        "Unit rate first",
        "18 miles in 3 hours. Find miles per 1 hour first, then scale to 5 hours.",
        ["6 mi/hr", "3 mi/hr", "18 mi/hr", "5 mi/hr"],
        "6 mi/hr",
        "l3_sdsu_unit",
        { correct: "18 ÷ 3 = 6 per hour.", incorrect: "Divide to get per 1.", hint: "6 mi/hr." },
      ),
      mcScene(
        "l3-sdsu-2",
        "Scale up",
        "6 mi/hr × 5 hours = ?",
        ["30 miles", "6 miles", "11 miles", "25 miles"],
        "30 miles",
        "l3_sdsu_scale",
        { correct: "6 × 5 = 30.", incorrect: "Unit rate × hours.", hint: "30 miles." },
      ),
      sortScene(
        "l3-sdsu-3",
        "Strategy",
        "Order: scale down to 1, then scale up.",
        ["Divide to find per 1", "Multiply by target", "Add unrelated totals"],
        ["Divide to find per 1", "Multiply by target", "Add unrelated totals"],
        "l3_sdsu_steps",
        { correct: "Unit rate then scale.", incorrect: "Down to 1, up to target.", hint: "Divide then multiply." },
      ),
    ],
    mcScene(
      "l3-sdsu-final",
      "Mastery check",
      "24 items in 4 boxes → 7 boxes hold?",
      ["42", "28", "24", "7"],
      "42",
      "l3_sdsu_mastery",
      { correct: "6 per box × 7 = 42.", incorrect: "Find per 1, then ×7.", hint: "42." },
    ),
  ),
  scaleRatioLesson(3, "scaling-in-one-move", "Scaling in One Move", 2, 7, 4, "up"),
  findPartsLesson(3, "finding-the-total", "Finding the Total", 2, 3, 25),
  findPartsLesson(3, "finding-the-parts", "Finding the Parts", 3, 5, 40),
  lesson(
    3,
    "scaling-ratios-review",
    "Scaling Ratios",
    "intermediate",
    [
      mcScene(
        "l3-sr-1",
        "One move",
        "5:8 scaled by 3 in one move →",
        ["15:24", "8:11", "5:24", "15:8"],
        "15:24",
        "l3_scaling_ratios_move",
        { correct: "Multiply both by 3.", incorrect: "Same factor both parts.", hint: "15:24." },
      ),
      mcScene(
        "l3-sr-2",
        "From total",
        "45 split 2:7. Unit part?",
        ["5", "9", "45", "7"],
        "5",
        "l3_scaling_ratios_unit",
        { correct: "45 ÷ 9 = 5.", incorrect: "Total ÷ sum of parts.", hint: "5." },
      ),
      mcScene(
        "l3-sr-3",
        "Equivalent check",
        "4:10 = 2:5?",
        ["Yes", "No", "Only if doubled", "Never"],
        "Yes",
        "l3_scaling_ratios_equiv",
        { correct: "Divide both by 2.", incorrect: "Simplify 4:10.", hint: "Yes." },
      ),
    ],
    mcScene(
      "l3-sr-final",
      "Mastery check",
      "60 in ratio 1:4 → larger part?",
      ["48", "12", "60", "15"],
      "48",
      "l3_scaling_ratios_mastery",
      { correct: "4 × 12 = 48.", incorrect: "Find unit then ×4.", hint: "48." },
    ),
  ),
];
