import {
  compareRatesLesson,
  lesson,
  mcScene,
  unitRateLesson,
} from "./_helpers";

/** Level 4 — Unit rates */
export const MATH_PROP_LEVEL_4_SEEDS = [
  unitRateLesson(4, "how-much-for-one", "How Much for One", 15, 3, "miles"),
  unitRateLesson(4, "computing-unit-rates", "Computing Unit Rates", 24, 6, "pages"),
  compareRatesLesson(4, "two-unit-rates", "Two Unit Rates", 10, 2, 14, 4, "Store A", "Store B"),
  lesson(
    4,
    "scaling-down-to-scale-up-rates",
    "Scaling Down to Scale Up",
    "intermediate",
    [
      mcScene(
        "l4-sdsu-1",
        "Find per hour",
        "A car goes 120 miles in 2 hours. Miles per hour?",
        ["60", "120", "2", "240"],
        "60",
        "l4_sdsu_rate",
        { correct: "120 ÷ 2 = 60 mph.", incorrect: "Divide distance by time.", hint: "60." },
      ),
      mcScene(
        "l4-sdsu-2",
        "Scale time",
        "At 60 mph for 5 hours, distance?",
        ["300", "65", "60", "120"],
        "300",
        "l4_sdsu_dist",
        { correct: "60 × 5 = 300.", incorrect: "Rate × time.", hint: "300." },
      ),
      mcScene(
        "l4-sdsu-3",
        "Why scale down first?",
        "Finding per 1 helps because…",
        ["You can multiply any amount", "Ratios disappear", "Totals always add", "Units cancel"],
        "You can multiply any amount",
        "l4_sdsu_why",
        { correct: "Unit rate scales to any quantity.", incorrect: "Per 1 is the multiplier base.", hint: "Multiply any amount." },
      ),
    ],
    mcScene(
      "l4-sdsu-final",
      "Mastery check",
      "$36 for 4 lb → cost of 7 lb?",
      ["63", "36", "7", "49"],
      "63",
      "l4_sdsu_mastery",
      { correct: "$9/lb × 7 = $63.", incorrect: "Find $/lb first.", hint: "63." },
    ),
  ),
  lesson(
    4,
    "using-unit-rates",
    "Using Unit Rates",
    "intermediate",
    [
      mcScene(
        "l4-use-1",
        "Apply rate",
        "A printer makes 8 pages per minute. Pages in 12 minutes?",
        ["96", "20", "8", "12"],
        "96",
        "l4_using_rate",
        { correct: "8 × 12 = 96.", incorrect: "Rate × time.", hint: "96." },
      ),
      mcScene(
        "l4-use-2",
        "Find time",
        "Same printer: 40 pages takes ? minutes",
        ["5", "8", "40", "32"],
        "5",
        "l4_using_time",
        { correct: "40 ÷ 8 = 5 min.", incorrect: "Total ÷ rate.", hint: "5." },
      ),
      mcScene(
        "l4-use-3",
        "Units matter",
        "Unit rates must keep…",
        ["Consistent units", "Random units", "No labels", "Only totals"],
        "Consistent units",
        "l4_using_units",
        { correct: "Compare like units.", incorrect: "Same unit in numerator/denominator.", hint: "Consistent units." },
      ),
    ],
    mcScene(
      "l4-use-final",
      "Mastery check",
      "5 gal/min × 6 min = ?",
      ["30 gal", "11 gal", "5 gal", "6 gal"],
      "30 gal",
      "l4_using_mastery",
      { correct: "30 gallons.", incorrect: "Rate × minutes.", hint: "30 gal." },
    ),
  ),
];
