import {
  compareRatesLesson,
  lesson,
  mcScene,
  unitRateLesson,
} from "./_helpers";

/** Level 5 — Proportional relationships */
export const MATH_PROP_LEVEL_5_SEEDS = [
  lesson(
    5,
    "using-unit-rates-to-find-cost",
    "Using Unit Rates to Find Cost",
    "intermediate",
    [
      mcScene(
        "l5-cost-1",
        "Price per pound",
        "$12 for 4 lb of apples. Cost per lb?",
        ["$3", "$4", "$12", "$8"],
        "$3",
        "l5_cost_per_lb",
        { correct: "12 ÷ 4 = $3/lb.", incorrect: "Divide cost by pounds.", hint: "$3." },
      ),
      mcScene(
        "l5-cost-2",
        "Scale cost",
        "At $3/lb, cost of 6 lb?",
        ["$18", "$9", "$6", "$12"],
        "$18",
        "l5_cost_scale",
        { correct: "3 × 6 = $18.", incorrect: "Unit price × pounds.", hint: "$18." },
      ),
      mcScene(
        "l5-cost-3",
        "Proportional?",
        "Cost vs pounds at fixed price is…",
        ["Proportional", "Random", "Always decreasing", "Never linear"],
        "Proportional",
        "l5_cost_prop",
        { correct: "Cost = rate × pounds.", incorrect: "Constant unit price → proportional.", hint: "Proportional." },
      ),
    ],
    mcScene(
      "l5-cost-final",
      "Mastery check",
      "$20 for 5 items → 8 items cost?",
      ["$32", "$20", "$8", "$25"],
      "$32",
      "l5_cost_mastery",
      { correct: "$4 each × 8 = $32.", incorrect: "Find unit cost first.", hint: "$32." },
    ),
  ),
  unitRateLesson(5, "finding-unit-cost", "Finding Unit Cost", 35, 7, "dollars"),
  compareRatesLesson(5, "comparing-rates", "Comparing Rates", 8, 2, 15, 5, "Brand X", "Brand Y"),
  lesson(
    5,
    "proportional-relationships",
    "Proportional Relationships",
    "intermediate",
    [
      mcScene(
        "l5-pr-1",
        "Definition",
        "Two quantities are proportional when…",
        [
          "Their ratio is constant",
          "They always add to 100",
          "One is always larger",
          "They never change",
        ],
        "Their ratio is constant",
        "l5_prop_def",
        { correct: "Constant ratio y/x = k.", incorrect: "Proportional → fixed ratio.", hint: "Constant ratio." },
      ),
      mcScene(
        "l5-pr-2",
        "Table check",
        "x: 1,2,3 and y: 4,8,12. Proportional?",
        ["Yes", "No", "Only for x=1", "Cannot tell"],
        "Yes",
        "l5_prop_table",
        { correct: "y/x = 4 always.", incorrect: "Check y ÷ x.", hint: "Yes." },
      ),
      mcScene(
        "l5-pr-3",
        "Graph check",
        "Proportional graphs pass through…",
        ["(0, 0)", "(1, 1) only", "Any point", "Never the origin"],
        "(0, 0)",
        "l5_prop_graph",
        { correct: "y = kx through origin.", incorrect: "Proportional lines through (0,0).", hint: "(0, 0)." },
      ),
    ],
    mcScene(
      "l5-pr-final",
      "Mastery check",
      "y = 5x is a proportional relationship?",
      ["Yes", "No", "Only for x > 0", "Only linear"],
      "Yes",
      "l5_prop_mastery",
      { correct: "Constant k = 5.", incorrect: "y = kx form.", hint: "Yes." },
    ),
  ),
];
