import {
  constantKLesson,
  lesson,
  mcScene,
  plotProportionalLesson,
} from "./_helpers";

/** Level 6 — Graphing proportional relationships */
export const MATH_PROP_LEVEL_6_SEEDS = [
  plotProportionalLesson(6, "plotting-points", "Plotting Points", 2, 3),
  plotProportionalLesson(6, "plotting-equivalent-ratios", "Plotting Equivalent Ratios", 3, 2),
  lesson(
    6,
    "using-graphs",
    "Using Graphs",
    "intermediate",
    [
      mcScene(
        "l6-ug-1",
        "Read x",
        "A proportional graph shows (4, 12). What is x?",
        ["4", "12", "3", "16"],
        "4",
        "l6_using_graphs_x",
        { correct: "First coordinate is x.", incorrect: "Read horizontal value.", hint: "4." },
      ),
      mcScene(
        "l6-ug-2",
        "Read y",
        "For (4, 12), y = ?",
        ["12", "4", "3", "48"],
        "12",
        "l6_using_graphs_y",
        { correct: "Second coordinate is y.", incorrect: "Read vertical value.", hint: "12." },
      ),
      mcScene(
        "l6-ug-3",
        "Predict",
        "Line through origin with (2, 6). When x = 5, y = ?",
        ["15", "10", "6", "5"],
        "15",
        "l6_using_graphs_predict",
        { correct: "k = 3, so 5 × 3 = 15.", incorrect: "Find k from the point.", hint: "15." },
      ),
    ],
    mcScene(
      "l6-ug-final",
      "Mastery check",
      "(1, 7) on a proportional line. y when x = 3?",
      ["21", "7", "10", "3"],
      "21",
      "l6_using_graphs_mastery",
      { correct: "k = 7 → 3 × 7 = 21.", incorrect: "Triple both.", hint: "21." },
    ),
  ),
  plotProportionalLesson(6, "plotting-unit-rate", "Plotting Unit Rate", 1, 4),
  lesson(
    6,
    "graphing-relationships",
    "Graphing Relationships",
    "intermediate",
    [
      mcScene(
        "l6-gr-1",
        "Points align",
        "Equivalent ratios (2,5), (4,10), (6,15) lie on…",
        ["One line through origin", "Three separate lines", "A curve", "Random points"],
        "One line through origin",
        "l6_graph_rel_line",
        { correct: "Same k = 2.5.", incorrect: "Proportional → one line.", hint: "One line." },
      ),
      mcScene(
        "l6-gr-2",
        "Not proportional",
        "Which point is NOT on y = 2x?",
        ["(3, 7)", "(1, 2)", "(4, 8)", "(5, 10)"],
        "(3, 7)",
        "l6_graph_rel_off",
        { correct: "3 × 2 = 6 ≠ 7.", incorrect: "Check y = 2x.", hint: "(3, 7)." },
      ),
      mcScene(
        "l6-gr-3",
        "Ratio from graph",
        "From (2, 8), the ratio y:x equals…",
        ["4", "2", "8", "10"],
        "4",
        "l6_graph_rel_ratio",
        { correct: "8 ÷ 2 = 4 = k.", incorrect: "y/x is the unit rate.", hint: "4." },
      ),
    ],
    mcScene(
      "l6-gr-final",
      "Mastery check",
      "Points on y = kx through origin are…",
      ["Proportional", "Never proportional", "Always negative", "Unrelated"],
      "Proportional",
      "l6_graph_rel_mastery",
      { correct: "Constant k.", incorrect: "Proportional graph.", hint: "Proportional." },
    ),
  ),
  constantKLesson(6, "constant-of-proportionality", "Constant of Proportionality", 4, 10),
];
