import {
  equationFromPointLesson,
  graphFromEquationLesson,
  lesson,
  mcScene,
} from "./_helpers";

/** Level 7 — Writing equations */
export const MATH_PROP_LEVEL_7_SEEDS = [
  lesson(
    7,
    "writing-equations",
    "Writing Equations",
    "intermediate",
    [
      mcScene(
        "l7-we-1",
        "Form",
        "A proportional relationship is written as…",
        ["y = kx", "y = x + k", "y = k + x", "y = x/k only"],
        "y = kx",
        "l7_writing_form",
        { correct: "k is the constant of proportionality.", incorrect: "No constant term except k×x.", hint: "y = kx." },
      ),
      mcScene(
        "l7-we-2",
        "Find k",
        "If y = 6 when x = 2, then k = ?",
        ["3", "6", "2", "8"],
        "3",
        "l7_writing_k",
        { correct: "k = 6/2 = 3.", incorrect: "Divide y by x.", hint: "3." },
      ),
      mcScene(
        "l7-we-3",
        "Write it",
        "k = 4 gives equation…",
        ["y = 4x", "y = x + 4", "y = 4/x", "x = 4y"],
        "y = 4x",
        "l7_writing_eq",
        { correct: "Substitute k into y = kx.", incorrect: "y = kx.", hint: "y = 4x." },
      ),
    ],
    mcScene(
      "l7-we-final",
      "Mastery check",
      "Proportional equations have no…",
      ["Constant added term", "Variable x", "Coefficient k", "Origin point"],
      "Constant added term",
      "l7_writing_mastery",
      { correct: "Pure y = kx — no + b.", incorrect: "No y-intercept except 0.", hint: "No added constant." },
    ),
  ),
  equationFromPointLesson(7, "equation-from-a-point", "Equation from a Point", 3, 12),
  graphFromEquationLesson(7, "graphing-from-an-equation", "Graphing from an Equation", 2),
  lesson(
    7,
    "graphing-comparisons",
    "Graphing Comparisons",
    "intermediate",
    [
      mcScene(
        "l7-gc-1",
        "Two lines",
        "y = 2x and y = 5x both pass through…",
        ["(0, 0)", "(2, 0)", "(0, 5)", "(5, 2)"],
        "(0, 0)",
        "l7_graph_comp_origin",
        { correct: "Both proportional → origin.", incorrect: "Plug in x = 0.", hint: "(0, 0)." },
      ),
      mcScene(
        "l7-gc-2",
        "Steeper line",
        "Which grows faster for x > 0?",
        ["y = 5x", "y = 2x", "Same rate", "Neither"],
        "y = 5x",
        "l7_graph_comp_steeper",
        { correct: "Larger k → steeper.", incorrect: "Compare k values.", hint: "y = 5x." },
      ),
      mcScene(
        "l7-gc-3",
        "Same x",
        "At x = 3, y = 2x gives 6 and y = 5x gives…",
        ["15", "5", "3", "8"],
        "15",
        "l7_graph_comp_values",
        { correct: "5 × 3 = 15.", incorrect: "Evaluate each equation.", hint: "15." },
      ),
    ],
    mcScene(
      "l7-gc-final",
      "Mastery check",
      "Comparing y = 3x and y = x: which has larger y at x = 4?",
      ["y = 3x", "y = x", "Equal", "Cannot tell"],
      "y = 3x",
      "l7_graph_comp_mastery",
      { correct: "12 vs 4.", incorrect: "Larger k wins.", hint: "y = 3x." },
    ),
  ),
];
