/** Visual Problem Engine — balancing equations: order & atom bookkeeping (chemistry). */
export const CHEMISTRY_BALANCING_LESSON_SEED = {
  id: "lesson-balancing-equations-visual",
  title: "Balancing equations: order your thinking",
  subject: "Chemistry",
  topic: "Balancing equations",
  level: "beginner" as const,
  scenes: [
    {
      id: "chem-bal-1-equation-layout",
      title: "Read the reaction left to right",
      type: "segment_select" as const,
      prompt: "What do you write on the left of the arrow in a standard chemical equation?",
      visualPrompt: "Convention: start with what you begin with.",
      data: {
        segments: [
          { id: "reactants", label: "Reactants" },
          { id: "arrow", label: "Arrow only" },
          { id: "products", label: "Products" },
          { id: "states", label: "State symbols only (no formulas)" },
        ],
      },
      interaction: "select_choice" as const,
      validation: { type: "choice_match" as const, expectedChoice: "reactants" },
      feedback: {
        correct: "Reactants → arrow → products is the convention every balanced equation follows.",
        incorrect: "The arrow sits between what you start with and what you make.",
        hint: "Start with what you begin with on the left.",
      },
      masteryTarget: { conceptNodeId: "balancing-equations", skill: "equation_layout" },
    },
    {
      id: "chem-bal-2-combustion-heuristic",
      title: "Combustion balancing order",
      type: "segment_select" as const,
      prompt: "For hydrocarbon combustion, which element do you usually balance first?",
      visualPrompt: "Many teachers lock the fuel skeleton before touching O₂ from air.",
      data: {
        segments: [
          { id: "carbon", label: "Carbon in the fuel" },
          { id: "oxygen", label: "Oxygen first" },
          { id: "hydrogen", label: "Hydrogen first (before carbon)" },
          { id: "metals", label: "Metals first (always)" },
        ],
      },
      interaction: "select_choice" as const,
      validation: { type: "choice_match" as const, expectedChoice: "carbon" },
      feedback: {
        correct: "Carbon in the fuel first, then hydrogen, then oxygen — then audit atom counts.",
        incorrect: "Oxygen from air is usually adjusted last after C and H are locked in.",
        hint: "Start with atoms inside the fuel molecule before touching diatomic oxygen.",
      },
      masteryTarget: { conceptNodeId: "balancing-equations", skill: "combustion_balance_order" },
    },
    {
      id: "chem-bal-3-atom-grid",
      title: "Atom count toy",
      type: "grid_model" as const,
      prompt: "A tiny model shows 6 “atom slots” on the left. Shade exactly 4 to show “four atoms of one element before balancing.”",
      visualPrompt: "Tap exactly four cells in this 2×3 grid.",
      data: { rows: 2, columns: 3 },
      interaction: "tap_to_fill" as const,
      validation: { type: "count_match" as const, expectedCount: 4 },
      feedback: {
        correct: "Four shaded slots — a stand-in for matching counts before you adjust coefficients.",
        incorrect: "The prompt asks for exactly four cells shaded.",
        hint: "Count taps; undo extras if you overshoot.",
      },
      masteryTarget: { conceptNodeId: "balancing-equations", skill: "atom_inventory" },
    },
    {
      id: "chem-bal-4-mc-water-coef",
      title: "Coefficients in context",
      type: "multiple_choice" as const,
      prompt: "For 2 H₂(g) + O₂(g) → 2 H₂O(l), what coefficient belongs in front of H₂O?",
      visualPrompt: "Pick the number that balances H and O together.",
      data: { choices: ["2", "1", "3", "4"] },
      interaction: "select_choice" as const,
      validation: { type: "choice_match" as const, expectedChoice: "2" },
      feedback: {
        correct: "Two water molecules carry four H and two O, matching two H₂ and one O₂ on the left.",
        incorrect: "Count H on both sides after you pick a coefficient for water.",
        hint: "You need two H₂O to close both H and O counts.",
      },
      masteryTarget: { conceptNodeId: "balancing-equations", skill: "water_coefficient" },
    },
    {
      id: "chem-bal-5-ratio-bar",
      title: "Mole ratio as parts",
      type: "fraction_bar" as const,
      prompt: "A 2 : 1 ratio of H₂ to O₂ (in moles) is modeled as 6 equal parts: shade 4 parts for “hydrogen’s share” (two thirds).",
      visualPrompt: "Two thirds of six is four — shade four slices.",
      data: { totalParts: 6 },
      interaction: "tap_to_fill" as const,
      validation: { type: "count_match" as const, expectedCount: 4 },
      feedback: {
        correct: "Four of six is 2/3 — the same ratio as 2 mol H₂ in a 2 : 1 mix with O₂.",
        incorrect: "You need exactly four of the six parts shaded for this toy ratio.",
        hint: "Leave two slices unshaded for the oxygen “one third” partner.",
      },
      masteryTarget: { conceptNodeId: "mole-concept", skill: "mole_ratio_bar" },
    },
  ],
  finalMasteryCheck: {
    id: "chem-bal-final-ph",
    title: "States and solutions",
    type: "number_line" as const,
    prompt: "Aqueous acid waste might be pH ≈ 2. Mark 2 on this 0–14 line (step 1).",
    visualPrompt: "Strongly acidic but not negative pH.",
    data: { min: 0, max: 14, step: 1 },
    interaction: "place_point" as const,
    validation: {
      type: "point_match" as const,
      expectedPoint: { x: 2, y: 0 },
      tolerance: 0.45,
    },
    feedback: {
      correct: "pH 2 is strongly acidic — left of neutral but still on the 0–14 scale.",
      incorrect: "Slide left from 7 toward the acid side; stop at the tick labeled 2.",
      hint: "Two ticks to the right of 0 if the line starts at 0.",
    },
    masteryTarget: { conceptNodeId: "balancing-equations", skill: "acidic_waste_ph" },
  },
} as const;
