/** Visual Problem Engine — lab procedure & dilution safety (chemistry). */
export const CHEMISTRY_LAB_SAFETY_LESSON_SEED = {
  id: "lesson-acid-dilution-and-lab-flow",
  title: "Acid dilution & lab thinking",
  subject: "Chemistry",
  topic: "Lab safety",
  level: "beginner" as const,
  scenes: [
    {
      id: "chem-lab-1-dilution",
      title: "Never the dangerous order",
      type: "segment_select" as const,
      prompt: "What is the very first thing you should do before diluting concentrated acid?",
      visualPrompt: "Safety and identity before any pouring.",
      data: {
        segments: [
          { id: "goggles", label: "Put on goggles and read the bottle label" },
          { id: "acid_first", label: "Pour water into concentrated acid" },
          { id: "label_done", label: "Label the finished dilution first" },
          { id: "acid_to_air", label: "Open concentrated acid in an unventilated corner" },
        ],
      },
      interaction: "select_choice" as const,
      validation: { type: "choice_match" as const, expectedChoice: "goggles" },
      feedback: {
        correct: "PPE and label check first — then water ready, then acid into water while stirring, then label the product.",
        incorrect: "Never pour water into concentrated acid; never skip PPE before handling corrosives.",
        hint: "Goggles before glassware moves; acid joins water, not the reverse.",
      },
      masteryTarget: { conceptNodeId: "reaction-types", skill: "acid_dilution_order" },
    },
    {
      id: "chem-lab-2-weighing",
      title: "Mass of a solid",
      type: "segment_select" as const,
      prompt: "On an analytical balance, what comes immediately after choosing the container you will use?",
      visualPrompt: "You need a zero reference with that vessel on the pan.",
      data: {
        segments: [
          { id: "tare", label: "Tare / zero with the empty container on the pan" },
          { id: "record", label: "Record the final mass first" },
          { id: "add_solid", label: "Add solid before the container touches the pan" },
          { id: "random", label: "Calibrate the hallway scale" },
        ],
      },
      interaction: "select_choice" as const,
      validation: { type: "choice_match" as const, expectedChoice: "tare" },
      feedback: {
        correct: "Choose container → tare → add sample → record — tare locks the baseline for that vessel.",
        incorrect: "You cannot interpret mass until the balance is zeroed with the vessel you will use.",
        hint: "Taring happens after the container is chosen but before you add the chemical.",
      },
      masteryTarget: { conceptNodeId: "mole-concept", skill: "mass_measurement_order" },
    },
    {
      id: "chem-lab-3-stoich-grid",
      title: "Mole ratio toy",
      type: "grid_model" as const,
      prompt: "A balanced toy reaction needs 2 “product squares” for every 3 “reactant squares.” Shade exactly 2 cells in this 2×4 grid to show “products formed” in a minimal model.",
      visualPrompt: "Pick any two cells — we are only anchoring the number 2.",
      data: { rows: 2, columns: 4 },
      interaction: "tap_to_fill" as const,
      validation: { type: "count_match" as const, expectedCount: 2 },
      feedback: {
        correct: "Two shaded cells matches the “2” in a 2:3 product-to-reactant toy ratio.",
        incorrect: "Count again — the prompt asks for exactly two shaded cells.",
        hint: "Two taps total; undo extras if needed.",
      },
      masteryTarget: { conceptNodeId: "stoichiometry-calc", skill: "ratio_visual" },
    },
    {
      id: "chem-lab-4-mc-state-symbol",
      title: "Symbols on equations",
      type: "multiple_choice" as const,
      prompt: "Which symbol means aqueous (dissolved in water)?",
      visualPrompt: "Often written as a subscript parenthetical.",
      data: { choices: ["(aq)", "(s)", "(l)", "(g)"] },
      interaction: "select_choice" as const,
      validation: { type: "choice_match" as const, expectedChoice: "(aq)" },
      feedback: {
        correct: "(aq) marks species dissolved in water — common in net ionic work.",
        incorrect: "(s) solid, (l) liquid, (g) gas — only (aq) is “in solution.”",
        hint: "Think “aqua” like water.",
      },
      masteryTarget: { conceptNodeId: "balancing-equations", skill: "state_symbols" },
    },
    {
      id: "chem-lab-5-volume-line",
      title: "Reading a volume",
      type: "number_line" as const,
      prompt: "A graduated cylinder reads 42 mL on a 40–50 mL zoom line (step 1 mL). Mark 42.",
      visualPrompt: "40 on the left, 50 on the right.",
      data: { min: 40, max: 50, step: 1 },
      interaction: "place_point" as const,
      validation: {
        type: "point_match" as const,
        expectedPoint: { x: 42, y: 0 },
        tolerance: 0.55,
      },
      feedback: {
        correct: "Two ticks past 40 lands on 42 — that matches a careful volume reading.",
        incorrect: "Slide to the second mark after 40 if each step is 1 mL.",
        hint: "40, 41, 42 — stop on the third tick from 40.",
      },
      masteryTarget: { conceptNodeId: "mole-concept", skill: "volume_reading" },
    },
  ],
  finalMasteryCheck: {
    id: "chem-lab-final-fraction",
    title: "Concentration intuition",
    type: "fraction_bar" as const,
    prompt: "A stock solution is “full strength” in this 10-part bar. Shade 2 parts to show roughly a 1 : 5 dilution (two parts diluted stock in a mental model).",
    visualPrompt: "Exactly two slices.",
    data: { totalParts: 10 },
    interaction: "tap_to_fill" as const,
    validation: { type: "count_match" as const, expectedCount: 2 },
    feedback: {
      correct: "Two of ten is a 20% slice — a useful visual when thinking about dilution factors.",
      incorrect: "Tap exactly two parts of the ten to match the story.",
      hint: "Count aloud while tapping; stop at two shaded slices.",
    },
    masteryTarget: { conceptNodeId: "stoichiometry-calc", skill: "dilution_fraction_model" },
  },
} as const;
