/** Visual Problem Engine — filling order & simple atomic models (chemistry). */
export const CHEMISTRY_ATOMS_LESSON_SEED = {
  id: "lesson-electron-filling-order",
  title: "Building up atoms: energy levels",
  subject: "Chemistry",
  topic: "Atomic structure",
  level: "beginner" as const,
  scenes: [
    {
      id: "chem-aufbau-1-sublevels",
      title: "Aufbau order (first subshells)",
      type: "segment_select" as const,
      prompt: "Which subshell is filled first among these (lowest energy)?",
      visualPrompt: "Smallest n and tightest binding wins for the first electron in a neutral atom build-up.",
      data: {
        segments: [
          { id: "1s", label: "1s" },
          { id: "2s", label: "2s" },
          { id: "2p", label: "2p" },
          { id: "3s", label: "3s" },
        ],
      },
      interaction: "select_choice" as const,
      validation: { type: "choice_match" as const, expectedChoice: "1s" },
      feedback: {
        correct: "1s is always lowest here — then 2s → 2p → 3s as you climb the aufbau ladder.",
        incorrect: "The 1s subshell is closest to the nucleus and lowest in energy in this picture.",
        hint: "Smallest principal quantum number first.",
      },
      masteryTarget: { conceptNodeId: "atomic-structure", skill: "aufbau_order" },
    },
    {
      id: "chem-aufbau-2-period-trend",
      title: "Across a period",
      type: "drag_drop_sort" as const,
      prompt: "Order these ideas as you move left → right across a period (same row).",
      visualPrompt: "Think nuclear charge vs electron addition.",
      data: {
        items: [
          "Valence electrons added one by one in the same shell",
          "Nuclear charge increases (more protons)",
          "Atomic radius tends to shrink (same-shell attraction)",
        ],
      },
      interaction: "reorder" as const,
      validation: {
        type: "ordered_sequence" as const,
        expectedOrder: [
          "Nuclear charge increases (more protons)",
          "Valence electrons added one by one in the same shell",
          "Atomic radius tends to shrink (same-shell attraction)",
        ],
      },
      feedback: {
        correct: "More protons pull the same shell inward while you add valence electrons — that is the period trend story.",
        incorrect: "Nuclear charge climbs before you reason about how tightly the outer shell is held.",
        hint: "Start with “more protons in the nucleus.”",
      },
      masteryTarget: { conceptNodeId: "periodic-trends", skill: "period_left_to_right" },
    },
    {
      id: "chem-aufbau-3-valence-grid",
      title: "Valence electron toy model",
      type: "grid_model" as const,
      prompt: "Group 2 elements have 2 valence electrons in the simplest Lewis-style toy. Shade exactly 2 cells in this 2×3 grid.",
      visualPrompt: "Any two cells count — we are only practicing “two valence dots.”",
      data: { rows: 2, columns: 3 },
      interaction: "tap_to_fill" as const,
      validation: { type: "count_match" as const, expectedCount: 2 },
      feedback: {
        correct: "Two shaded cells matches “two valence electrons” in this simplified picture.",
        incorrect: "Tap exactly two cells — not one, not three.",
        hint: "Pick any two squares and leave the rest empty.",
      },
      masteryTarget: { conceptNodeId: "atomic-structure", skill: "valence_count_model" },
    },
    {
      id: "chem-aufbau-4-mc-ion",
      title: "Ion charge",
      type: "multiple_choice" as const,
      prompt: "What charge does a sodium atom most commonly take when it becomes an ion?",
      visualPrompt: "Sodium is in group 1.",
      data: { choices: ["+1", "−1", "+2", "0"] },
      interaction: "select_choice" as const,
      validation: { type: "choice_match" as const, expectedChoice: "+1" },
      feedback: {
        correct: "Na loses one valence electron to mimic a noble gas shell — Na⁺.",
        incorrect: "Group 1 atoms typically lose one electron, not gain two.",
        hint: "Think “one electron above a full inner shell.”",
      },
      masteryTarget: { conceptNodeId: "atomic-structure", skill: "group1_cation" },
    },
    {
      id: "chem-aufbau-5-ph-scale",
      title: "pH on a line",
      type: "number_line" as const,
      prompt: "Mark neutral pH on this 0–14 scale (steps of 1).",
      visualPrompt: "Drag the marker to pure water at room temperature.",
      data: { min: 0, max: 14, step: 1 },
      interaction: "place_point" as const,
      validation: {
        type: "point_match" as const,
        expectedPoint: { x: 7, y: 0 },
        tolerance: 0.45,
      },
      feedback: {
        correct: "pH 7 is neutral — your marker sits at the balance between acid and base on the scale.",
        incorrect: "Neutral is halfway between 0 and 14 on the standard pH ruler.",
        hint: "Count seven ticks from the left if the line starts at 0.",
      },
      masteryTarget: { conceptNodeId: "atomic-structure", skill: "ph_neutral" },
    },
  ],
  finalMasteryCheck: {
    id: "chem-aufbau-final-graph",
    title: "Trend sketch",
    type: "graph_plot" as const,
    prompt: "Atomic radius decreases across period 3 in a simple cartoon: place a point where “later element, smaller atom” might sit — high period number on x, smaller radius on y (toy axes 0–6).",
    visualPrompt: "Try around (5, 2): far along the period, pulled in.",
    data: {
      xMin: 0,
      xMax: 6,
      yMin: 0,
      yMax: 6,
      lines: [],
    },
    interaction: "place_point" as const,
    validation: {
      type: "point_match" as const,
      expectedPoint: { x: 5, y: 2 },
      tolerance: 0.65,
    },
    feedback: {
      correct: "Farther across the period with a lower y matches “smaller atom” in this toy plot.",
      incorrect: "Slide right on x and keep y modest to show shrinkage across the row.",
      hint: "Avoid the top-left corner; think “right and somewhat down.”",
    },
    masteryTarget: { conceptNodeId: "periodic-trends", skill: "radius_trend_point" },
  },
} as const;
