/** Visual Problem Engine — quadratic equations via drag-and-drop (math). */
export const MATH_QUADRATIC_EQUATIONS_LESSON_SEED = {
  id: "lesson-quadratic-equations-drag",
  title: "Quadratic equations by drag & drop",
  subject: "Algebra",
  topic: "Quadratic equations",
  level: "beginner" as const,
  scenes: [
    {
      id: "quad-1-factor-steps",
      title: "Factor in order",
      type: "drag_drop_sort" as const,
      prompt: "Reorder the steps to solve x² − 5x + 6 = 0 by factoring.",
      visualPrompt: "Find numbers → write factors → zero-product → solutions.",
      data: {
        items: [
          "Solutions: x = 2 or x = 3",
          "Set each factor to zero: (x − 2)(x − 3) = 0",
          "Find two numbers that multiply to +6 and add to −5: −2 and −3",
          "Write (x − 2)(x − 3) = 0",
        ],
      },
      interaction: "reorder" as const,
      validation: {
        type: "ordered_sequence" as const,
        expectedOrder: [
          "Find two numbers that multiply to +6 and add to −5: −2 and −3",
          "Write (x − 2)(x − 3) = 0",
          "Set each factor to zero: (x − 2)(x − 3) = 0",
          "Solutions: x = 2 or x = 3",
        ],
      },
      feedback: {
        correct: "−2 × −3 = 6 and −2 + −3 = −5 — then zero-product gives x = 2 and x = 3.",
        incorrect: "Start by finding the pair of numbers, then build the factors.",
        hint: "Which step finds −2 and −3 before writing parentheses?",
      },
      masteryTarget: { conceptNodeId: "quadratic-equations", skill: "factor_steps_order" },
    },
    {
      id: "quad-2-match-roots",
      title: "Match the roots",
      type: "drag_drop_match" as const,
      prompt: "Place the correct roots of x² − 5x + 6 = 0 into the slots (smaller first).",
      visualPrompt: "(x − 2)(x − 3) = 0 → x = 2 and x = 3.",
      data: {
        items: [
          { id: "r2", label: "x = 2" },
          { id: "r3", label: "x = 3" },
          { id: "rn2", label: "x = −2" },
        ],
        slots: [
          { id: "root_a", label: "Smaller root" },
          { id: "root_b", label: "Larger root" },
        ],
      },
      interaction: "drag_to_place" as const,
      validation: {
        type: "slot_match" as const,
        expected: { root_a: "r2", root_b: "r3" },
      },
      feedback: {
        correct: "x = 2 and x = 3 — the roots from (x − 2)(x − 3) = 0.",
        incorrect: "Both roots are positive: 2 and 3, not −2.",
        hint: "Which two values make each factor zero?",
      },
      masteryTarget: { conceptNodeId: "quadratic-equations", skill: "match_quadratic_roots" },
    },
    {
      id: "quad-3-build-factors",
      title: "Build the factors",
      type: "drag_drop_match" as const,
      prompt: "Drag the correct binomial factors for x² + 7x + 12 into the slots.",
      visualPrompt: "Need two numbers that multiply to 12 and add to 7: 3 and 4.",
      data: {
        items: [
          { id: "p3", label: "(x + 3)" },
          { id: "p4", label: "(x + 4)" },
          { id: "p2", label: "(x + 2)" },
          { id: "p6", label: "(x + 6)" },
        ],
        slots: [
          { id: "slot_plus3", label: "Factor with +3" },
          { id: "slot_plus4", label: "Factor with +4" },
        ],
      },
      interaction: "drag_to_place" as const,
      validation: {
        type: "slot_match" as const,
        expected: { slot_plus3: "p3", slot_plus4: "p4" },
      },
      feedback: {
        correct: "(x + 3)(x + 4) expands to x² + 7x + 12.",
        incorrect: "3 × 4 = 12 and 3 + 4 = 7 — use (x + 3) and (x + 4).",
        hint: "Match the constant +12 and the middle term +7x.",
      },
      masteryTarget: { conceptNodeId: "quadratic-equations", skill: "build_quadratic_factors" },
    },
    {
      id: "quad-4-vertex",
      title: "Parabola vertex",
      type: "graph_plot" as const,
      prompt: "The graph of y = (x − 2)² − 1 is a parabola. Place its vertex on the grid.",
      visualPrompt: "Vertex form (x − h)² + k → vertex (h, k) = (2, −1).",
      data: {
        xMin: -1,
        xMax: 5,
        yMin: -4,
        yMax: 4,
        lines: [],
      },
      interaction: "place_point" as const,
      validation: {
        type: "point_match" as const,
        expectedPoint: { x: 2, y: -1 },
        tolerance: 0.45,
      },
      feedback: {
        correct: "Vertex (2, −1) — the lowest point of y = (x − 2)² − 1.",
        incorrect: "In (x − 2)² − 1, h = 2 and k = −1.",
        hint: "Read h and k from vertex form: (x − h)² + k.",
      },
      masteryTarget: { conceptNodeId: "quadratic-equations", skill: "quadratic_vertex_plot" },
    },
    {
      id: "quad-5-standard-form",
      title: "Standard form ax² + bx + c",
      type: "drag_drop_match" as const,
      prompt: "Match each term of x² + 5x + 6 to the correct slot in ax² + bx + c.",
      visualPrompt: "a = 1 on x², b = 5 on x, c = 6 constant.",
      data: {
        items: [
          { id: "t_x2", label: "x²" },
          { id: "t_5x", label: "5x" },
          { id: "t_6", label: "6" },
          { id: "t_x", label: "x" },
          { id: "t_5", label: "5" },
        ],
        slots: [
          { id: "term_a", label: "ax² term" },
          { id: "term_b", label: "bx term" },
          { id: "term_c", label: "Constant c" },
        ],
      },
      interaction: "drag_to_place" as const,
      validation: {
        type: "slot_match" as const,
        expected: { term_a: "t_x2", term_b: "t_5x", term_c: "t_6" },
      },
      feedback: {
        correct: "x² + 5x + 6 — a = 1, b = 5, c = 6 in standard form.",
        incorrect: "The x² term is a, the x term is b, and the lone number is c.",
        hint: "Place 5x in the bx slot, not just x or 5.",
      },
      masteryTarget: { conceptNodeId: "quadratic-equations", skill: "quadratic_standard_form" },
    },
    {
      id: "quad-6-formula-steps",
      title: "Quadratic formula steps",
      type: "drag_drop_sort" as const,
      prompt: "Order the steps to solve x² + 6x + 5 = 0 with the quadratic formula.",
      visualPrompt: "Identify a, b, c → substitute → simplify → solve.",
      data: {
        items: [
          "Solutions: x = −1 or x = −5",
          "Identify a = 1, b = 6, c = 5",
          "Substitute into x = (−b ± √(b² − 4ac)) / 2a",
          "Simplify: x = (−6 ± 4) / 2",
        ],
      },
      interaction: "reorder" as const,
      validation: {
        type: "ordered_sequence" as const,
        expectedOrder: [
          "Identify a = 1, b = 6, c = 5",
          "Substitute into x = (−b ± √(b² − 4ac)) / 2a",
          "Simplify: x = (−6 ± 4) / 2",
          "Solutions: x = −1 or x = −5",
        ],
      },
      feedback: {
        correct: "a, b, c first — then formula, simplify, and read off x = −1 and x = −5.",
        incorrect: "You need coefficients before substituting into the formula.",
        hint: "What are a, b, and c for x² + 6x + 5?",
      },
      masteryTarget: { conceptNodeId: "quadratic-equations", skill: "quadratic_formula_order" },
    },
    {
      id: "quad-7-cts-steps",
      title: "Complete the square — steps",
      type: "drag_drop_sort" as const,
      prompt: "Reorder the steps to solve x² + 6x + 5 = 0 by completing the square.",
      visualPrompt: "Move c → add (b/2)² → factor the perfect square → take square roots.",
      data: {
        items: [
          "Solutions: x = −1 or x = −5",
          "(x + 3)² = 4",
          "Move constant: x² + 6x = −5",
          "Add 9 to both sides: x² + 6x + 9 = 4",
          "Take half of 6 and square: (6/2)² = 9",
        ],
      },
      interaction: "reorder" as const,
      validation: {
        type: "ordered_sequence" as const,
        expectedOrder: [
          "Move constant: x² + 6x = −5",
          "Take half of 6 and square: (6/2)² = 9",
          "Add 9 to both sides: x² + 6x + 9 = 4",
          "(x + 3)² = 4",
          "Solutions: x = −1 or x = −5",
        ],
      },
      feedback: {
        correct: "(x + 3)² = 4 → x = −3 ± 2 — same roots as factoring.",
        incorrect: "Move the +5 first, then add the square of half the x-coefficient.",
        hint: "What do you add to both sides after x² + 6x = −5?",
      },
      masteryTarget: { conceptNodeId: "quadratic-equations", skill: "complete_square_steps" },
    },
    {
      id: "quad-8-cts-form",
      title: "Complete the square — form",
      type: "drag_drop_match" as const,
      prompt: "After completing the square on x² + 6x + 5 = 0, match the factored left side and the value on the right.",
      visualPrompt: "x² + 6x + 9 = (x + 3)² and the equation becomes (x + 3)² = 4.",
      data: {
        items: [
          { id: "sq3", label: "(x + 3)²" },
          { id: "sq6", label: "(x + 6)²" },
          { id: "eq4", label: "4" },
          { id: "eq9", label: "9" },
          { id: "eqn5", label: "−5" },
        ],
        slots: [
          { id: "left", label: "Left side" },
          { id: "right", label: "Right side (=)" },
        ],
      },
      interaction: "drag_to_place" as const,
      validation: {
        type: "slot_match" as const,
        expected: { left: "sq3", right: "eq4" },
      },
      feedback: {
        correct: "(x + 3)² = 4 — ready to take square roots.",
        incorrect: "Half of 6 is 3, so the square is (x + 3)²; the right side becomes 4.",
        hint: "Which binomial squared equals x² + 6x + 9?",
      },
      masteryTarget: { conceptNodeId: "quadratic-equations", skill: "complete_square_form" },
    },
    {
      id: "quad-9-discriminant-abc",
      title: "Discriminant — read a, b, c",
      type: "drag_drop_match" as const,
      prompt: "For x² − 4x + 4 = 0, place a, b, and c into the slots (standard form ax² + bx + c).",
      visualPrompt: "a is the x² coefficient, b the x coefficient, c the constant.",
      data: {
        items: [
          { id: "a1", label: "a = 1" },
          { id: "bm4", label: "b = −4" },
          { id: "c4", label: "c = 4" },
          { id: "b4", label: "b = 4" },
          { id: "cm4", label: "c = −4" },
        ],
        slots: [
          { id: "slot_a", label: "Coefficient a" },
          { id: "slot_b", label: "Coefficient b" },
          { id: "slot_c", label: "Constant c" },
        ],
      },
      interaction: "drag_to_place" as const,
      validation: {
        type: "slot_match" as const,
        expected: { slot_a: "a1", slot_b: "bm4", slot_c: "c4" },
      },
      feedback: {
        correct: "a = 1, b = −4, c = 4 — watch the sign on the middle term.",
        incorrect: "In x² − 4x + 4, the x term is −4x so b = −4.",
        hint: "Include the sign with b and c.",
      },
      masteryTarget: { conceptNodeId: "quadratic-equations", skill: "discriminant_abc" },
    },
    {
      id: "quad-10-discriminant-value",
      title: "Discriminant b² − 4ac",
      type: "drag_drop_match" as const,
      prompt: "For x² + 6x + 5 = 0 (a = 1, b = 6, c = 5), drag the discriminant and the number of real roots.",
      visualPrompt: "D = 6² − 4(1)(5) = 36 − 20 = 16 > 0 → two real roots.",
      data: {
        items: [
          { id: "d16", label: "D = 16" },
          { id: "d0", label: "D = 0" },
          { id: "dneg", label: "D = −4" },
          { id: "two", label: "Two real roots" },
          { id: "one", label: "One repeated root" },
          { id: "none", label: "No real roots" },
        ],
        slots: [
          { id: "disc", label: "Discriminant" },
          { id: "roots", label: "Real roots" },
        ],
      },
      interaction: "drag_to_place" as const,
      validation: {
        type: "slot_match" as const,
        expected: { disc: "d16", roots: "two" },
      },
      feedback: {
        correct: "D = 16 > 0 — the parabola crosses the x-axis twice.",
        incorrect: "Compute 6² − 4(1)(5) = 36 − 20 = 16.",
        hint: "Positive discriminant → two distinct real roots.",
      },
      masteryTarget: { conceptNodeId: "quadratic-equations", skill: "discriminant_compute" },
    },
    {
      id: "quad-11-discriminant-zero",
      title: "When D = 0",
      type: "drag_drop_match" as const,
      prompt: "For x² − 4x + 4 = 0, drag the discriminant and root type (perfect square trinomial).",
      visualPrompt: "D = (−4)² − 4(1)(4) = 0 — one repeated root at x = 2.",
      data: {
        items: [
          { id: "dz0", label: "D = 0" },
          { id: "dz16", label: "D = 16" },
          { id: "dzneg", label: "D = −8" },
          { id: "repeat", label: "One repeated root" },
          { id: "two_r", label: "Two real roots" },
          { id: "zero_r", label: "No real roots" },
        ],
        slots: [
          { id: "disc_z", label: "Discriminant" },
          { id: "roots_z", label: "Real roots" },
        ],
      },
      interaction: "drag_to_place" as const,
      validation: {
        type: "slot_match" as const,
        expected: { disc_z: "dz0", roots_z: "repeat" },
      },
      feedback: {
        correct: "D = 0 — (x − 2)² = 0 touches the axis once at x = 2.",
        incorrect: "(−4)² − 4(1)(4) = 16 − 16 = 0.",
        hint: "A perfect square trinomial has discriminant zero.",
      },
      masteryTarget: { conceptNodeId: "quadratic-equations", skill: "discriminant_zero" },
    },
    {
      id: "quad-12-discriminant-negative",
      title: "When D < 0",
      type: "segment_select" as const,
      prompt: "x² + 2x + 5 = 0 has D = 2² − 4(1)(5) = −16. What happens to the real roots?",
      visualPrompt: "Negative discriminant — the parabola stays above the x-axis.",
      data: {
        segments: [
          { id: "none", label: "No real roots" },
          { id: "one", label: "One repeated root" },
          { id: "two", label: "Two real roots" },
          { id: "three", label: "Three real roots" },
        ],
      },
      interaction: "select_choice" as const,
      validation: { type: "choice_match" as const, expectedChoice: "none" },
      feedback: {
        correct: "D < 0 — no x-intercepts, so no real solutions (only complex).",
        incorrect: "When the discriminant is negative, √D is not a real number.",
        hint: "Can a parabola with no x-intercepts have real roots?",
      },
      masteryTarget: { conceptNodeId: "quadratic-equations", skill: "discriminant_negative" },
    },
  ],
  finalMasteryCheck: {
    id: "quad-final-cts-disc",
    title: "Mastery check",
    type: "drag_drop_match" as const,
    prompt: "Complete the square on x² + 8x + 12 = 0: match (x + 4)² and the right-hand value.",
    visualPrompt: "Add (8/2)² = 16 → x² + 8x + 16 = 4 → (x + 4)² = 4.",
    data: {
      items: [
        { id: "sq4", label: "(x + 4)²" },
        { id: "sq8", label: "(x + 8)²" },
        { id: "v4", label: "4" },
        { id: "v12", label: "12" },
        { id: "vn4", label: "−4" },
      ],
      slots: [
        { id: "m_left", label: "Completed square" },
        { id: "m_right", label: "Equals" },
      ],
    },
    interaction: "drag_to_place" as const,
    validation: {
      type: "slot_match" as const,
      expected: { m_left: "sq4", m_right: "v4" },
    },
    feedback: {
      correct: "(x + 4)² = 4 → x = −4 ± 2 — completing the square and the discriminant both work.",
      incorrect: "Half of 8 is 4; add 16 to both sides to get (x + 4)² = 4.",
      hint: "(8/2)² = 16; x² + 8x + 16 = 4.",
    },
    masteryTarget: { conceptNodeId: "quadratic-equations", skill: "quadratic_cts_disc_mastery" },
  },
} as const;
