/** Visual Problem Engine — ionic vs covalent bonding (chemistry). */
export const CHEMISTRY_BONDING_LESSON_SEED = {
  id: "lesson-chemical-bonding-basics",
  title: "Ionic vs covalent bonding",
  subject: "Chemistry",
  topic: "Chemical bonding",
  level: "beginner" as const,
  scenes: [
    {
      id: "chem-bond-1-transfer-vs-share",
      title: "Transfer or share?",
      type: "segment_select" as const,
      prompt: "In an ionic bond, what happens to valence electrons between a metal and a nonmetal?",
      visualPrompt: "Think NaCl: metal gives, nonmetal takes.",
      data: {
        segments: [
          { id: "transfer", label: "Electrons transfer from metal to nonmetal" },
          { id: "share", label: "Electrons are shared equally" },
          { id: "none", label: "No electrons involved" },
          { id: "pool", label: "Electrons form a free pool (metallic only)" },
        ],
      },
      interaction: "select_choice" as const,
      validation: { type: "choice_match" as const, expectedChoice: "transfer" },
      feedback: {
        correct: "Transfer — metal cations and nonmetal anions form an ionic lattice.",
        incorrect: "Equal sharing is covalent; ionic is full transfer between metal and nonmetal.",
        hint: "Na loses one electron; Cl gains it — that's transfer.",
      },
      masteryTarget: { conceptNodeId: "chemical-bonding", skill: "ionic_electron_transfer" },
    },
    {
      id: "chem-bond-2-nacl-steps",
      title: "Forming NaCl",
      type: "drag_drop_sort" as const,
      prompt: "Order the steps in forming NaCl from Na and Cl atoms.",
      visualPrompt: "Neutral atoms → ions → attraction.",
      data: {
        items: [
          "Na loses one valence electron → Na⁺",
          "Cl gains that electron → Cl⁻",
          "Oppositely charged ions attract in a crystal lattice",
        ],
      },
      interaction: "reorder" as const,
      validation: {
        type: "ordered_sequence" as const,
        expectedOrder: [
          "Na loses one valence electron → Na⁺",
          "Cl gains that electron → Cl⁻",
          "Oppositely charged ions attract in a crystal lattice",
        ],
      },
      feedback: {
        correct: "Na⁺ and Cl⁻ first, then lattice — the ionic bond story.",
        incorrect: "Ions must form before they can attract into a solid.",
        hint: "Who loses an electron first?",
      },
      masteryTarget: { conceptNodeId: "chemical-bonding", skill: "nacl_formation_order" },
    },
    {
      id: "chem-bond-3-covalent-grid",
      title: "Shared pair model",
      type: "grid_model" as const,
      prompt: "A covalent bond shares one electron pair. In this 2×2 grid, shade exactly 2 cells to model 'one shared pair — two electrons'.",
      visualPrompt: "Two electrons = two shaded cells.",
      data: { rows: 2, columns: 2 },
      interaction: "tap_to_fill" as const,
      validation: { type: "count_match" as const, expectedCount: 2 },
      feedback: {
        correct: "Two cells — one bonding pair in this simplified Lewis-style model.",
        incorrect: "A single covalent bond involves exactly two shared electrons.",
        hint: "Shade two cells, leave two empty.",
      },
      masteryTarget: { conceptNodeId: "chemical-bonding", skill: "shared_pair_model" },
    },
    {
      id: "chem-bond-4-en-difference",
      title: "Electronegativity gap",
      type: "number_line" as const,
      prompt: "ΔEN ≈ 0.4 suggests polar covalent; ΔEN > 1.7 often suggests ionic. Mark 2.0 on this ΔEN scale (0–3, step 0.5).",
      visualPrompt: "Large gap → ionic character.",
      data: { min: 0, max: 3, step: 0.5 },
      interaction: "place_point" as const,
      validation: {
        type: "point_match" as const,
        expectedPoint: { x: 2, y: 0 },
        tolerance: 0.3,
      },
      feedback: {
        correct: "2.0 — a large electronegativity difference, ionic territory for many textbook cutoffs.",
        incorrect: "Place on the fourth tick: 0, 0.5, 1.0, 1.5, 2.0.",
        hint: "Count four steps of 0.5 from zero.",
      },
      masteryTarget: { conceptNodeId: "chemical-bonding", skill: "en_difference_scale" },
    },
    {
      id: "chem-bond-5-h2-share",
      title: "H₂ covalent",
      type: "fraction_bar" as const,
      prompt: "In H₂ each H contributes 1 electron to the bond (2 total). Shade 1 of 2 equal parts to show 'half from each atom'.",
      visualPrompt: "One of two parts = 50% from one H.",
      data: { totalParts: 2 },
      interaction: "tap_to_fill" as const,
      validation: { type: "count_match" as const, expectedCount: 1 },
      feedback: {
        correct: "One of two — each hydrogen supplies half the bonding pair in H₂.",
        incorrect: "Shade exactly one of the two equal slices.",
        hint: "Equal sharing → one part per atom out of two.",
      },
      masteryTarget: { conceptNodeId: "chemical-bonding", skill: "h2_equal_share" },
    },
  ],
  finalMasteryCheck: {
    id: "chem-bond-final-classify",
    title: "Classify the bond",
    type: "segment_select" as const,
    prompt: "Which pair is most likely to form a predominantly ionic bond?",
    visualPrompt: "Large ΔEN + metal/nonmetal combo.",
    data: {
      segments: [
        { id: "nacl", label: "Na and Cl" },
        { id: "h2", label: "H and H" },
        { id: "o2", label: "O and O" },
        { id: "c_c", label: "C and C (in diamond)" },
      ],
    },
    interaction: "select_choice" as const,
    validation: { type: "choice_match" as const, expectedChoice: "nacl" },
    feedback: {
      correct: "Na + Cl — classic metal + halogen ionic pair.",
      incorrect: "H₂, O₂, and C–C are covalent networks or molecules.",
      hint: "Look for metal + nonmetal with a big electronegativity gap.",
    },
    masteryTarget: { conceptNodeId: "chemical-bonding", skill: "bond_type_classify" },
  },
} as const;
