/** Visual Problem Engine — algebra via gear variables (g = driver teeth, d = driven teeth). */
export const MATH_GEAR_ALGEBRA_LESSON_SEED = {
  id: "lesson-gear-algebra",
  title: "Algebra with gears",
  subject: "Math",
  topic: "Linear equations",
  level: "beginner" as const,
  scenes: [
    {
      id: "gear-alg-1-multiply",
      title: "d = 3g",
      type: "gear" as const,
      prompt: "Let g = driver teeth and d = driven teeth. If d = 3g and g = 12, select the driven gear.",
      visualPrompt: "Three times the driver teeth go on the driven gear.",
      data: {
        driverTeeth: 12,
        drivenOptions: [24, 30, 36],
        equation: "d = 3g,  g = 12",
      },
      interaction: "drag_to_place" as const,
      validation: { type: "gear_match" as const, driverTeeth: 12, drivenTeeth: 36 },
      feedback: {
        correct: "d = 3 × 12 = 36 — the driven gear has 36 teeth.",
        incorrect: "Multiply: 3 × 12 = 36 teeth on the driven gear.",
        hint: "Substitute g = 12 into d = 3g.",
      },
      masteryTarget: { conceptNodeId: "linear-equations", skill: "gear_algebra_multiply" },
    },
    {
      id: "gear-alg-2-solve-d",
      title: "Name d",
      type: "multiple_choice" as const,
      prompt: "With g = 12 and d = 3g, what is d?",
      visualPrompt: "Use the gear you just built.",
      data: { choices: ["36", "24", "12", "3"] },
      interaction: "select_choice" as const,
      validation: { type: "choice_match" as const, expectedChoice: "36" },
      feedback: {
        correct: "d = 36 — substitution turns the formula into arithmetic.",
        incorrect: "Compute 3 × 12.",
        hint: "d = 3g = 3(12).",
      },
      masteryTarget: { conceptNodeId: "linear-equations", skill: "gear_algebra_substitute" },
    },
    {
      id: "gear-alg-3-add",
      title: "g + 18 = d",
      type: "gear" as const,
      prompt: "The driven gear has 18 more teeth than the driver. If g = 12, find d.",
      visualPrompt: "Add 18 to the driver tooth count.",
      data: {
        driverTeeth: 12,
        drivenOptions: [24, 30, 36],
        equation: "d = g + 18,  g = 12",
      },
      interaction: "drag_to_place" as const,
      validation: { type: "gear_match" as const, driverTeeth: 12, drivenTeeth: 30 },
      feedback: {
        correct: "12 + 18 = 30 — d = 30 teeth on the driven gear.",
        incorrect: "Add 18 to g: 12 + 18 = 30.",
        hint: "d = g + 18 → substitute g = 12.",
      },
      masteryTarget: { conceptNodeId: "linear-equations", skill: "gear_algebra_add" },
    },
    {
      id: "gear-alg-4-solve-g",
      title: "2g = 24",
      type: "gear" as const,
      prompt: "Twice the driver teeth equals 24 (the driven gear). Solve for g.",
      visualPrompt: "Pick the driver gear so 2g = 24.",
      data: {
        fixedDrivenTeeth: 24,
        driverOptions: [8, 12, 16],
        equation: "2g = d,  d = 24",
      },
      interaction: "drag_to_place" as const,
      validation: { type: "gear_match" as const, driverTeeth: 12, drivenTeeth: 24 },
      feedback: {
        correct: "2g = 24 → g = 12 — select the 12-tooth driver.",
        incorrect: "Divide both sides by 2: g = 24 ÷ 2 = 12.",
        hint: "Which driver option satisfies 2g = 24?",
      },
      masteryTarget: { conceptNodeId: "linear-equations", skill: "gear_algebra_solve_g" },
    },
    {
      id: "gear-alg-5-proportion",
      title: "Proportional gears",
      type: "gear" as const,
      prompt: "Gears A and B mesh: 12/36 = g/48. Find g (driver teeth for the second pair).",
      visualPrompt: "Same ratio — cross-multiply or scale the fraction.",
      data: {
        fixedDrivenTeeth: 48,
        driverOptions: [12, 16, 18],
        equation: "12/36 = g/48",
      },
      interaction: "drag_to_place" as const,
      validation: { type: "gear_match" as const, driverTeeth: 16, drivenTeeth: 48 },
      feedback: {
        correct: "12/36 = 1/3, so g/48 = 1/3 → g = 16.",
        incorrect: "Cross-multiply: 12 × 48 = 36g → 576 = 36g → g = 16.",
        hint: "Simplify 12/36 to 1/3, then solve g/48 = 1/3.",
      },
      masteryTarget: { conceptNodeId: "linear-equations", skill: "gear_algebra_proportion" },
    },
    {
      id: "gear-alg-6-mc-equation",
      title: "Read the equation",
      type: "multiple_choice" as const,
      prompt: "A 12-tooth driver meshes with a 30-tooth driven gear. Which equation matches d = g + 18?",
      visualPrompt: "Match tooth counts to the formula.",
      data: { choices: ["g = 12, d = 30", "g = 30, d = 12", "g = 18, d = 12", "g = 12, d = 18"] },
      interaction: "select_choice" as const,
      validation: { type: "choice_match" as const, expectedChoice: "g = 12, d = 30" },
      feedback: {
        correct: "12 + 18 = 30 — driver g, driven d, and d = g + 18 all align.",
        incorrect: "Check: does g + 18 equal d for each option?",
        hint: "Plug g = 12 into d = g + 18.",
      },
      masteryTarget: { conceptNodeId: "linear-equations", skill: "gear_algebra_read_equation" },
    },
  ],
  finalMasteryCheck: {
    id: "gear-alg-final",
    title: "Mastery check",
    type: "gear" as const,
    prompt: "Solve d = 4g when g = 9. Select the correct driven gear.",
    visualPrompt: "Substitute and multiply.",
    data: {
      driverTeeth: 9,
      drivenOptions: [27, 32, 36],
      equation: "d = 4g,  g = 9",
    },
    interaction: "drag_to_place" as const,
    validation: { type: "gear_match" as const, driverTeeth: 9, drivenTeeth: 36 },
    feedback: {
      correct: "d = 4 × 9 = 36 — gear ratios are just algebra with teeth.",
      incorrect: "Multiply: 4 × 9 = 36 teeth on the driven gear.",
      hint: "d = 4g → d = 4(9).",
    },
    masteryTarget: { conceptNodeId: "linear-equations", skill: "gear_algebra_mastery" },
  },
} as const;
