/** Visual Problem Engine — Pythagorean theorem with coordinate geometry (math). */
export const MATH_PYTHAGOREAN_LESSON_SEED = {
  id: "lesson-pythagorean-theorem",
  title: "Pythagorean theorem visual",
  subject: "Math",
  topic: "Right triangles",
  level: "beginner" as const,
  scenes: [
    {
      id: "math-pyth-1-right-angle",
      title: "Which side is hypotenuse?",
      type: "segment_select" as const,
      prompt: "In a right triangle, which side is always the longest?",
      visualPrompt: "Opposite the 90° corner.",
      data: {
        segments: [
          { id: "hyp", label: "Hypotenuse (opposite the right angle)" },
          { id: "leg", label: "Either leg" },
          { id: "alt", label: "The altitude to the hypotenuse" },
          { id: "shortest", label: "The shortest side always" },
        ],
      },
      interaction: "select_choice" as const,
      validation: { type: "choice_match" as const, expectedChoice: "hyp" },
      feedback: {
        correct: "The hypotenuse faces the right angle and is always the longest side.",
        incorrect: "Legs meet at the right angle; the hypotenuse is across from it.",
        hint: "The name starts with 'hypo-' and means 'under' the right angle.",
      },
      masteryTarget: { conceptNodeId: "linear-equations", skill: "hypotenuse_identify" },
    },
    {
      id: "math-pyth-2-legs-plot",
      title: "Legs on a grid",
      type: "graph_plot" as const,
      prompt: "A right triangle has legs along the axes from (0,0) to (3,0) and (0,4). Place the right-angle vertex at (0, 0).",
      visualPrompt: "Origin corner where perpendicular legs meet.",
      data: {
        xMin: -1,
        xMax: 6,
        yMin: -1,
        yMax: 6,
        lines: [],
      },
      interaction: "place_point" as const,
      validation: {
        type: "point_match" as const,
        expectedPoint: { x: 0, y: 0 },
        tolerance: 0.45,
      },
      feedback: {
        correct: "(0, 0) — the right angle sits where the horizontal and vertical legs meet.",
        incorrect: "Move to the origin-style corner where both legs start.",
        hint: "Both legs start from the same point at zero on both axes.",
      },
      masteryTarget: { conceptNodeId: "linear-equations", skill: "right_angle_vertex" },
    },
    {
      id: "math-pyth-3-3-4-5",
      title: "Classic 3-4-5",
      type: "graph_plot" as const,
      prompt: "Place the far end of the hypotenuse for a 3-4-5 triangle: from (0,0) along legs to (3, 4).",
      visualPrompt: "Three right, four up from the origin.",
      data: {
        xMin: -1,
        xMax: 6,
        yMin: -1,
        yMax: 6,
        lines: [{ x1: 0, y1: 0, x2: 3, y2: 0 }, { x1: 0, y1: 0, x2: 0, y2: 4 }],
      },
      interaction: "place_point" as const,
      validation: {
        type: "point_match" as const,
        expectedPoint: { x: 3, y: 4 },
        tolerance: 0.45,
      },
      feedback: {
        correct: "(3, 4) — legs 3 and 4 give hypotenuse 5 by a² + b² = c².",
        incorrect: "Go 3 units right and 4 units up from the right-angle corner.",
        hint: "x = 3, y = 4.",
      },
      masteryTarget: { conceptNodeId: "linear-equations", skill: "plot_345_triangle" },
    },
    {
      id: "math-pyth-4-formula-order",
      title: "Build the formula",
      type: "drag_drop_sort" as const,
      prompt: "Order the steps to find hypotenuse c when legs are a = 6 and b = 8.",
      visualPrompt: "Square → add → square root.",
      data: {
        items: [
          "Compute a² + b² = 36 + 64 = 100",
          "Take √100 = 10",
          "Write c² = a² + b²",
        ],
      },
      interaction: "reorder" as const,
      validation: {
        type: "ordered_sequence" as const,
        expectedOrder: [
          "Write c² = a² + b²",
          "Compute a² + b² = 36 + 64 = 100",
          "Take √100 = 10",
        ],
      },
      feedback: {
        correct: "Formula → substitute → sqrt — c = 10 for the 6-8-10 triangle.",
        incorrect: "State the theorem before you plug in numbers.",
        hint: "Start with c² = a² + b².",
      },
      masteryTarget: { conceptNodeId: "linear-equations", skill: "pythagorean_steps" },
    },
    {
      id: "math-pyth-5-area-grid",
      title: "Squares on sides",
      type: "grid_model" as const,
      prompt: "A visual proof uses squares on each side. A 3×3 square has 9 cells. Shade exactly 9 cells in this 3×3 grid to model the square on a leg of length 3.",
      visualPrompt: "Fill the whole 3×3 grid.",
      data: { rows: 3, columns: 3 },
      interaction: "tap_to_fill" as const,
      validation: { type: "count_match" as const, expectedCount: 9 },
      feedback: {
        correct: "All 9 cells — area 3² = 9 for the square on a leg of length 3.",
        incorrect: "A 3×3 grid has nine cells; shade all of them.",
        hint: "Tap every cell in the grid.",
      },
      masteryTarget: { conceptNodeId: "linear-equations", skill: "square_on_leg_area" },
    },
  ],
  finalMasteryCheck: {
    id: "math-pyth-final-calc",
    title: "Find the missing side",
    type: "number_line" as const,
    prompt: "Legs 5 and 12 give hypotenuse 13. Mark 13 on this scale (0–20, step 1).",
    visualPrompt: "5² + 12² = 13² — another Pythagorean triple.",
    data: { min: 0, max: 20, step: 1 },
    interaction: "place_point" as const,
    validation: {
      type: "point_match" as const,
      expectedPoint: { x: 13, y: 0 },
      tolerance: 0.35,
    },
    feedback: {
      correct: "13 — the hypotenuse of the 5-12-13 right triangle.",
      incorrect: "Count thirteen unit ticks from zero.",
      hint: "25 + 144 = 169 = 13².",
    },
    masteryTarget: { conceptNodeId: "linear-equations", skill: "hypotenuse_51213" },
  },
} as const;
