/** Visual Problem Engine — forces, Newton's laws, and free-body intuition (physics). */
export const PHYSICS_FORCES_LESSON_SEED = {
  id: "lesson-forces-free-body",
  title: "Forces & free-body basics",
  subject: "Physics",
  topic: "Forces",
  level: "beginner" as const,
  scenes: [
    {
      id: "phy-forces-1-inertia",
      title: "Inertia first",
      type: "segment_select" as const,
      prompt: "A book rests on a table. You push gently but it does not move. Which force best balances your push?",
      visualPrompt: "Think about what keeps the book from sliding.",
      data: {
        segments: [
          { id: "gravity", label: "Gravity only" },
          { id: "friction", label: "Static friction from the table" },
          { id: "air", label: "Air resistance" },
          { id: "none", label: "No opposing force" },
        ],
      },
      interaction: "select_choice" as const,
      validation: { type: "choice_match" as const, expectedChoice: "friction" },
      feedback: {
        correct: "Static friction matches your push — the net force stays zero, so the book stays put (Newton's first law).",
        incorrect: "Gravity pulls down; the normal force balances that. Sideways, static friction opposes your push.",
        hint: "What surface force resists sliding when nothing moves yet?",
      },
      masteryTarget: { conceptNodeId: "forces-newton", skill: "static_equilibrium" },
    },
    {
      id: "phy-forces-2-action-reaction",
      title: "Action–reaction pairs",
      type: "drag_drop_sort" as const,
      prompt: "Order these statements from general idea to specific example.",
      visualPrompt: "Start with the law, then the pair, then the everyday case.",
      data: {
        items: [
          "You push the wall; the wall pushes back on you with equal magnitude",
          "For every action there is an equal and opposite reaction",
          "Rocket exhaust pushes down; rocket accelerates upward",
        ],
      },
      interaction: "reorder" as const,
      validation: {
        type: "ordered_sequence" as const,
        expectedOrder: [
          "For every action there is an equal and opposite reaction",
          "You push the wall; the wall pushes back on you with equal magnitude",
          "Rocket exhaust pushes down; rocket accelerates upward",
        ],
      },
      feedback: {
        correct: "Law → contact pair → rocket example — each step applies the same third-law idea.",
        incorrect: "The general principle comes before specific contact forces and rockets.",
        hint: "Newton's third law is the broadest statement here.",
      },
      masteryTarget: { conceptNodeId: "forces-newton", skill: "action_reaction_order" },
    },
    {
      id: "phy-forces-3-f-ma-graph",
      title: "F = ma on a graph",
      type: "graph_plot" as const,
      prompt: "For constant mass, force and acceleration are proportional. Place a point at (2 N, 4 m/s²) if the slope is 2 m/s² per newton.",
      visualPrompt: "x = force (0–6 N), y = acceleration (0–8 m/s²).",
      data: {
        xMin: 0,
        xMax: 6,
        yMin: 0,
        yMax: 8,
        lines: [],
      },
      interaction: "place_point" as const,
      validation: {
        type: "point_match" as const,
        expectedPoint: { x: 2, y: 4 },
        tolerance: 0.55,
      },
      feedback: {
        correct: "(2, 4) sits on the line a = 2F — double the force, double the acceleration.",
        incorrect: "Count two steps right on force, four steps up on acceleration for this slope.",
        hint: "From the origin style corner: 2 across, 4 up.",
      },
      masteryTarget: { conceptNodeId: "forces-newton", skill: "f_ma_proportionality" },
    },
    {
      id: "phy-forces-4-vector-grid",
      title: "Net force model",
      type: "grid_model" as const,
      prompt: "A 2×4 grid models force arrows on an object. Shade exactly 3 cells to show 'three forces acting' before you combine them.",
      visualPrompt: "Tap exactly three cells — any three.",
      data: { rows: 2, columns: 4 },
      interaction: "tap_to_fill" as const,
      validation: { type: "count_match" as const, expectedCount: 3 },
      feedback: {
        correct: "Three separate forces — next you'd draw a free-body diagram and add them vectorially.",
        incorrect: "The prompt asks for exactly three shaded cells.",
        hint: "Count your taps; undo extras if you overshoot.",
      },
      masteryTarget: { conceptNodeId: "forces-newton", skill: "free_body_count" },
    },
    {
      id: "phy-forces-5-mass-number-line",
      title: "Mass vs weight",
      type: "number_line" as const,
      prompt: "On Earth, a 5 kg object weighs about 50 N. Mark 50 on this force scale (0–100 N, steps of 10).",
      visualPrompt: "Weight = mg with g ≈ 10 m/s².",
      data: { min: 0, max: 100, step: 10 },
      interaction: "place_point" as const,
      validation: {
        type: "point_match" as const,
        expectedPoint: { x: 50, y: 0 },
        tolerance: 6,
      },
      feedback: {
        correct: "50 N — five kilograms times roughly ten newtons per kilogram on Earth's surface.",
        incorrect: "Slide to the fifth major tick: 5 × 10 = 50 newtons.",
        hint: "Five steps of ten from zero.",
      },
      masteryTarget: { conceptNodeId: "forces-newton", skill: "weight_from_mass" },
    },
  ],
  finalMasteryCheck: {
    id: "phy-forces-final-friction",
    title: "Friction direction",
    type: "segment_select" as const,
    prompt: "A box slides right across a rough floor. Which direction does kinetic friction act on the box?",
    visualPrompt: "Friction opposes relative motion between surfaces.",
    data: {
      segments: [
        { id: "left", label: "Left (opposite motion)" },
        { id: "right", label: "Right (same as motion)" },
        { id: "up", label: "Upward" },
        { id: "down", label: "Downward only" },
      ],
    },
    interaction: "select_choice" as const,
    validation: { type: "choice_match" as const, expectedChoice: "left" },
    feedback: {
      correct: "Kinetic friction points left — it opposes the box sliding right.",
      incorrect: "Friction always opposes the direction of sliding, not the direction of gravity alone.",
      hint: "Ask: which way is the box moving relative to the floor?",
    },
    masteryTarget: { conceptNodeId: "forces-newton", skill: "kinetic_friction_direction" },
  },
} as const;
