/** Visual Problem Engine — decimals & benchmarks (0–1 and beyond). */
export const DECIMALS_VISUAL_LESSON_SEED = {
  id: "lesson-decimals-on-the-line",
  title: "Decimals on the Number Line",
  subject: "Math",
  topic: "Decimals",
  level: "beginner" as const,
  scenes: [
    {
      id: "dec-1-place-tenths",
      title: "Seven tenths",
      type: "number_line" as const,
      prompt: "Place 0.7 on the number line.",
      visualPrompt: "Drag the marker to 0.7 between 0 and 1.",
      data: { min: 0, max: 1, step: 0.1 },
      interaction: "place_point" as const,
      validation: {
        type: "point_match" as const,
        expectedPoint: { x: 0.7, y: 0 },
        tolerance: 0.09,
      },
      feedback: {
        correct: "0.7 is seven tenths of the way from 0 to 1 — your marker matches that distance.",
        incorrect: "Count by tenths from zero; 0.7 is one tick before 0.8.",
        hint: "Seven steps of size 0.1 lands just before 0.8.",
      },
      masteryTarget: { conceptNodeId: "linear-equations", skill: "decimal_number_line" },
    },
    {
      id: "dec-2-bar-tenths",
      title: "Show seven tenths",
      type: "fraction_bar" as const,
      prompt: "Shade the bar to show the same value as 0.7 (ten equal parts).",
      visualPrompt: "Tap parts until seven of ten are shaded.",
      data: { totalParts: 10 },
      interaction: "tap_to_fill" as const,
      validation: { type: "count_match" as const, expectedCount: 7 },
      feedback: {
        correct: "Seven shaded out of ten matches 0.7 and the fraction 7/10.",
        incorrect: "You need exactly seven equal parts shaded — same story as 0.7 on the line.",
        hint: "Tap seven slices; none of the others should stay highlighted.",
      },
      masteryTarget: { conceptNodeId: "linear-equations", skill: "decimal_to_fraction_model" },
    },
    {
      id: "dec-3-symbol",
      title: "Same value, fraction form",
      type: "multiple_choice" as const,
      prompt: "0.7 is the same as which fraction?",
      visualPrompt: "Pick the fraction that matches seven tenths.",
      data: { choices: ["7/10", "10/7", "7/100", "0.07"] },
      interaction: "select_choice" as const,
      validation: { type: "choice_match" as const, expectedChoice: "7/10" },
      feedback: {
        correct: "7/10 and 0.7 are two names for the same amount.",
        incorrect: "Tenths means denominator 10; the numerator counts how many tenths you have.",
        hint: "Seven tenths → 7 on top, 10 on the bottom.",
      },
      masteryTarget: { conceptNodeId: "linear-equations", skill: "decimal_fraction_equivalence" },
    },
    {
      id: "dec-4-between-integers",
      title: "Between 1 and 2",
      type: "number_line" as const,
      prompt: "Place 1.25 on this number line.",
      visualPrompt: "The line runs from 0 to 2 in steps of 0.25.",
      data: { min: 0, max: 2, step: 0.25 },
      interaction: "place_point" as const,
      validation: {
        type: "point_match" as const,
        expectedPoint: { x: 1.25, y: 0 },
        tolerance: 0.12,
      },
      feedback: {
        correct: "1.25 sits one quarter after 1 — halfway from 1.0 to 1.5.",
        incorrect: "Move one quarter to the right of 1.0; that tick is 1.25.",
        hint: "Count four quarter steps from 0 — that is 1.0; one more quarter is 1.25.",
      },
      masteryTarget: { conceptNodeId: "linear-equations", skill: "decimals_beyond_one" },
    },
    {
      id: "dec-5-grid-percent",
      title: "Thirty percent",
      type: "grid_model" as const,
      prompt: "Shade 30% of this 2×5 grid (10 cells).",
      visualPrompt: "30% of ten cells means three cells.",
      data: { rows: 2, columns: 5 },
      interaction: "tap_to_fill" as const,
      validation: { type: "count_match" as const, expectedCount: 3 },
      feedback: {
        correct: "Three out of ten is 30% — same ratio as 0.3.",
        incorrect: "Ten cells total; 30% asks for three shaded cells.",
        hint: "Try any three cells — count to be sure you have exactly three.",
      },
      masteryTarget: { conceptNodeId: "linear-equations", skill: "percent_decimal_link" },
    },
  ],
  finalMasteryCheck: {
    id: "dec-final-benchmark",
    title: "Benchmark",
    type: "number_line" as const,
    prompt: "Place 0.35 between 0 and 1.",
    visualPrompt: "Use the tick marks every 0.05.",
    data: { min: 0, max: 1, step: 0.05 },
    interaction: "place_point" as const,
    validation: {
      type: "point_match" as const,
      expectedPoint: { x: 0.35, y: 0 },
      tolerance: 0.06,
    },
    feedback: {
      correct: "0.35 is seven steps of 0.05 from zero — nice benchmark placement.",
      incorrect: "Each small step is 0.05; count seven of them from 0 to land on 0.35.",
      hint: "0.3 is six ticks; one more tick is 0.35.",
    },
    masteryTarget: { conceptNodeId: "linear-equations", skill: "decimal_benchmarks" },
  },
} as const;
