/** Visual Problem Engine — photosynthesis flow from capture to sugar (biology). */
export const BIOLOGY_PHOTOSYNTHESIS_LESSON_SEED = {
  id: "lesson-photosynthesis-story",
  title: "Photosynthesis: from light to sugar",
  subject: "Biology",
  topic: "Photosynthesis",
  level: "beginner" as const,
  scenes: [
    {
      id: "bio-photo-1-light-path",
      title: "Order the big picture",
      type: "drag_drop_sort" as const,
      prompt: "Order these stages so energy and matter flow like a leaf in full sun.",
      visualPrompt: "Earliest part of the story at the top of your final list.",
      data: {
        items: [
          "Sugars are built and stored for the plant to use",
          "CO₂ is fixed into carbon skeletons in the Calvin cycle",
          "ATP and NADPH carry energy from the thylakoids",
          "Light is captured by pigments in the chloroplast",
          "Water is split; oxygen is released as a by-product",
        ],
      },
      interaction: "reorder" as const,
      validation: {
        type: "ordered_sequence" as const,
        expectedOrder: [
          "Light is captured by pigments in the chloroplast",
          "Water is split; oxygen is released as a by-product",
          "ATP and NADPH carry energy from the thylakoids",
          "CO₂ is fixed into carbon skeletons in the Calvin cycle",
          "Sugars are built and stored for the plant to use",
        ],
      },
      feedback: {
        correct: "Light capture → water splitting and O₂ → energy carriers → carbon fixation → sugars — that is the textbook pipeline.",
        incorrect: "CO₂ cannot be fixed before the light reactions supply ATP and NADPH.",
        hint: "Start with pigments and sunlight; sugars come last.",
      },
      masteryTarget: { conceptNodeId: "photosynthesis", skill: "photo_overall_sequence" },
    },
    {
      id: "bio-photo-2-calvin-round",
      title: "Calvin cycle beats",
      type: "segment_select" as const,
      prompt: "Which move runs first inside the Calvin cycle?",
      visualPrompt: "Attach carbon before you reduce intermediates or regenerate RuBP.",
      data: {
        segments: [
          { id: "fix", label: "Fix CO₂ onto RuBP (carbon fixation)" },
          { id: "reduce", label: "Reduce 3-carbon molecules (ATP + NADPH)" },
          { id: "regen", label: "Regenerate RuBP using ATP" },
        ],
      },
      interaction: "select_choice" as const,
      validation: { type: "choice_match" as const, expectedChoice: "fix" },
      feedback: {
        correct: "Fix → reduce → regenerate is how the cycle keeps spinning — fixation opens the loop.",
        incorrect: "RuBP must accept CO₂ before reductions spend ATP and NADPH.",
        hint: "Carbon fixation is always the opening move of the cycle.",
      },
      masteryTarget: { conceptNodeId: "photosynthesis", skill: "calvin_cycle_order" },
    },
    {
      id: "bio-photo-3-grid-chloroplast",
      title: "Where is the action?",
      type: "grid_model" as const,
      prompt: "Shade 4 cells in this 4×4 grid to show “chloroplast-rich tissue” in a toy leaf cross-section (about one quarter).",
      visualPrompt: "Exactly four cells — any pattern is fine for this model.",
      data: { rows: 4, columns: 4 },
      interaction: "tap_to_fill" as const,
      validation: { type: "count_match" as const, expectedCount: 4 },
      feedback: {
        correct: "Four of sixteen squares is one quarter — a simple visual for “lots of chloroplasts here.”",
        incorrect: "Count shaded squares; the prompt asks for exactly four.",
        hint: "A 2×2 block in one corner is four cells.",
      },
      masteryTarget: { conceptNodeId: "photosynthesis", skill: "chloroplast_density_model" },
    },
    {
      id: "bio-photo-4-mc-stroma",
      title: "Where in the chloroplast?",
      type: "multiple_choice" as const,
      prompt: "The Calvin cycle runs in which compartment?",
      visualPrompt: "Pick the fluid space around the thylakoids.",
      data: { choices: ["Stroma", "Thylakoid lumen", "Outer membrane only", "Nucleolus"] },
      interaction: "select_choice" as const,
      validation: { type: "choice_match" as const, expectedChoice: "Stroma" },
      feedback: {
        correct: "The stroma is the aqueous compartment where RuBP is regenerated and sugars are assembled.",
        incorrect: "Thylakoids host the light reactions; carbon fixation is in the surrounding fluid.",
        hint: "Think “stroma surrounds the stacks of thylakoids (grana).”",
      },
      masteryTarget: { conceptNodeId: "photosynthesis", skill: "calvin_location" },
    },
    {
      id: "bio-photo-5-energy-numberline",
      title: "Relative energy",
      type: "number_line" as const,
      prompt: "On a 0–1 scale, mark where “excited electrons leaving Photosystem II” sit compared with ground state (0).",
      visualPrompt: "Use a high value — excitation is a big jump from baseline.",
      data: { min: 0, max: 1, step: 0.1 },
      interaction: "place_point" as const,
      validation: {
        type: "point_match" as const,
        expectedPoint: { x: 0.85, y: 0 },
        tolerance: 0.12,
      },
      feedback: {
        correct: "High on the scale matches “strongly energized” relative to ground state.",
        incorrect: "Slide toward the right — excitation is not near zero on this toy axis.",
        hint: "Try around 0.8–0.9 if you are unsure.",
      },
      masteryTarget: { conceptNodeId: "photosynthesis", skill: "excitation_energy_scale" },
    },
  ],
  finalMasteryCheck: {
    id: "bio-photo-final-graph",
    title: "Light vs rate",
    type: "graph_plot" as const,
    prompt: "A saturating light curve: at very high light, rate levels off. Place a point in the “plateau” region (high light, high but not maximal growth on this toy y-axis).",
    visualPrompt: "x and y both 0–6. Aim for the flat top of the curve mentally — around (5, 4).",
    data: {
      xMin: 0,
      xMax: 6,
      yMin: 0,
      yMax: 6,
      lines: [
        { x1: 0, y1: 1, x2: 3, y2: 4 },
        { x1: 3, y1: 4, x2: 6, y2: 4.2 },
      ],
    },
    interaction: "place_point" as const,
    validation: {
      type: "point_match" as const,
      expectedPoint: { x: 5, y: 4 },
      tolerance: 0.65,
    },
    feedback: {
      correct: "High light on the x-axis with a y-value up on the plateau matches “saturated” photosynthesis.",
      incorrect: "Slide right until you are on the nearly horizontal segment, with y near the top of the plot.",
      hint: "Follow the dashed guide to where it flattens, then tap there.",
    },
    masteryTarget: { conceptNodeId: "photosynthesis", skill: "light_saturation_concept" },
  },
} as const;
