/** Visual Problem Engine — equivalent fractions on a balance scale (math). */
export const MATH_BALANCE_FRACTIONS_LESSON_SEED = {
  id: "lesson-balance-fraction-equivalence",
  title: "Equivalent fractions on a balance",
  subject: "Math",
  topic: "Fractions",
  level: "beginner" as const,
  scenes: [
    {
      id: "bal-frac-1-half",
      title: "1/2 with unit weights",
      type: "balance_scale" as const,
      prompt: "Each unit weight is 1/4 of a whole. Show 1/2 using two units on the left.",
      visualPrompt: "Two quarter-units = one half.",
      data: { weights: [1, 1, 1, 1, 2], unit: "u" },
      interaction: "drag_to_place" as const,
      validation: { type: "balance_match" as const, left: [1, 1], right: [2] },
      feedback: {
        correct: "Two 1/4-units (2u) balance one 1/2-unit — 2/4 = 1/2.",
        incorrect: "1/2 of a whole is 2 quarter-units. Match 2 on the left to 2u on the right.",
        hint: "Place two 1-weights on the left and one 2-weight on the right.",
      },
      masteryTarget: { conceptNodeId: "variables", skill: "fraction_balance_half" },
    },
    {
      id: "bal-frac-2-equivalent",
      title: "Name the equivalence",
      type: "multiple_choice" as const,
      prompt: "When 2 quarter-units balance 1 half-unit, which statement is true?",
      visualPrompt: "Same mass on both pans means equal value.",
      data: { choices: ["1/2 = 2/4", "1/2 = 4/2", "2/4 = 8", "1/4 = 1/2"] },
      interaction: "select_choice" as const,
      validation: { type: "choice_match" as const, expectedChoice: "1/2 = 2/4" },
      feedback: {
        correct: "1/2 and 2/4 are equivalent — same amount, different unit counts.",
        incorrect: "Equal pans mean equal fractions: two fourths equals one half.",
        hint: "You used 2 units of size 1/4 on the left.",
      },
      masteryTarget: { conceptNodeId: "variables", skill: "equivalent_fraction_symbol" },
    },
    {
      id: "bal-frac-3-three-sixths",
      title: "3/6 = 1/2",
      type: "balance_scale" as const,
      prompt: "Show 3/6 on the left with three unit weights and balance 1/2 (3 units) on the right.",
      visualPrompt: "Three sixths is the same mass as three quarter-units when units are equal size.",
      data: { weights: [1, 1, 1, 1, 1, 1, 2, 3] },
      interaction: "drag_to_place" as const,
      validation: { type: "balance_match" as const, left: [1, 1, 1], right: [3] },
      feedback: {
        correct: "3 units = 3 units — 3/6 and 1/2 represent the same balance.",
        incorrect: "Three 1-weights on the left; one 3-weight on the right.",
        hint: "Both sides should sum to 3 in unit weights.",
      },
      masteryTarget: { conceptNodeId: "variables", skill: "three_sixths_half" },
    },
    {
      id: "bal-frac-4-four-eighths",
      title: "4/8 = 1/2",
      type: "balance_scale" as const,
      prompt: "Balance four unit weights on the left with a single 4 on the right.",
      visualPrompt: "4/8 and 1/2 — same total, different descriptions.",
      data: { weights: [1, 1, 1, 1, 2, 3, 4] },
      interaction: "drag_to_place" as const,
      validation: { type: "balance_match" as const, left: [1, 1, 1, 1], right: [4] },
      feedback: {
        correct: "4/8 = 1/2 — four eighths balances one half when units match.",
        incorrect: "Four 1-weights on the left; one 4-weight on the right.",
        hint: "1 + 1 + 1 + 1 on the left; 4 on the right.",
      },
      masteryTarget: { conceptNodeId: "variables", skill: "four_eighths_half" },
    },
  ],
  finalMasteryCheck: {
    id: "bal-frac-final",
    title: "Mastery check",
    type: "balance_scale" as const,
    prompt: "Show that 2/4 = 1/2 again: two units on the left, balance on the right.",
    visualPrompt: "Prove equivalence with the scale one more time.",
    data: { weights: [1, 1, 1, 1, 2] },
    interaction: "drag_to_place" as const,
    validation: { type: "balance_match" as const, left: [1, 1], right: [2] },
    feedback: {
      correct: "Level scale — 2/4 and 1/2 are equivalent fractions.",
      incorrect: "Match two 1-weights to one 2-weight.",
      hint: "Same setup as your first scene: [1,1] vs [2].",
    },
    masteryTarget: { conceptNodeId: "variables", skill: "fraction_balance_mastery" },
  },
} as const;
