/**
 * Canonical JSON for the Visual Problem Engine seed lesson (Fractions).
 * Typed loosely here so `@mindorbit/content` stays free of web-only imports.
 */
export const FRACTIONS_VISUAL_LESSON_SEED = {
  id: "lesson-fractions-parts-of-whole",
  title: "Fractions as Parts of a Whole",
  subject: "Math",
  topic: "Fractions",
  level: "beginner" as const,
  scenes: [
    {
      id: "scene-1-pizza",
      title: "Shade parts",
      type: "fraction_bar" as const,
      prompt: "Shade 3 out of 8 pizza slices.",
      visualPrompt: "Tap slices to shade them.",
      data: { totalParts: 8 },
      interaction: "tap_to_fill" as const,
      validation: { type: "count_match" as const, expectedCount: 3 },
      feedback: {
        correct: "That’s 3/8 of the whole — three equal parts out of eight.",
        incorrect: "Aim for exactly three shaded slices so the picture matches 3/8.",
        hint: "Tap three slices once each; they should stay highlighted.",
      },
      masteryTarget: { conceptNodeId: "variables", skill: "shade_unit_fractions" },
    },
    {
      id: "scene-2-symbol",
      title: "Name the fraction",
      type: "multiple_choice" as const,
      prompt: "What fraction did you shade?",
      visualPrompt: "Pick the fraction that matches a 3-out-of-8 model.",
      data: { choices: ["3/8", "8/3", "5/8", "3/5"] },
      interaction: "select_choice" as const,
      validation: { type: "choice_match" as const, expectedChoice: "3/8" },
      feedback: {
        correct: "3/8 means three parts shaded out of eight equal parts.",
        incorrect: "Compare numerator (shaded) to denominator (total equal parts).",
        hint: "Smaller top number than bottom usually means less than one whole.",
      },
      masteryTarget: { conceptNodeId: "variables", skill: "symbolic_fraction" },
    },
    {
      id: "scene-3-half-bar",
      title: "Half of the bar",
      type: "fraction_bar" as const,
      prompt: "Now shade 1/2 of the bar.",
      visualPrompt: "Half means the same amount on both sides.",
      data: { totalParts: 8 },
      interaction: "tap_to_fill" as const,
      validation: { type: "count_match" as const, expectedCount: 4 },
      feedback: {
        correct: "Four of eight parts is exactly one half.",
        incorrect: "For 1/2 on eight parts, shade four — split the bar into two equal groups.",
        hint: "8 ÷ 2 = 4 slices for one half.",
      },
      masteryTarget: { conceptNodeId: "variables", skill: "half_as_ratio" },
    },
    {
      id: "scene-4-number-line",
      title: "Place one half",
      type: "number_line" as const,
      prompt: "Place 1/2 on the number line.",
      visualPrompt: "Drag the marker to where 1/2 lives between 0 and 1.",
      data: { min: 0, max: 1, step: 0.125 },
      interaction: "place_point" as const,
      validation: {
        type: "point_match" as const,
        expectedPoint: { x: 0.5, y: 0 },
        tolerance: 0.07,
      },
      feedback: {
        correct: "1/2 sits halfway between 0 and 1.",
        incorrect: "The midpoint of the segment from 0 to 1 is 1/2 — your marker should land there.",
        hint: "Count ticks: 4/8 from zero is the same position as 1/2.",
      },
      masteryTarget: { conceptNodeId: "variables", skill: "number_line_fractions" },
    },
    {
      id: "scene-5-grid-percent",
      title: "Percent on a grid",
      type: "grid_model" as const,
      prompt: "Shade 25% of this 4×4 grid.",
      visualPrompt: "25% is one quarter of the squares.",
      data: { rows: 4, columns: 4 },
      interaction: "tap_to_fill" as const,
      validation: { type: "count_match" as const, expectedCount: 4 },
      feedback: {
        correct: "Four cells out of sixteen is 25%.",
        incorrect: "25% of 16 squares is 4 — shade a quarter of the grid.",
        hint: "Try a small block like a 2×2 corner — that’s four cells.",
      },
      masteryTarget: { conceptNodeId: "variables", skill: "percent_area_model" },
    },
  ],
  finalMasteryCheck: {
    id: "scene-final-chocolate",
    title: "Mastery check",
    type: "fraction_bar" as const,
    prompt: "A chocolate bar has 10 pieces. Shade 4/10.",
    visualPrompt: "Shade four of the ten equal pieces.",
    data: { totalParts: 10 },
    interaction: "tap_to_fill" as const,
    validation: { type: "count_match" as const, expectedCount: 4 },
    feedback: {
      correct: "4/10 matches the story — four shaded pieces out of ten.",
      incorrect: "Recount the shaded pieces; you need exactly four of the ten.",
      hint: "Tap four different pieces until four are shaded.",
    },
    masteryTarget: { conceptNodeId: "variables", skill: "contextual_fraction" },
  },
} as const;
