/** Visual Problem Engine — calorimetry & sign of ΔH (chemistry). */
export const CHEMISTRY_THERMO_LESSON_SEED = {
  id: "lesson-calorimetry-and-delta-h",
  title: "Calorimetry & energy sign",
  subject: "Chemistry",
  topic: "Thermochemistry",
  level: "beginner" as const,
  scenes: [
    {
      id: "chem-th-1-coffee-cup-order",
      title: "Coffee-cup calorimetry",
      type: "segment_select" as const,
      prompt: "What should you do first in a simple coffee-cup calorimetry run?",
      visualPrompt: "You need a trustworthy baseline before anything reacts.",
      data: {
        segments: [
          { id: "record_init", label: "Record stable initial temperature" },
          { id: "add_sample", label: "Add sample and stir (before ΔT is meaningful)" },
          { id: "calc_q", label: "Calculate q = mcΔT immediately" },
          { id: "cap_first", label: "Cap the cup before measuring anything" },
        ],
      },
      interaction: "select_choice" as const,
      validation: { type: "choice_match" as const, expectedChoice: "record_init" },
      feedback: {
        correct: "Baseline temperature first — then react, follow ΔT, and only then compute heat.",
        incorrect: "You need a trustworthy initial reading before mixing changes the system.",
        hint: "Math comes after you have initial and final temperatures.",
      },
      masteryTarget: { conceptNodeId: "thermochemistry", skill: "calorimetry_sequence" },
    },
    {
      id: "chem-th-2-delta-h-line",
      title: "Sign of ΔH",
      type: "number_line" as const,
      prompt: "On this axis, −100 means “100 kJ released per mole of reaction” and +100 means absorbed. Mark roughly −40 for a moderately exothermic reaction.",
      visualPrompt: "Range −100 to +100, steps of 20.",
      data: { min: -100, max: 100, step: 20 },
      interaction: "place_point" as const,
      validation: {
        type: "point_match" as const,
        expectedPoint: { x: -40, y: 0 },
        tolerance: 12,
      },
      feedback: {
        correct: "Negative on this scale means heat released — your marker sits on the exothermic side.",
        incorrect: "Slide left of zero for exothermic; about two small steps left of 0 if each step is 20.",
        hint: "Aim between −20 and −60.",
      },
      masteryTarget: { conceptNodeId: "thermochemistry", skill: "delta_h_sign" },
    },
    {
      id: "chem-th-3-energy-units-grid",
      title: "Energy bookkeeping",
      type: "grid_model" as const,
      prompt: "Shade 5 of 10 cells to show “half the energy accounted for as heat in this toy model” — wait: use exactly 5 for 50% on a 2×5 grid.",
      visualPrompt: "Five cells on, five off.",
      data: { rows: 2, columns: 5 },
      interaction: "tap_to_fill" as const,
      validation: { type: "count_match" as const, expectedCount: 5 },
      feedback: {
        correct: "Half the cells shaded — a quick visual for 50% of the energy in this metaphor.",
        incorrect: "Count shaded squares; you want exactly five of ten.",
        hint: "One full row of five works.",
      },
      masteryTarget: { conceptNodeId: "thermochemistry", skill: "energy_partition_model" },
    },
    {
      id: "chem-th-4-mc-combustion",
      title: "Combustion sign",
      type: "multiple_choice" as const,
      prompt: "Typical combustion of a hydrocarbon in excess O₂ is…",
      visualPrompt: "Think about whether you feel heat from a flame.",
      data: {
        choices: [
          "Exothermic (releases heat)",
          "Endothermic (absorbs heat)",
          "Always thermoneutral",
          "Only endothermic at night",
        ],
      },
      interaction: "select_choice" as const,
      validation: {
        type: "choice_match" as const,
        expectedChoice: "Exothermic (releases heat)",
      },
      feedback: {
        correct: "Flames heat surroundings — combustion is strongly exothermic overall.",
        incorrect: "Burning fuels releases energy; it does not chill the room under normal conditions.",
        hint: "Touch a safe distance from a candle — thermal energy flows out.",
      },
      masteryTarget: { conceptNodeId: "thermochemistry", skill: "combustion_exothermic" },
    },
    {
      id: "chem-th-5-profile-graph",
      title: "Activation hump (toy)",
      type: "graph_plot" as const,
      prompt: "A toy energy profile has reactants low, a peak, then products lower than reactants (exothermic). Tap near the “transition region” high on the curve (around x = 3, y = 5 in this 0–6 window).",
      visualPrompt: "High on the hump, not at the product valley.",
      data: {
        xMin: 0,
        xMax: 6,
        yMin: 0,
        yMax: 6,
        lines: [
          { x1: 0, y1: 2, x2: 3, y2: 5.2 },
          { x1: 3, y1: 5.2, x2: 6, y2: 1.5 },
        ],
      },
      interaction: "place_point" as const,
      validation: {
        type: "point_match" as const,
        expectedPoint: { x: 3, y: 5 },
        tolerance: 0.75,
      },
      feedback: {
        correct: "Near the top of the profile is the activated-complex region in this cartoon.",
        incorrect: "Slide up toward the peak between reactants and products on the dashed path.",
        hint: "Aim around the corner of the two dashed segments.",
      },
      masteryTarget: { conceptNodeId: "enthalpy", skill: "activation_energy_concept" },
    },
  ],
  finalMasteryCheck: {
    id: "chem-th-final-fraction",
    title: "Efficiency toy",
    type: "fraction_bar" as const,
    prompt: "If only 3 of every 8 packets of released energy become useful work in a toy engine, shade 3 of 8 parts.",
    visualPrompt: "Exactly three slices.",
    data: { totalParts: 8 },
    interaction: "tap_to_fill" as const,
    validation: { type: "count_match" as const, expectedCount: 3 },
    feedback: {
      correct: "Three eighths is a simple fraction for “useful fraction” in this mental model.",
      incorrect: "Tap exactly three of the eight parts.",
      hint: "Count to three shaded slices and stop.",
    },
    masteryTarget: { conceptNodeId: "thermochemistry", skill: "efficiency_fraction" },
  },
} as const;
