/** Visual Problem Engine — linear equations from graphs and slope–intercept (math). */
export const MATH_LINEAR_EQUATIONS_LESSON_SEED = {
  id: "lesson-linear-equations-graph",
  title: "Linear equations from graphs",
  subject: "Math",
  topic: "Linear equations",
  level: "beginner" as const,
  scenes: [
    {
      id: "math-lin-1-y-intercept",
      title: "Find the y-intercept",
      type: "graph_plot" as const,
      prompt: "A line crosses the y-axis at (0, 3). Place that intercept on the grid.",
      visualPrompt: "x = 0, y = 3 — on the vertical axis.",
      data: {
        xMin: -2,
        xMax: 6,
        yMin: -2,
        yMax: 6,
        lines: [],
      },
      interaction: "place_point" as const,
      validation: {
        type: "point_match" as const,
        expectedPoint: { x: 0, y: 3 },
        tolerance: 0.45,
      },
      feedback: {
        correct: "(0, 3) is the y-intercept — where the line meets the vertical axis.",
        incorrect: "Move to x = 0 (the y-axis) and y = 3.",
        hint: "The y-intercept always has x = 0.",
      },
      masteryTarget: { conceptNodeId: "linear-equations", skill: "y_intercept_plot" },
    },
    {
      id: "math-lin-2-slope-point",
      title: "Rise over run",
      type: "graph_plot" as const,
      prompt: "From (0, 1), the line rises 2 units when x increases by 1. Place the next lattice point at (1, 3).",
      visualPrompt: "One step right, two steps up from (0, 1).",
      data: {
        xMin: -1,
        xMax: 5,
        yMin: -1,
        yMax: 5,
        lines: [{ x1: 0, y1: 1, x2: 0, y2: 1 }],
      },
      interaction: "place_point" as const,
      validation: {
        type: "point_match" as const,
        expectedPoint: { x: 1, y: 3 },
        tolerance: 0.45,
      },
      feedback: {
        correct: "(1, 3) — slope 2 means Δy = 2 when Δx = 1.",
        incorrect: "From (0, 1), go one right and two up to reach (1, 3).",
        hint: "Rise 2, run 1 from the starting point.",
      },
      masteryTarget: { conceptNodeId: "linear-equations", skill: "slope_rise_run" },
    },
    {
      id: "math-lin-3-solve-steps",
      title: "Solve in order",
      type: "drag_drop_sort" as const,
      prompt: "Order the steps to solve 2x + 6 = 14.",
      visualPrompt: "Isolate x — undo addition before division.",
      data: {
        items: [
          "Subtract 6 from both sides: 2x = 8",
          "Divide both sides by 2: x = 4",
          "Check: 2(4) + 6 = 14 ✓",
        ],
      },
      interaction: "reorder" as const,
      validation: {
        type: "ordered_sequence" as const,
        expectedOrder: [
          "Subtract 6 from both sides: 2x = 8",
          "Divide both sides by 2: x = 4",
          "Check: 2(4) + 6 = 14 ✓",
        ],
      },
      feedback: {
        correct: "Undo +6 first, then ÷2, then verify — the standard two-step solve.",
        incorrect: "You cannot divide before removing the constant term from both sides.",
        hint: "Remove the +6 before dealing with the coefficient 2.",
      },
      masteryTarget: { conceptNodeId: "linear-equations", skill: "two_step_solve_order" },
    },
    {
      id: "math-lin-4-number-line-solution",
      title: "Solution on a line",
      type: "number_line" as const,
      prompt: "The solution x = 4 sits on this number line (−2 to 10, step 1). Mark 4.",
      visualPrompt: "Four ticks to the right of zero.",
      data: { min: -2, max: 10, step: 1 },
      interaction: "place_point" as const,
      validation: {
        type: "point_match" as const,
        expectedPoint: { x: 4, y: 0 },
        tolerance: 0.35,
      },
      feedback: {
        correct: "x = 4 — your marker matches the algebraic solution.",
        incorrect: "Count four unit steps right from zero.",
        hint: "Zero, one, two, three, four.",
      },
      masteryTarget: { conceptNodeId: "linear-equations", skill: "solution_number_line" },
    },
    {
      id: "math-lin-5-slope-grid",
      title: "Slope as a ratio",
      type: "grid_model" as const,
      prompt: "A 1×4 grid models 'rise 2, run 4'. Shade exactly 2 of the 4 cells to show the rise portion.",
      visualPrompt: "Two shaded cells out of four total.",
      data: { rows: 1, columns: 4 },
      interaction: "tap_to_fill" as const,
      validation: { type: "count_match" as const, expectedCount: 2 },
      feedback: {
        correct: "2 of 4 = rise/run = 2/4 = 1/2 — slope one half.",
        incorrect: "Shade exactly two of the four equal cells.",
        hint: "The rise is the numerator — 2 in a 2:4 ratio.",
      },
      masteryTarget: { conceptNodeId: "linear-equations", skill: "slope_ratio_model" },
    },
  ],
  finalMasteryCheck: {
    id: "math-lin-final-equation",
    title: "Write the equation",
    type: "segment_select" as const,
    prompt: "A line has y-intercept 3 and slope 2. Which equation matches y = mx + b?",
    visualPrompt: "m = 2, b = 3.",
    data: {
      segments: [
        { id: "correct", label: "y = 2x + 3" },
        { id: "swap", label: "y = 3x + 2" },
        { id: "neg", label: "y = −2x + 3" },
        { id: "wrong", label: "y = 2x − 3" },
      ],
    },
    interaction: "select_choice" as const,
    validation: { type: "choice_match" as const, expectedChoice: "correct" },
    feedback: {
      correct: "y = 2x + 3 — slope 2, intercept 3.",
      incorrect: "Slope is the coefficient of x; intercept is the constant term.",
      hint: "m comes first: 2x, then add b = 3.",
    },
    masteryTarget: { conceptNodeId: "linear-equations", skill: "slope_intercept_equation" },
  },
} as const;
