/** Visual Problem Engine — mitosis order and cell-cycle sense-making (biology). */
export const BIOLOGY_MITOSIS_LESSON_SEED = {
  id: "lesson-mitosis-sequence",
  title: "Mitosis: order the story",
  subject: "Biology",
  topic: "Cell division",
  level: "beginner" as const,
  scenes: [
    {
      id: "bio-mito-1-phases",
      title: "Name the phases",
      type: "segment_select" as const,
      prompt: "Which major mitotic phase happens first among these?",
      visualPrompt: "Chromosomes condense and the spindle gets organized before anything lines up at the middle.",
      data: {
        segments: [
          { id: "prophase", label: "Prophase" },
          { id: "metaphase", label: "Metaphase" },
          { id: "anaphase", label: "Anaphase" },
          { id: "telophase", label: "Telophase" },
        ],
      },
      interaction: "select_choice" as const,
      validation: { type: "choice_match" as const, expectedChoice: "prophase" },
      feedback: {
        correct: "Prophase opens mitosis — then metaphase → anaphase → telophase.",
        incorrect: "Condensation and spindle setup happen first; splitting chromatids happens after they line up.",
        hint: "Think: prepare → line up → pull apart → two new nuclei.",
      },
      masteryTarget: { conceptNodeId: "cell-division", skill: "mitosis_phase_order" },
    },
    {
      id: "bio-mito-2-events",
      title: "What happens when?",
      type: "drag_drop_sort" as const,
      prompt: "Order these events during one mitotic division.",
      visualPrompt: "Same division, finer narrative — earliest at the top.",
      data: {
        items: [
          "Two new nuclei finish forming; the cell begins to pinch",
          "Identical chromatids are pulled toward opposite poles",
          "Duplicated chromosomes line up along the cell equator",
          "Chromosomes condense; spindle poles move apart",
        ],
      },
      interaction: "reorder" as const,
      validation: {
        type: "ordered_sequence" as const,
        expectedOrder: [
          "Chromosomes condense; spindle poles move apart",
          "Duplicated chromosomes line up along the cell equator",
          "Identical chromatids are pulled toward opposite poles",
          "Two new nuclei finish forming; the cell begins to pinch",
        ],
      },
      feedback: {
        correct: "Condense and capture → line up → pull apart → reform nuclei — that matches what you dragged.",
        incorrect: "Chromatids cannot separate before chromosomes meet in the middle.",
        hint: "Middle step is always “line up at the equator.”",
      },
      masteryTarget: { conceptNodeId: "cell-division", skill: "mitosis_event_order" },
    },
    {
      id: "bio-mito-3-grid-plate",
      title: "Metaphase plate model",
      type: "grid_model" as const,
      prompt: "In this 3×3 toy model, shade exactly one center square for the metaphase plate.",
      visualPrompt: "Tap the middle cell only.",
      data: { rows: 3, columns: 3 },
      interaction: "tap_to_fill" as const,
      validation: { type: "count_match" as const, expectedCount: 1 },
      feedback: {
        correct: "One center square — a stand-in for chromosomes meeting along the middle of the cell.",
        incorrect: "Only the single center cell should be shaded for this metaphor.",
        hint: "Row 2, column 2 in a 3×3 grid is the center.",
      },
      masteryTarget: { conceptNodeId: "cell-division", skill: "metaphase_plate_model" },
    },
    {
      id: "bio-mito-4-mc-anaphase",
      title: "Check understanding",
      type: "multiple_choice" as const,
      prompt: "In which phase do sister chromatids separate and move toward opposite poles?",
      visualPrompt: "Pick the phase name that matches that motion.",
      data: { choices: ["Anaphase", "Metaphase", "Telophase", "Prophase"] },
      interaction: "select_choice" as const,
      validation: { type: "choice_match" as const, expectedChoice: "Anaphase" },
      feedback: {
        correct: "Anaphase is when spindle shortening pulls sister chromatids apart.",
        incorrect: "Separation happens after alignment — not while chromosomes are parked at the equator.",
        hint: "The phase name starts with “Ana-” like “apart.”",
      },
      masteryTarget: { conceptNodeId: "cell-division", skill: "anaphase_definition" },
    },
    {
      id: "bio-mito-5-cycle-timeline",
      title: "Interphase dominates",
      type: "number_line" as const,
      prompt: "In many mammal cells, interphase is roughly 90% of the cell cycle. Mark ~90 on this timeline (0–100%).",
      visualPrompt: "Steps of 10 from 0 to 100.",
      data: { min: 0, max: 100, step: 10 },
      interaction: "place_point" as const,
      validation: {
        type: "point_match" as const,
        expectedPoint: { x: 90, y: 0 },
        tolerance: 6,
      },
      feedback: {
        correct: "Near 90% — mitosis is the short burst; most of the life of the cell is growth and DNA prep.",
        incorrect: "Slide toward the high end of the scale; interphase is almost the whole timeline.",
        hint: "Nine ticks of size 10 from zero lands on 90.",
      },
      masteryTarget: { conceptNodeId: "cell-division", skill: "interphase_proportion" },
    },
  ],
  finalMasteryCheck: {
    id: "bio-mito-final-graph",
    title: "Growth curve checkpoint",
    type: "graph_plot" as const,
    prompt: "A textbook plots “relative cell size” vs “time after division.” Tap where early G₁ might sit: modest size, not yet doubled.",
    visualPrompt: "x = time (0–6), y = relative size (0–6). Place around (1, 2).",
    data: {
      xMin: 0,
      xMax: 6,
      yMin: 0,
      yMax: 6,
      lines: [],
    },
    interaction: "place_point" as const,
    validation: {
      type: "point_match" as const,
      expectedPoint: { x: 1, y: 2 },
      tolerance: 0.55,
    },
    feedback: {
      correct: "Early G₁ is small and early on the time axis — your point matches that idea.",
      incorrect: "Move left and low: soon after division the cell is still rebuilding, not yet at maximum size.",
      hint: "Try just right of the origin, a bit up from the bottom.",
    },
    masteryTarget: { conceptNodeId: "cell-division", skill: "cell_cycle_growth_plot" },
  },
} as const;
