/** Visual Problem Engine — coordinates & slope intuition (algebra). */
export const SLOPE_INTRO_VISUAL_LESSON_SEED = {
  id: "lesson-slope-from-points",
  title: "Slope from points on a grid",
  subject: "Math",
  topic: "Linear functions",
  level: "beginner" as const,
  scenes: [
    {
      id: "slp-1-plot-point",
      title: "Mark a point",
      type: "graph_plot" as const,
      prompt: "Tap the grid to place a point at (3, 2): 3 on the horizontal axis, 2 on the vertical.",
      visualPrompt: "Tap roughly where x = 3 and y = 2 meet.",
      data: {
        xMin: 0,
        xMax: 6,
        yMin: 0,
        yMax: 6,
        lines: [],
      },
      interaction: "place_point" as const,
      validation: {
        type: "point_match" as const,
        expectedPoint: { x: 3, y: 2 },
        tolerance: 0.45,
      },
      feedback: {
        correct: "Your point sits near (3, 2) — three across and two up from the origin style corner.",
        incorrect: "Move to where the vertical line through x = 3 meets the horizontal through y = 2.",
        hint: "Count three to the right along the bottom axis, then two up.",
      },
      masteryTarget: { conceptNodeId: "linear-functions", skill: "plot_integer_coordinates" },
    },
    {
      id: "slp-2-second-point",
      title: "Another point",
      type: "graph_plot" as const,
      prompt: "Place (1, 4) on the same grid.",
      visualPrompt: "One step right of the origin style corner, four steps up.",
      data: {
        xMin: 0,
        xMax: 6,
        yMin: 0,
        yMax: 6,
        lines: [],
      },
      interaction: "place_point" as const,
      validation: {
        type: "point_match" as const,
        expectedPoint: { x: 1, y: 4 },
        tolerance: 0.45,
      },
      feedback: {
        correct: "(1, 4) means x = 1 and y = 4 — your dot matches that address.",
        incorrect: "Slide to x = 1 on the bottom, then rise to height y = 4.",
        hint: "Near the left edge but high up on the plot.",
      },
      masteryTarget: { conceptNodeId: "linear-functions", skill: "plot_second_point" },
    },
    {
      id: "slp-3-number-line-rise",
      title: "Vertical change",
      type: "number_line" as const,
      prompt: "On this axis from 0 to 6, mark the value 4 (a rise of 4 if you started at 0).",
      visualPrompt: "Steps of 0.5 — land on 4.0.",
      data: { min: 0, max: 6, step: 0.5 },
      interaction: "place_point" as const,
      validation: {
        type: "point_match" as const,
        expectedPoint: { x: 4, y: 0 },
        tolerance: 0.15,
      },
      feedback: {
        correct: "4 on the axis matches a rise of four units in a rise/run story.",
        incorrect: "Count eight half steps from 0, or four whole steps — you want the tick at 4.",
        hint: "Half, 1, 1.5… keep counting until you reach 4.0.",
      },
      masteryTarget: { conceptNodeId: "linear-functions", skill: "rise_on_axis" },
    },
    {
      id: "slp-4-mc-slope",
      title: "Compute slope",
      type: "multiple_choice" as const,
      prompt: "Through (0, 0) and (2, 4), what is the slope Δy/Δx?",
      visualPrompt: "Rise 4 while run 2 simplifies to…",
      data: { choices: ["2", "4", "1/2", "1/4"] },
      interaction: "select_choice" as const,
      validation: { type: "choice_match" as const, expectedChoice: "2" },
      feedback: {
        correct: "Slope = (4 − 0)/(2 − 0) = 2 — the line goes up two for every one to the right.",
        incorrect: "Divide the vertical change by the horizontal change between the two points.",
        hint: "Rise 4, run 2 → 4/2.",
      },
      masteryTarget: { conceptNodeId: "linear-functions", skill: "slope_formula" },
    },
    {
      id: "slp-5-order-steps",
      title: "Order the reasoning",
      type: "segment_select" as const,
      prompt: "What should you do first when finding slope from a graphed line?",
      visualPrompt: "You need two anchors before any rise/run numbers are meaningful.",
      data: {
        segments: [
          { id: "pick_points", label: "Pick two clear points on the line" },
          { id: "divide_first", label: "Compute Δy / Δx before choosing points" },
          { id: "dy_first", label: "Read Δy before you know which two points you will use" },
          { id: "guess", label: "Guess the slope from the title of the graph" },
        ],
      },
      interaction: "select_choice" as const,
      validation: { type: "choice_match" as const, expectedChoice: "pick_points" },
      feedback: {
        correct: "Points first, then Δx and Δy between them, then the ratio — that is the clean workflow.",
        incorrect: "You need two anchor points before you can read Δx and Δy in a consistent order.",
        hint: "Start by choosing points; division comes last.",
      },
      masteryTarget: { conceptNodeId: "linear-functions", skill: "slope_reasoning_order" },
    },
  ],
  finalMasteryCheck: {
    id: "slp-final-origin-line",
    title: "Mastery plot",
    type: "graph_plot" as const,
    prompt: "The line through the origin with slope 1 passes through (4, 4). Place that point.",
    visualPrompt: "Same 0–6 window on both axes.",
    data: {
      xMin: 0,
      xMax: 6,
      yMin: 0,
      yMax: 6,
      lines: [{ x1: 0, y1: 0, x2: 6, y2: 6 }],
    },
    interaction: "place_point" as const,
    validation: {
      type: "point_match" as const,
      expectedPoint: { x: 4, y: 4 },
      tolerance: 0.45,
    },
    feedback: {
      correct: "(4, 4) sits on y = x — equal run and rise, slope 1.",
      incorrect: "Along the diagonal through the corner, run and rise stay equal; find where both coordinates are 4.",
      hint: "Move diagonally along the dashed guide until x and y both read 4.",
    },
    masteryTarget: { conceptNodeId: "linear-functions", skill: "slope_one_line" },
  },
} as const;
