/** Visual Problem Engine — Punnett squares and Mendelian inheritance (biology). */
export const BIOLOGY_PUNNETT_LESSON_SEED = {
  id: "lesson-punnett-square-basics",
  title: "Punnett square basics",
  subject: "Biology",
  topic: "Genetics",
  level: "beginner" as const,
  scenes: [
    {
      id: "bio-pun-1-heterozygous",
      title: "Dominant vs recessive",
      type: "segment_select" as const,
      prompt: "In pea plants, tall (T) is dominant over short (t). A heterozygous tall plant has which genotype?",
      visualPrompt: "One dominant allele and one recessive allele.",
      data: {
        segments: [
          { id: "TT", label: "TT" },
          { id: "Tt", label: "Tt" },
          { id: "tt", label: "tt" },
          { id: "tT", label: "tT (different order)" },
        ],
      },
      interaction: "select_choice" as const,
      validation: { type: "choice_match" as const, expectedChoice: "Tt" },
      feedback: {
        correct: "Tt — one T and one t. Heterozygous means two different alleles.",
        incorrect: "TT is homozygous dominant; tt is homozygous recessive. Heterozygous = Tt.",
        hint: "Look for one uppercase and one lowercase letter.",
      },
      masteryTarget: { conceptNodeId: "genetics-inheritance", skill: "heterozygous_genotype" },
    },
    {
      id: "bio-pun-2-square-grid",
      title: "Fill the Punnett square",
      type: "grid_model" as const,
      prompt: "A 2×2 Punnett square has four offspring cells. Shade exactly 4 cells to show you've filled the entire square.",
      visualPrompt: "All four outcome cells should be marked.",
      data: { rows: 2, columns: 2 },
      interaction: "tap_to_fill" as const,
      validation: { type: "count_match" as const, expectedCount: 4 },
      feedback: {
        correct: "All four cells — each represents one equally likely gamete combination.",
        incorrect: "A complete 2×2 Punnett square has four offspring boxes.",
        hint: "Tap every cell in the grid.",
      },
      masteryTarget: { conceptNodeId: "genetics-inheritance", skill: "punnett_grid_complete" },
    },
    {
      id: "bio-pun-3-cross-steps",
      title: "Monohybrid cross steps",
      type: "drag_drop_sort" as const,
      prompt: "Order the steps to cross two Tt parents.",
      visualPrompt: "Setup → gametes → combine → read phenotypes.",
      data: {
        items: [
          "List each parent's alleles: T and t from each Tt parent",
          "Place one allele from each parent in each Punnett cell",
          "Count offspring genotypes: 1 TT, 2 Tt, 1 tt",
          "Predict phenotypes: 3 tall : 1 short",
        ],
      },
      interaction: "reorder" as const,
      validation: {
        type: "ordered_sequence" as const,
        expectedOrder: [
          "List each parent's alleles: T and t from each Tt parent",
          "Place one allele from each parent in each Punnett cell",
          "Count offspring genotypes: 1 TT, 2 Tt, 1 tt",
          "Predict phenotypes: 3 tall : 1 short",
        ],
      },
      feedback: {
        correct: "Alleles → fill square → genotype ratio → phenotype ratio — classic monohybrid cross.",
        incorrect: "You need gametes before you can fill cells, and genotypes before phenotypes.",
        hint: "What do you need before you can fill the four boxes?",
      },
      masteryTarget: { conceptNodeId: "genetics-inheritance", skill: "monohybrid_cross_order" },
    },
    {
      id: "bio-pun-4-ratio-bar",
      title: "3:1 phenotype ratio",
      type: "fraction_bar" as const,
      prompt: "The 3:1 tall-to-short ratio has 4 total parts. Shade 3 parts to show the fraction of tall offspring.",
      visualPrompt: "Three of four parts = 75% tall.",
      data: { totalParts: 4 },
      interaction: "tap_to_fill" as const,
      validation: { type: "count_match" as const, expectedCount: 3 },
      feedback: {
        correct: "3/4 tall — the classic Mendelian monohybrid phenotype ratio.",
        incorrect: "Three of the four equal parts should be shaded for the dominant phenotype share.",
        hint: "Three tall for every one short means three shaded slices.",
      },
      masteryTarget: { conceptNodeId: "genetics-inheritance", skill: "phenotype_ratio_model" },
    },
    {
      id: "bio-pun-5-gamete-line",
      title: "Gamete combinations",
      type: "number_line" as const,
      prompt: "Each Tt parent makes 2 types of gametes (T or t). Two parents → 2 × 2 = 4 combinations. Mark 4 on this scale (0–6, step 1).",
      visualPrompt: "The product of gamete choices gives Punnett square size.",
      data: { min: 0, max: 6, step: 1 },
      interaction: "place_point" as const,
      validation: {
        type: "point_match" as const,
        expectedPoint: { x: 4, y: 0 },
        tolerance: 0.35,
      },
      feedback: {
        correct: "4 combinations — that's why a monohybrid cross uses a 2×2 square.",
        incorrect: "2 gamete types × 2 gamete types = 4 offspring cells.",
        hint: "Mark the fourth tick on the line.",
      },
      masteryTarget: { conceptNodeId: "genetics-inheritance", skill: "gamete_combination_count" },
    },
  ],
  finalMasteryCheck: {
    id: "bio-pun-final-probability",
    title: "Probability checkpoint",
    type: "segment_select" as const,
    prompt: "From a Tt × Tt cross, what is the probability of a homozygous recessive (tt) offspring?",
    visualPrompt: "One of four cells in the Punnett square is tt.",
    data: {
      segments: [
        { id: "quarter", label: "1/4 (25%)" },
        { id: "half", label: "1/2 (50%)" },
        { id: "threequarter", label: "3/4 (75%)" },
        { id: "all", label: "1 (100%)" },
      ],
    },
    interaction: "select_choice" as const,
    validation: { type: "choice_match" as const, expectedChoice: "quarter" },
    feedback: {
      correct: "1/4 — one tt cell out of four in the standard Tt × Tt square.",
      incorrect: "Count the tt box: one of four equally likely outcomes.",
      hint: "How many of the four cells are tt?",
    },
    masteryTarget: { conceptNodeId: "genetics-inheritance", skill: "recessive_probability" },
  },
} as const;
