/** Visual Problem Engine — work, energy, and conservation (physics). */
export const PHYSICS_WORK_ENERGY_LESSON_SEED = {
  id: "lesson-work-energy-basics",
  title: "Work & energy basics",
  subject: "Physics",
  topic: "Work & energy",
  level: "beginner" as const,
  scenes: [
    {
      id: "phy-we-1-work-definition",
      title: "When is work done?",
      type: "segment_select" as const,
      prompt: "A force does mechanical work on an object when the force has a component in which direction relative to displacement?",
      visualPrompt: "W = F·d·cos θ — need overlap with motion.",
      data: {
        segments: [
          { id: "parallel", label: "Parallel to the displacement" },
          { id: "perp", label: "Perpendicular to the displacement" },
          { id: "opposite", label: "Always opposite to displacement" },
          { id: "none", label: "Direction doesn't matter" },
        ],
      },
      interaction: "select_choice" as const,
      validation: { type: "choice_match" as const, expectedChoice: "parallel" },
      feedback: {
        correct: "A component along the displacement — perpendicular force does zero work (like centripetal).",
        incorrect: "Work requires force and displacement to align at least partly.",
        hint: "Pushing forward on a box sliding forward — that's work.",
      },
      masteryTarget: { conceptNodeId: "work-energy", skill: "work_direction" },
    },
    {
      id: "phy-we-2-energy-forms",
      title: "Energy conversion",
      type: "drag_drop_sort" as const,
      prompt: "Order the energy story as a book falls from a shelf to the floor.",
      visualPrompt: "Gravitational PE → KE → other forms on impact.",
      data: {
        items: [
          "Gravitational potential energy is highest on the shelf",
          "KE increases as the book falls and speeds up",
          "On impact, some energy becomes sound and thermal energy",
        ],
      },
      interaction: "reorder" as const,
      validation: {
        type: "ordered_sequence" as const,
        expectedOrder: [
          "Gravitational potential energy is highest on the shelf",
          "KE increases as the book falls and speeds up",
          "On impact, some energy becomes sound and thermal energy",
        ],
      },
      feedback: {
        correct: "PE high → KE grows → dissipates at impact — energy transforms but isn't destroyed.",
        incorrect: "Start at rest on the shelf before the fall accelerates.",
        hint: "Where is gravitational PE maximum?",
      },
      masteryTarget: { conceptNodeId: "work-energy", skill: "energy_conversion_order" },
    },
    {
      id: "phy-we-3-ke-graph",
      title: "KE grows with speed",
      type: "graph_plot" as const,
      prompt: "KE = ½mv². At v = 4 m/s (with fixed mass), mark the point (4, 8) on a toy graph where y = KE in joules.",
      visualPrompt: "x = speed (0–6), y = KE (0–12).",
      data: {
        xMin: 0,
        xMax: 6,
        yMin: 0,
        yMax: 12,
        lines: [],
      },
      interaction: "place_point" as const,
      validation: {
        type: "point_match" as const,
        expectedPoint: { x: 4, y: 8 },
        tolerance: 0.55,
      },
      feedback: {
        correct: "(4, 8) — doubling speed quadruples KE for the same mass.",
        incorrect: "Place at x = 4, y = 8 on the grid.",
        hint: "Four across, eight up from the origin-style corner.",
      },
      masteryTarget: { conceptNodeId: "work-energy", skill: "ke_speed_plot" },
    },
    {
      id: "phy-we-4-pe-number-line",
      title: "Gravitational PE",
      type: "number_line" as const,
      prompt: "PE = mgh. At h = 5 m (with g and m fixed), mark 5 on this height scale (0–10 m, step 1).",
      visualPrompt: "Higher height → higher gravitational PE.",
      data: { min: 0, max: 10, step: 1 },
      interaction: "place_point" as const,
      validation: {
        type: "point_match" as const,
        expectedPoint: { x: 5, y: 0 },
        tolerance: 0.35,
      },
      feedback: {
        correct: "5 m — PE scales linearly with height near Earth's surface.",
        incorrect: "Mark the fifth tick on the height axis.",
        hint: "Count five unit steps from zero.",
      },
      masteryTarget: { conceptNodeId: "work-energy", skill: "pe_height_scale" },
    },
    {
      id: "phy-we-5-conservation-grid",
      title: "Closed system",
      type: "grid_model" as const,
      prompt: "Energy conservation: total energy in a closed system stays constant. In a 2×5 grid of 'energy buckets,' shade exactly 5 cells to show 'half the buckets hold energy at one instant'.",
      visualPrompt: "5 of 10 cells = half.",
      data: { rows: 2, columns: 5 },
      interaction: "tap_to_fill" as const,
      validation: { type: "count_match" as const, expectedCount: 5 },
      feedback: {
        correct: "Half the buckets — energy redistributes but total stays fixed in a closed system.",
        incorrect: "Shade exactly five of the ten cells.",
        hint: "Half of 2×5 = 5 cells.",
      },
      masteryTarget: { conceptNodeId: "work-energy", skill: "conservation_model" },
    },
  ],
  finalMasteryCheck: {
    id: "phy-we-final-work-calc",
    title: "Calculate work",
    type: "segment_select" as const,
    prompt: "A 10 N force pushes a box 3 m in the direction of the force. How much work is done?",
    visualPrompt: "W = Fd when force and displacement align.",
    data: {
      segments: [
        { id: "30", label: "30 J" },
        { id: "13", label: "13 J" },
        { id: "7", label: "7 J" },
        { id: "0", label: "0 J" },
      ],
    },
    interaction: "select_choice" as const,
    validation: { type: "choice_match" as const, expectedChoice: "30" },
    feedback: {
      correct: "W = Fd = 10 × 3 = 30 joules.",
      incorrect: "Multiply force (N) by displacement (m) when they point the same way.",
      hint: "10 times 3.",
    },
    masteryTarget: { conceptNodeId: "work-energy", skill: "work_calculation" },
  },
} as const;
