/** Visual Problem Engine — limiting reagent reasoning (chemistry). */
export const CHEMISTRY_LIMITING_LESSON_SEED = {
  id: "lesson-limiting-reagent-reasoning",
  title: "Limiting reagent: compare the runners",
  subject: "Chemistry",
  topic: "Limiting reagents",
  level: "intermediate" as const,
  scenes: [
    {
      id: "chem-lim-1-strategy-order",
      title: "Strategy order",
      type: "segment_select" as const,
      prompt: "When two reactant masses are given, what is the first computational move toward finding the limiting reagent?",
      visualPrompt: "You need comparable “moles per recipe slice” before you compare who runs out.",
      data: {
        segments: [
          { id: "to_moles", label: "Convert each reactant mass to moles" },
          { id: "pick_smallest_moles", label: "Compare raw moles only (ignore coefficients)" },
          { id: "product_first", label: "Use mole ratio to find product before any conversion" },
          { id: "quotient_first", label: "Divide by coefficients before you have moles" },
        ],
      },
      interaction: "select_choice" as const,
      validation: { type: "choice_match" as const, expectedChoice: "to_moles" },
      feedback: {
        correct: "Moles first — then divide by coefficients, compare quotients, pick the limiter, then product moles.",
        incorrect: "You cannot pick the limiter before each reactant is expressed in moles.",
        hint: "Mass → moles is always the opening move when you start from grams.",
      },
      masteryTarget: { conceptNodeId: "limiting-reagents", skill: "limiting_algorithm_order" },
    },
    {
      id: "chem-lim-2-recipe-drag",
      title: "Sandwich analogy",
      type: "drag_drop_sort" as const,
      prompt: "You have bread slices and cheese slices for “sandwiches” (1 bread + 1 cheese each). Order what you check first.",
      visualPrompt: "Think limiting ingredient.",
      data: {
        items: [
          "See which ingredient runs out first when pairing",
          "Count how many cheese slices you have",
          "Count how many bread slices you have",
          "The smaller complete sandwich count is the limit",
        ],
      },
      interaction: "reorder" as const,
      validation: {
        type: "ordered_sequence" as const,
        expectedOrder: [
          "Count how many bread slices you have",
          "Count how many cheese slices you have",
          "See which ingredient runs out first when pairing",
          "The smaller complete sandwich count is the limit",
        ],
      },
      feedback: {
        correct: "Count both stacks, pair them mentally, then the smaller count caps product — same logic as limiting reagents.",
        incorrect: "You compare inventories before you know which runs out in the pairing.",
        hint: "Counts before pairing; the cap is last.",
      },
      masteryTarget: { conceptNodeId: "limiting-reagents", skill: "limiting_analogy" },
    },
    {
      id: "chem-lim-3-quotient-bar",
      title: "Per-coefficient amount",
      type: "fraction_bar" as const,
      prompt: "Two runners “A” and “B” tie to coefficients 2 and 3 in the equation. Model A’s coefficient as 6 parts: shade 2 parts to show “2 portions of recipe” visually (toy).",
      visualPrompt: "Exactly two slices of six.",
      data: { totalParts: 6 },
      interaction: "tap_to_fill" as const,
      validation: { type: "count_match" as const, expectedCount: 2 },
      feedback: {
        correct: "Two of six links to thinking in “parts per total” before you compare limiters.",
        incorrect: "Shade exactly two parts of the six-part bar.",
        hint: "Tap two slices only.",
      },
      masteryTarget: { conceptNodeId: "stoichiometry-calc", skill: "coefficient_visual" },
    },
    {
      id: "chem-lim-4-mc-quotient",
      title: "Which runs out?",
      type: "multiple_choice" as const,
      prompt: "If 0.50 mol A (coeff 2) and 0.40 mol B (coeff 1) react, which comparison is the right “per-coefficient” check?",
      visualPrompt: "Smaller moles/coefficient limits.",
      data: {
        choices: [
          "Compare 0.50/2 vs 0.40/1 — smaller quotient limits",
          "Compare 0.50 vs 0.40 only — smaller moles always limits",
          "Compare 2 vs 1 only — larger coefficient always limits",
          "Add moles and divide by two",
        ],
      },
      interaction: "select_choice" as const,
      validation: {
        type: "choice_match" as const,
        expectedChoice: "Compare 0.50/2 vs 0.40/1 — smaller quotient limits",
      },
      feedback: {
        correct: "0.50/2 = 0.25 and 0.40/1 = 0.40 — A supplies fewer “reaction portions,” so A limits here.",
        incorrect: "Raw moles ignore stoichiometry; always scale by the balanced coefficient first.",
        hint: "Divide each amount by its coefficient, then compare.",
      },
      masteryTarget: { conceptNodeId: "limiting-reagents", skill: "quotient_rule" },
    },
    {
      id: "chem-lim-5-product-grid",
      title: "Product cap toy",
      type: "grid_model" as const,
      prompt: "The limiter caps product at “3 units” in this toy. Shade exactly 3 cells in a 2×4 grid.",
      visualPrompt: "Any three cells.",
      data: { rows: 2, columns: 4 },
      interaction: "tap_to_fill" as const,
      validation: { type: "count_match" as const, expectedCount: 3 },
      feedback: {
        correct: "Three shaded cells — a stand-in for moles of product capped by the limiter.",
        incorrect: "Count to exactly three shaded squares.",
        hint: "Undo if you have four or more.",
      },
      masteryTarget: { conceptNodeId: "limiting-reagents", skill: "product_cap_model" },
    },
  ],
  finalMasteryCheck: {
    id: "chem-lim-final-graph",
    title: "Leftover sense",
    type: "graph_plot" as const,
    prompt: "On a toy plot, x = “moles of excess reactant added beyond stoichiometric need,” y = “moles of excess left unreacted.” After the stoichiometric point, leftover climbs. Place a point in the “past stoichiometry, leftover rising” region.",
    visualPrompt: "Try high x and moderately high y (e.g. around 4.5, 3.5) in the 0–6 window.",
    data: {
      xMin: 0,
      xMax: 6,
      yMin: 0,
      yMax: 6,
      lines: [
        { x1: 2, y1: 0.5, x2: 5, y2: 3.5 },
      ],
    },
    interaction: "place_point" as const,
    validation: {
      type: "point_match" as const,
      expectedPoint: { x: 4.5, y: 3.2 },
      tolerance: 0.85,
    },
    feedback: {
      correct: "Far along x with y climbing matches “added excess, unreacted excess grows” in this cartoon.",
      incorrect: "Slide right and upward along the idea of leftover reagent after the limiter is consumed.",
      hint: "Stay away from the origin; think upper-right of the plot.",
    },
    masteryTarget: { conceptNodeId: "limiting-reagents", skill: "excess_leftover_concept" },
  },
} as const;
