/** Visual Problem Engine — gear ratios & rotation (math / physics). */
export const MATH_GEAR_RATIOS_LESSON_SEED = {
  id: "lesson-gear-ratios-intro",
  title: "Gear ratios intro",
  subject: "Math",
  topic: "Ratios & proportions",
  level: "beginner" as const,
  scenes: [
    {
      id: "gear-1-spin",
      title: "Spin the driver",
      type: "gear" as const,
      prompt: "Rotate the 12-tooth driver and watch the 24-tooth driven gear turn the other way.",
      visualPrompt: "Connected gears rotate together — opposite directions, linked speeds.",
      data: { driverTeeth: 12, drivenOptions: [24], defaultDrivenTeeth: 24 },
      interaction: "drag_to_place" as const,
      validation: { type: "gear_match" as const, driverTeeth: 12, drivenTeeth: 24 },
      feedback: {
        correct: "12:24 means the driver turns twice for each driven turn — a 2:1 speed ratio.",
        incorrect: "Keep the 24-tooth driven gear meshed with the 12-tooth driver.",
        hint: "Count teeth: double the driver teeth on the driven gear gives half the speed.",
      },
      masteryTarget: { conceptNodeId: "properties", skill: "gear_observation" },
    },
    {
      id: "gear-2-pick-ratio",
      title: "Build a 1:3 ratio",
      type: "gear" as const,
      prompt: "Select the driven gear so the ratio is 12:36 (driver turns 3× per driven turn).",
      visualPrompt: "More driven teeth → slower output rotation.",
      data: { driverTeeth: 12, drivenOptions: [24, 36, 48] },
      interaction: "drag_to_place" as const,
      validation: { type: "gear_match" as const, driverTeeth: 12, drivenTeeth: 36 },
      feedback: {
        correct: "12:36 = 1:3 — three driver revolutions per one driven revolution.",
        incorrect: "For a 1:3 ratio with a 12T driver, the driven gear needs 36 teeth.",
        hint: "Multiply driver teeth by 3: 12 × 3 = 36.",
      },
      masteryTarget: { conceptNodeId: "properties", skill: "gear_ratio_select" },
    },
    {
      id: "gear-3-mc",
      title: "Read the ratio",
      type: "multiple_choice" as const,
      prompt: "A 12-tooth driver meshes with a 36-tooth driven gear. How many driver turns per driven turn?",
      visualPrompt: "Use the ratio you just built.",
      data: { choices: ["3", "2", "1/3", "36"] },
      interaction: "select_choice" as const,
      validation: { type: "choice_match" as const, expectedChoice: "3" },
      feedback: {
        correct: "3 driver turns per 1 driven turn — that's the mechanical meaning of 12:36.",
        incorrect: "Ratio 12:36 simplifies to 1:3 for rotations: driver turns ÷ driven turns = 36/12 = 3.",
        hint: "Divide driven teeth by driver teeth: 36 ÷ 12.",
      },
      masteryTarget: { conceptNodeId: "properties", skill: "gear_ratio_read" },
    },
    {
      id: "gear-4-slow-output",
      title: "Slow the output",
      type: "gear" as const,
      prompt: "Pick the largest driven gear to maximize torque (slowest output).",
      visualPrompt: "More teeth on the driven gear = slower spin, more force.",
      data: { driverTeeth: 12, drivenOptions: [24, 36, 48] },
      interaction: "drag_to_place" as const,
      validation: { type: "gear_match" as const, driverTeeth: 12, drivenTeeth: 48 },
      feedback: {
        correct: "48T driven — a 1:4 ratio. Slowest output, greatest mechanical advantage.",
        incorrect: "The largest driven gear (48T) gives the biggest reduction.",
        hint: "Choose the option with the most teeth.",
      },
      masteryTarget: { conceptNodeId: "properties", skill: "gear_torque_tradeoff" },
    },
  ],
  finalMasteryCheck: {
    id: "gear-final",
    title: "Mastery check",
    type: "gear" as const,
    prompt: "Build a 12:24 ratio again — select the correct driven gear.",
    visualPrompt: "Driver 12T, driven should complete half a turn when driver completes one.",
    data: { driverTeeth: 12, drivenOptions: [18, 24, 30] },
    interaction: "drag_to_place" as const,
    validation: { type: "gear_match" as const, driverTeeth: 12, drivenTeeth: 24 },
    feedback: {
      correct: "12:24 = 1:2 — you can predict rotation from tooth counts alone.",
      incorrect: "Double the driver teeth on the driven gear: 12 × 2 = 24.",
      hint: "Select 24T.",
    },
    masteryTarget: { conceptNodeId: "properties", skill: "gear_mastery" },
  },
} as const;
