/** Visual Problem Engine — ordering & sense-making in measurement (physics). */
export const PHYSICS_MEASUREMENT_LESSON_SEED = {
  id: "lesson-measurement-order-and-sense",
  title: "Measurement: Order & magnitude",
  subject: "Physics",
  topic: "Measurement",
  level: "beginner" as const,
  scenes: [
    {
      id: "phy-1-length-units",
      title: "Largest to smallest",
      type: "segment_select" as const,
      prompt: "Which length unit is the smallest here?",
      visualPrompt: "Paper thickness vs city distances.",
      data: {
        segments: [
          { id: "km", label: "Kilometer" },
          { id: "m", label: "Meter" },
          { id: "cm", label: "Centimeter" },
          { id: "mm", label: "Millimeter" },
        ],
      },
      interaction: "select_choice" as const,
      validation: { type: "choice_match" as const, expectedChoice: "mm" },
      feedback: {
        correct: "Millimeter is finest here — km → m → cm → mm is the staircase down in size.",
        incorrect: "Compare everyday scales: hair and paper live on the smallest common prefix here.",
        hint: "Think: km is for cities, mm is for paper thickness.",
      },
      masteryTarget: { conceptNodeId: "kinematics", skill: "si_length_order" },
    },
    {
      id: "phy-2-lab-sequence",
      title: "Before you heat anything",
      type: "segment_select" as const,
      prompt: "What should happen first before you light a Bunsen burner?",
      visualPrompt: "Professional habit: prep before flame.",
      data: {
        segments: [
          { id: "hair", label: "Tie long hair back" },
          { id: "light", label: "Light the Bunsen burner" },
          { id: "gloves", label: "Put on thermal gloves only" },
          { id: "blanket_only", label: "Locate fire blanket (nothing else)" },
        ],
      },
      interaction: "select_choice" as const,
      validation: { type: "choice_match" as const, expectedChoice: "hair" },
      feedback: {
        correct: "Secure hair (and other prep) before an open flame — then blanket awareness, gloves as needed, ignition last.",
        incorrect: "Lighting first skips preparation; safety checks come before ignition.",
        hint: "Hair and general prep come before the flame.",
      },
      masteryTarget: { conceptNodeId: "kinematics", skill: "lab_safety_sequence" },
    },
    {
      id: "phy-3-number-line",
      title: "Position on a line",
      type: "number_line" as const,
      prompt: "A toy car sits 0.4 m to the right of the sensor. Place 0.4 on the line (meters).",
      visualPrompt: "The axis runs from −1 m to 2 m in steps of 0.2.",
      data: { min: -1, max: 2, step: 0.2 },
      interaction: "place_point" as const,
      validation: {
        type: "point_match" as const,
        expectedPoint: { x: 0.4, y: 0 },
        tolerance: 0.11,
      },
      feedback: {
        correct: "0.4 m is two small ticks past 0 — your placement matches the story.",
        incorrect: "Count two steps of 0.2 after zero to reach 0.4 on the axis.",
        hint: "0.2, then 0.4 — the second tick after zero.",
      },
      masteryTarget: { conceptNodeId: "kinematics", skill: "position_number_line" },
    },
    {
      id: "phy-4-grid-area",
      title: "Rough coverage",
      type: "grid_model" as const,
      prompt: "Shade exactly half of this 2×4 grid (8 cells).",
      visualPrompt: "Half of eight cells means four shaded.",
      data: { rows: 2, columns: 4 },
      interaction: "tap_to_fill" as const,
      validation: { type: "count_match" as const, expectedCount: 4 },
      feedback: {
        correct: "Four of eight cells is one half — a quick visual for ratios in measurement.",
        incorrect: "Count shaded cells; you want four of the eight equal squares.",
        hint: "Try a full 2×2 block on one side — that is four cells.",
      },
      masteryTarget: { conceptNodeId: "kinematics", skill: "ratio_area_model" },
    },
    {
      id: "phy-5-base-unit",
      title: "SI thinking",
      type: "multiple_choice" as const,
      prompt: "Which is a base SI unit for length in science class?",
      visualPrompt: "Pick the standard we build prefixes on.",
      data: { choices: ["meter", "mile", "inch", "foot"] },
      interaction: "select_choice" as const,
      validation: { type: "choice_match" as const, expectedChoice: "meter" },
      feedback: {
        correct: "The meter is the SI base; kilometers and millimeters are prefixes on that same base.",
        incorrect: "Miles, inches, and feet are common, but SI length starts with the meter.",
        hint: "Think of the m in km and mm.",
      },
      masteryTarget: { conceptNodeId: "kinematics", skill: "si_base_units" },
    },
  ],
  finalMasteryCheck: {
    id: "phy-final-prefix",
    title: "Prefix sense",
    type: "segment_select" as const,
    prompt: "Compared with deci-, centi-, and milli-, which represents the largest length factor on the same meter stick?",
    visualPrompt: "Think 1 m vs 0.1 m vs 0.01 m vs 0.001 m.",
    data: {
      segments: [
        { id: "base", label: "Base meter (no prefix)" },
        { id: "deci", label: "deci- (d)" },
        { id: "centi", label: "centi- (c)" },
        { id: "milli", label: "milli- (m)" },
      ],
    },
    interaction: "select_choice" as const,
    validation: { type: "choice_match" as const, expectedChoice: "base" },
    feedback: {
      correct: "The plain meter is the largest step here; deci, centi, milli each divide by ten again.",
      incorrect: "Compare 1 m to 0.1 m to 0.01 m to 0.001 m — the undivided meter is the biggest chunk.",
      hint: "The reference meter (no prefix) is the whole step before prefixes shrink it.",
    },
    masteryTarget: { conceptNodeId: "kinematics", skill: "metric_prefix_order" },
  },
} as const;
