/** Visual Problem Engine — balance scale & equality (math). */
export const MATH_BALANCE_EQUALITY_LESSON_SEED = {
  id: "lesson-balance-scale-equality",
  title: "Balance scale & equality",
  subject: "Algebra",
  topic: "Equality & operations",
  level: "beginner" as const,
  scenes: [
    {
      id: "bal-eq-1-sum-five",
      title: "Make both sides 5",
      type: "balance_scale" as const,
      prompt: "Add weights so the left pan and right pan each total 5.",
      visualPrompt: "The scale tips until both sides match — that is equality.",
      data: { weights: [1, 2, 3, 4, 5] },
      interaction: "drag_to_place" as const,
      validation: { type: "balance_sum" as const, targetSum: 5 },
      feedback: {
        correct: "Both pans at 5 — equal weights, level scale. That is the balance property of equality.",
        incorrect: "Each pan must total exactly 5. Check both sums before you check.",
        hint: "Try 2 + 3 on one side and 5 on the other.",
      },
      masteryTarget: { conceptNodeId: "properties", skill: "balance_equality" },
    },
    {
      id: "bal-eq-2-two-three-five",
      title: "2 + 3 = 5",
      type: "balance_scale" as const,
      prompt: "Place weights so the left pan shows 2 + 3 and the right pan shows 5.",
      visualPrompt: "Same total on both sides — an equation in physical form.",
      data: { weights: [1, 2, 3, 4, 5] },
      interaction: "drag_to_place" as const,
      validation: { type: "balance_match" as const, left: [2, 3], right: [5] },
      feedback: {
        correct: "2 + 3 balances 5 — addition as combining weights.",
        incorrect: "Left needs two weights summing to 5 (like 2 and 3); right needs a single 5.",
        hint: "Put 5 on the right first, then match with 2 and 3 on the left.",
      },
      masteryTarget: { conceptNodeId: "properties", skill: "addition_balance" },
    },
    {
      id: "bal-eq-3-property",
      title: "Name the property",
      type: "multiple_choice" as const,
      prompt: "When both pans hold the same total, which property are you using?",
      visualPrompt: "Think about what stays true when you move equal amounts.",
      data: {
        choices: [
          "Balance / equality of sides",
          "Commutative property only",
          "Order of operations",
          "Negative reciprocals",
        ],
      },
      interaction: "select_choice" as const,
      validation: { type: "choice_match" as const, expectedChoice: "Balance / equality of sides" },
      feedback: {
        correct: "Equal totals on both sides — the same idea behind a = b in algebra.",
        incorrect: "A level scale means both sides have the same value — balance equality.",
        hint: "Which option mentions both sides being the same?",
      },
      masteryTarget: { conceptNodeId: "properties", skill: "equality_property" },
    },
    {
      id: "bal-eq-4-double-four",
      title: "4 + 4 = 8",
      type: "balance_scale" as const,
      prompt: "Balance eight on the right with two equal weights on the left.",
      visualPrompt: "Two identical weights on the left should match one 8 on the right.",
      data: { weights: [1, 2, 3, 4, 5, 8] },
      interaction: "drag_to_place" as const,
      validation: { type: "balance_match" as const, left: [4, 4], right: [8] },
      feedback: {
        correct: "4 + 4 = 8 — repeated equal groups balance a single total.",
        incorrect: "Use two 4-weights on the left and one 8 on the right.",
        hint: "Half of 8 is 4 — put that on each side of the left pan.",
      },
      masteryTarget: { conceptNodeId: "properties", skill: "equal_groups" },
    },
  ],
  finalMasteryCheck: {
    id: "bal-eq-final-six",
    title: "Mastery check",
    type: "balance_scale" as const,
    prompt: "Balance 6 on the right with three weights on the left that also sum to 6.",
    visualPrompt: "Any three weights on the left that total 6 will level the scale.",
    data: { weights: [1, 2, 3, 4, 5, 6] },
    interaction: "drag_to_place" as const,
    validation: { type: "balance_match" as const, left: [1, 2, 3], right: [6] },
    feedback: {
      correct: "1 + 2 + 3 = 6 — three weights balancing one 6. You own the balance model.",
      incorrect: "Left pan needs three weights totaling 6; right pan needs a 6.",
      hint: "Try 1, 2, and 3 on the left.",
    },
    masteryTarget: { conceptNodeId: "properties", skill: "balance_mastery" },
  },
} as const;
