/** Visual Problem Engine — natural selection and adaptation (biology). */
export const BIOLOGY_NATURAL_SELECTION_LESSON_SEED = {
  id: "lesson-natural-selection",
  title: "Natural selection basics",
  subject: "Biology",
  topic: "Evolution",
  level: "beginner" as const,
  scenes: [
    {
      id: "bio-ns-1-variation",
      title: "Variation exists",
      type: "segment_select" as const,
      prompt: "In a population of beetles, some are green and some are brown. What does natural selection act on?",
      visualPrompt: "Selection needs differences to work with.",
      data: {
        segments: [
          { id: "var", label: "Existing heritable variation" },
          { id: "identical", label: "Only identical individuals" },
          { id: "learned", label: "Behaviors learned in one lifetime only" },
          { id: "random", label: "Random mutations created after selection" },
        ],
      },
      interaction: "select_choice" as const,
      validation: { type: "choice_match" as const, expectedChoice: "var" },
      feedback: {
        correct: "Heritable variation — different traits already present in the population.",
        incorrect: "Selection can't favor differences that don't exist or aren't inherited.",
        hint: "Darwin's first requirement: variation in a population.",
      },
      masteryTarget: { conceptNodeId: "evolution-natural-selection", skill: "variation_prerequisite" },
    },
    {
      id: "bio-ns-2-steps",
      title: "Selection sequence",
      type: "drag_drop_sort" as const,
      prompt: "Order the classic steps of natural selection.",
      visualPrompt: "Variation → struggle → differential survival → change over generations.",
      data: {
        items: [
          "Individuals with advantageous traits survive and reproduce more",
          "Over generations, allele frequencies shift in the population",
          "More offspring are produced than the environment can support",
          "Heritable variation exists in the population",
        ],
      },
      interaction: "reorder" as const,
      validation: {
        type: "ordered_sequence" as const,
        expectedOrder: [
          "Heritable variation exists in the population",
          "More offspring are produced than the environment can support",
          "Individuals with advantageous traits survive and reproduce more",
          "Over generations, allele frequencies shift in the population",
        ],
      },
      feedback: {
        correct: "Variation → overproduction → differential survival → evolution — Darwin's logic.",
        incorrect: "You need variation and competition before traits spread across generations.",
        hint: "What must exist before any selection can happen?",
      },
      masteryTarget: { conceptNodeId: "evolution-natural-selection", skill: "selection_steps_order" },
    },
    {
      id: "bio-ns-3-beetle-grid",
      title: "Camouflage model",
      type: "grid_model" as const,
      prompt: "On a brown forest floor, brown beetles blend in. In a 2×4 grid of 'habitat patches,' shade exactly 3 cells to show '3 brown beetles hidden, 1 green visible'.",
      visualPrompt: "Three hidden (shaded), one conspicuous (leave one cell empty among four).",
      data: { rows: 2, columns: 4 },
      interaction: "tap_to_fill" as const,
      validation: { type: "count_match" as const, expectedCount: 3 },
      feedback: {
        correct: "Three of four — most beetles camouflaged, one stands out to predators.",
        incorrect: "Shade exactly three cells for the camouflaged majority.",
        hint: "Leave one cell unshaded for the conspicuous green beetle.",
      },
      masteryTarget: { conceptNodeId: "evolution-natural-selection", skill: "camouflage_model" },
    },
    {
      id: "bio-ns-4-fitness-bar",
      title: "Relative fitness",
      type: "fraction_bar" as const,
      prompt: "If brown beetles produce 6 offspring per adult and green beetles produce 2, brown fitness is 3× higher. Shade 3 of 4 parts to model 'three quarters of the next generation from brown parents'.",
      visualPrompt: "Three of four parts shaded.",
      data: { totalParts: 4 },
      interaction: "tap_to_fill" as const,
      validation: { type: "count_match" as const, expectedCount: 3 },
      feedback: {
        correct: "3/4 — brown beetles dominate reproduction in this toy model.",
        incorrect: "Shade three of the four equal slices.",
        hint: "Higher fitness → larger share of offspring.",
      },
      masteryTarget: { conceptNodeId: "evolution-natural-selection", skill: "relative_fitness_model" },
    },
    {
      id: "bio-ns-5-generation-line",
      title: "Generations",
      type: "number_line" as const,
      prompt: "Meaningful allele-frequency shifts usually take many generations. Mark generation 10 on this timeline (0–20, step 2).",
      visualPrompt: "Evolution is gradual over time.",
      data: { min: 0, max: 20, step: 2 },
      interaction: "place_point" as const,
      validation: {
        type: "point_match" as const,
        expectedPoint: { x: 10, y: 0 },
        tolerance: 0.5,
      },
      feedback: {
        correct: "Generation 10 — selection acts over many reproductive cycles, not one.",
        incorrect: "The fifth tick at step 2 is generation 10.",
        hint: "Count five steps of 2 from zero.",
      },
      masteryTarget: { conceptNodeId: "evolution-natural-selection", skill: "generations_timeline" },
    },
  ],
  finalMasteryCheck: {
    id: "bio-ns-final-definition",
    title: "Define the process",
    type: "segment_select" as const,
    prompt: "Which best describes natural selection?",
    visualPrompt: "Not goal-directed — environment filters variation.",
    data: {
      segments: [
        { id: "correct", label: "Environment favors certain heritable traits → they become more common" },
        { id: "goal", label: "Organisms choose traits they need and develop them intentionally" },
        { id: "individual", label: "Individual organisms evolve during their lifetime" },
        { id: "random", label: "Purely random change with no relation to survival" },
      ],
    },
    interaction: "select_choice" as const,
    validation: { type: "choice_match" as const, expectedChoice: "correct" },
    feedback: {
      correct: "Heritable advantage + reproduction → population change over time.",
      incorrect: "Selection is not intentional; populations change, not individuals mid-life.",
      hint: "Think 'differential reproductive success' not 'trying to adapt'.",
    },
    masteryTarget: { conceptNodeId: "evolution-natural-selection", skill: "natural_selection_definition" },
  },
} as const;
