/** Visual Problem Engine — one-step equations on a balance scale (math). */
export const MATH_BALANCE_EQUATIONS_LESSON_SEED = {
  id: "lesson-balance-one-step-equations",
  title: "One-step equations on a balance",
  subject: "Math",
  topic: "Linear equations",
  level: "beginner" as const,
  scenes: [
    {
      id: "bal-eq-x-1-plus-three",
      title: "x + 3 = 7",
      type: "balance_scale" as const,
      prompt: "The left pan already has 3. Add the missing weight so it balances 7 on the right.",
      visualPrompt: "What weight plus 3 makes 7? That weight is x.",
      data: { weights: [1, 2, 3, 4, 5, 7], fixedLeft: [3], fixedRight: [7] },
      interaction: "drag_to_place" as const,
      validation: { type: "balance_match" as const, left: [3, 4], right: [7] },
      feedback: {
        correct: "3 + 4 = 7, so x = 4. Adding the same to both sides keeps balance.",
        incorrect: "You need one more weight on the left so 3 + ? = 7.",
        hint: "7 − 3 = 4 — place a 4-weight on the left.",
      },
      masteryTarget: { conceptNodeId: "linear-equations", skill: "balance_addition_equation" },
    },
    {
      id: "bal-eq-x-2-name-x",
      title: "Name x",
      type: "multiple_choice" as const,
      prompt: "In x + 3 = 7, what is the value of x?",
      visualPrompt: "Use the balance you just built.",
      data: { choices: ["4", "3", "7", "10"] },
      interaction: "select_choice" as const,
      validation: { type: "choice_match" as const, expectedChoice: "4" },
      feedback: {
        correct: "x = 4 — the missing weight that completed the balance.",
        incorrect: "Subtract 3 from both sides: x = 7 − 3.",
        hint: "What did you add to the 3 on the left?",
      },
      masteryTarget: { conceptNodeId: "linear-equations", skill: "solve_x_addition" },
    },
    {
      id: "bal-eq-x-3-plus-five",
      title: "x + 5 = 12",
      type: "balance_scale" as const,
      prompt: "5 is fixed on the left. Find x so the scale balances 12 on the right.",
      visualPrompt: "Same idea — one unknown weight on the left.",
      data: { weights: [1, 2, 3, 4, 5, 6, 7, 12], fixedLeft: [5], fixedRight: [12] },
      interaction: "drag_to_place" as const,
      validation: { type: "balance_match" as const, left: [5, 7], right: [12] },
      feedback: {
        correct: "5 + 7 = 12, so x = 7.",
        incorrect: "Add the weight that makes 5 + ? = 12.",
        hint: "12 − 5 = 7.",
      },
      masteryTarget: { conceptNodeId: "linear-equations", skill: "balance_subtraction_inverse" },
    },
    {
      id: "bal-eq-x-4-two-x",
      title: "2x = 8",
      type: "balance_scale" as const,
      prompt: "Balance 8 on the right with two equal weights on the left (that is 2x).",
      visualPrompt: "Two identical unknowns on the left, 8 on the right.",
      data: { weights: [1, 2, 3, 4, 5, 8] },
      interaction: "drag_to_place" as const,
      validation: { type: "balance_match" as const, left: [4, 4], right: [8] },
      feedback: {
        correct: "Two 4-weights balance 8 — 2x = 8 so x = 4.",
        incorrect: "Put two equal weights on the left that sum to 8.",
        hint: "Split 8 into two equal parts: 4 and 4.",
      },
      masteryTarget: { conceptNodeId: "linear-equations", skill: "balance_multiplication" },
    },
  ],
  finalMasteryCheck: {
    id: "bal-eq-x-final",
    title: "Mastery check",
    type: "balance_scale" as const,
    prompt: "Solve 3 + x = 11 using the scale. Fixed 3 on the left, 11 on the right.",
    visualPrompt: "Add x to complete the balance.",
    data: { weights: [1, 2, 3, 4, 5, 6, 7, 8, 11], fixedLeft: [3], fixedRight: [11] },
    interaction: "drag_to_place" as const,
    validation: { type: "balance_match" as const, left: [3, 8], right: [11] },
    feedback: {
      correct: "3 + 8 = 11, so x = 8. You can read equations directly from a level scale.",
      incorrect: "Find the weight w so 3 + w = 11.",
      hint: "11 − 3 = 8.",
    },
    masteryTarget: { conceptNodeId: "linear-equations", skill: "balance_equation_mastery" },
  },
} as const;
