import {
  balanceScene,
  eliminationLesson,
  lesson,
  mcScene,
  substitutionLesson,
  sortScene,
} from "./_helpers";

export const MATH_ALGEBRA_LEVEL_8_SEEDS = [
  lesson(
    8,
    "systems-with-scales",
    "Systems with Scales",
    "intermediate",
    [
      balanceScene(
        "l8-sys-1",
        "Two equations",
        "Scale 1: x + y = 5. If x = 2, place weights so y = 3 balances.",
        { weights: [1, 2, 3, 4, 5], fixedLeft: [2], fixedRight: [5], left: [2, 3], right: [5] },
        "systems_scale_1",
        { correct: "2 + 3 = 5.", incorrect: "y = 3.", hint: "5 − 2." },
      ),
      mcScene(
        "l8-sys-2",
        "System",
        "Two equations, two unknowns — a ___ of equations.",
        ["System", "Single", "Fraction", "Inequality only"],
        "System",
        "systems_scale_2",
        { correct: "System of equations.", incorrect: "Two constraints together.", hint: "System." },
      ),
      balanceScene(
        "l8-sys-3",
        "Second scale",
        "x − y = 1 with x = 2 → y = ? Balance 2 on left, 1 on right with y=1.",
        { weights: [1, 2, 3], fixedLeft: [2], fixedRight: [1], left: [2], right: [1, 1] },
        "systems_scale_3",
        { correct: "2 − 1 = 1.", incorrect: "y = 1.", hint: "2 − y = 1." },
      ),
    ],
    mcScene(
      "l8-sys-final",
      "Mastery check",
      "x + y = 5 and x = 2 → y = ?",
      ["3", "2", "5", "7"],
      "3",
      "systems_scale_mastery",
      { correct: "y = 3.", incorrect: "Substitute x = 2.", hint: "5 − 2." },
    ),
  ),
  substitutionLesson(8, "balancing-with-substitution", "Balancing with Substitution", "y = 2x", 4, "2x + y = 12", 4),
  lesson(
    8,
    "writing-systems-of-equations",
    "Writing Systems of Equations",
    "intermediate",
    [
      mcScene(
        "l8-wrt-1",
        "From words",
        "Apples a and oranges o: a + o = 10 and a = o + 2. This is a…",
        ["System", "One equation", "Inequality", "No variables"],
        "System",
        "write_system_1",
        { correct: "Two equations, two unknowns.", incorrect: "Two constraints.", hint: "System." },
      ),
      mcScene(
        "l8-wrt-2",
        "Define variables",
        "First step writing a system?",
        ["Define variables", "Eliminate x", "Graph only", "Guess"],
        "Define variables",
        "write_system_2",
        { correct: "Name what x and y represent.", incorrect: "Variables first.", hint: "Define." },
      ),
      sortScene(
        "l8-wrt-3",
        "Model steps",
        "Order: define → write equations → solve.",
        ["Solve the system", "Assign variables", "Write two equations", "Check in context"],
        ["Assign variables", "Write two equations", "Solve the system", "Check in context"],
        "write_system_3",
        {
          correct: "Model before solve.",
          incorrect: "Variables first.",
          hint: "Define first.",
        },
      ),
    ],
    mcScene(
      "l8-wrt-final",
      "Mastery check",
      "x + y = 8 and y = x + 2 is a system with ___ equations.",
      ["2", "1", "3", "0"],
      "2",
      "write_system_mastery",
      { correct: "Two equations.", incorrect: "Count equations.", hint: "2." },
    ),
  ),
  substitutionLesson(8, "substituting-groups", "Substituting Groups", "y = x + 2", 3, "x + y = 9", 6),
  substitutionLesson(8, "isolating-and-substituting", "Isolating and Substituting", "y = 3x", 2, "y + x = 10", 8),
  substitutionLesson(8, "substitution-strategy", "Substitution Strategy", "y = 5 − x", 2, "2x + y = 8", 6),
] as const;

export const MATH_ALGEBRA_LEVEL_9_SEEDS = [
  eliminationLesson(9, "subtracting-scales", "Subtracting Scales"),
  eliminationLesson(9, "elimination", "Elimination"),
  lesson(
    9,
    "multiplying-to-eliminate",
    "Multiplying to Eliminate",
    "intermediate",
    [
      mcScene(
        "l9-mul-1",
        "Why multiply",
        "2x + y = 7 and 4x + 3y = 15 — multiply first equation by −2 to eliminate…",
        ["x", "y", "Both", "Neither"],
        "x",
        "elim_mult_1",
        { correct: "Align x coefficients to eliminate x.", incorrect: "Make x terms opposites.", hint: "x." },
      ),
      mcScene(
        "l9-mul-2",
        "After multiply",
        "Multiply 2x + y = 7 by 2 →",
        ["4x + 2y = 14", "4x + y = 14", "2x + 2y = 7", "x + 2y = 14"],
        "4x + 2y = 14",
        "elim_mult_2",
        { correct: "Every term × 2.", incorrect: "2(2x + y = 7).", hint: "Distribute 2." },
      ),
      sortScene(
        "l9-mul-3",
        "Elimination with multiply",
        "Order: multiply → add equations → solve.",
        ["Solve for y", "Add equations", "Multiply to match coefficients", "Original system"],
        ["Original system", "Multiply to match coefficients", "Add equations", "Solve for y"],
        "elim_mult_3",
        {
          correct: "Scale an equation before eliminating.",
          incorrect: "Match coefficients first.",
          hint: "Multiply before add.",
        },
      ),
    ],
    mcScene(
      "l9-mul-final",
      "Mastery check",
      "To eliminate x, you sometimes ___ an equation first.",
      ["Multiply", "Add 1", "Graph", "Factor only"],
      "Multiply",
      "elim_mult_mastery",
      { correct: "Scale to match coefficients.", incorrect: "Multiply to align.", hint: "Multiply." },
    ),
  ),
] as const;
