import {
  balanceScene,
  graphScene,
  inequalityLesson,
  lesson,
  mcScene,
  nlScene,
  segScene,
} from "./_helpers";

export const MATH_ALGEBRA_LEVEL_6_SEEDS = [
  lesson(
    6,
    "unbalanced-scales",
    "Unbalanced Scales",
    "intermediate",
    [
      mcScene(
        "l6-unb-1",
        "Not equal",
        "Left pan 5, right pan 3. Which symbol fits?",
        ["5 > 3", "5 < 3", "5 = 3", "5 ≥ 3 only"],
        "5 > 3",
        "unbalanced_read",
        {
          correct: "Left is heavier — 5 > 3.",
          incorrect: "Unequal pans mean > or <.",
          hint: "More weight on the left.",
        },
      ),
      mcScene(
        "l6-unb-2",
        "Inequality meaning",
        "x + 2 > 10 means the left side is…",
        ["Greater than 10", "Equal to 10", "Less than 10", "Exactly 2"],
        "Greater than 10",
        "unbalanced_meaning",
        {
          correct: "> — left expression exceeds 10.",
          incorrect: "Tilted to the left on a scale metaphor.",
          hint: "Greater than.",
        },
      ),
      segScene(
        "l6-unb-3",
        "Write it",
        "x + 2 is less than 10.",
        [
          { id: "lt", label: "x + 2 < 10" },
          { id: "gt", label: "x + 2 > 10" },
          { id: "eq", label: "x + 2 = 10" },
        ],
        "lt",
        "unbalanced_symbol",
        { correct: "Less than → <.", incorrect: "Smaller than 10.", hint: "< symbol." },
      ),
    ],
    mcScene(
      "l6-unb-final",
      "Mastery check",
      "3x > 12 means x is…",
      ["Greater than 4", "Less than 4", "Equal to 4", "Less than 12"],
      "Greater than 4",
      "unbalanced_mastery",
      { correct: "x > 4.", incorrect: "Divide by 3.", hint: "3x > 12." },
    ),
  ),
  inequalityLesson(6, "inequalities-both-ways", "Inequalities Both Ways", 2, "lt"),
  lesson(
    6,
    "balancing-scales",
    "Balancing Scales",
    "intermediate",
    [
      balanceScene(
        "l6-bal-1",
        "Equal pans",
        "Balance x + 4 = 10 on the scale.",
        { weights: [1, 2, 3, 4, 6, 10], fixedLeft: [4], fixedRight: [10], left: [4, 6], right: [10] },
        "ineq_balance_1",
        { correct: "x = 6.", incorrect: "6 + 4 = 10.", hint: "10 − 4." },
      ),
      mcScene(
        "l6-bal-2",
        "Equal vs unequal",
        "Level scale → = ; tilted scale → …",
        ["< or >", "Only +", "Always 0", "No symbol"],
        "< or >",
        "ineq_balance_2",
        { correct: "Tilt models inequality.", incorrect: "Unequal totals.", hint: "Not balanced." },
      ),
      mcScene(
        "l6-bal-3",
        "Add to both",
        "If a > b, then a + 3 ___ b + 3.",
        [">", "<", "=", "≤"],
        ">",
        "ineq_balance_3",
        { correct: "Order preserved.", incorrect: "Same addition both sides.", hint: "Still greater." },
      ),
    ],
    balanceScene(
      "l6-bal-final",
      "Mastery check",
      "x + 5 = 14 on the scale.",
      { weights: [1, 2, 3, 5, 9, 14], fixedLeft: [5], fixedRight: [14], left: [5, 9], right: [14] },
      "ineq_balance_mastery",
      { correct: "x = 9.", incorrect: "14 − 5.", hint: "Place 9." },
    ),
  ),
  inequalityLesson(6, "solutions-to-inequalities", "Solutions to Inequalities", 5, "gt"),
  lesson(
    6,
    "graphing-inequalities",
    "Graphing Inequalities",
    "intermediate",
    [
      graphScene(
        "l6-gi-1",
        "Line point",
        "Place (2, 5) on y = x + 3.",
        2,
        5,
        "graph_ineq_1",
        { correct: "(2, 5) on the line.", incorrect: "2 + 3 = 5.", hint: "x=2, y=5." },
      ),
      mcScene(
        "l6-gi-2",
        "Half-plane",
        "y > x + 1 shades…",
        ["Above the line", "Below the line", "Only on the line", "Nowhere"],
        "Above the line",
        "graph_ineq_2",
        { correct: "Greater y → above.", incorrect: "> means higher y.", hint: "Above." },
      ),
      nlScene(
        "l6-gi-3",
        "Number line",
        "Mark boundary x = 3 for x > 3.",
        -2,
        8,
        1,
        3,
        "graph_ineq_3",
        { correct: "Boundary 3.", incorrect: "Mark 3.", hint: "Cutoff." },
      ),
    ],
    mcScene(
      "l6-gi-final",
      "Mastery check",
      "x ≥ 2 includes…",
      ["2", "1", "0", "−1"],
      "2",
      "graph_ineq_mastery",
      { correct: "≥ includes boundary.", incorrect: "2 works.", hint: "Equal ok." },
    ),
  ),
  lesson(
    6,
    "graphing-solutions",
    "Graphing Solutions",
    "intermediate",
    [
      nlScene(
        "l6-gs-1",
        "Boundary",
        "Mark x = 4 for x < 4.",
        -2,
        10,
        1,
        4,
        "graph_sol_1",
        { correct: "Boundary 4.", incorrect: "Mark 4.", hint: "Cutoff." },
      ),
      mcScene(
        "l6-gs-2",
        "Test",
        "Which satisfies x < 4?",
        ["3", "4", "5", "6"],
        "3",
        "graph_sol_2",
        { correct: "3 < 4.", incorrect: "Strict <.", hint: "Less than 4." },
      ),
      segScene(
        "l6-gs-3",
        "Open circle",
        "x < 4 uses a(n) ___ circle at 4.",
        [
          { id: "open", label: "Open" },
          { id: "closed", label: "Closed" },
          { id: "none", label: "None" },
        ],
        "open",
        "graph_sol_3",
        { correct: "Strict → open.", incorrect: "4 not included.", hint: "Open." },
      ),
    ],
    mcScene(
      "l6-gs-final",
      "Mastery check",
      "Which satisfies x > 1?",
      ["2", "1", "0", "−1"],
      "2",
      "graph_sol_mastery",
      { correct: "2 > 1.", incorrect: "Right of 1.", hint: "Greater." },
    ),
  ),
] as const;
