import {
  balanceAddLesson,
  balanceMultLesson,
  balanceScene,
  balanceTwoStepLesson,
  lesson,
  mcScene,
} from "./_helpers";

export const MATH_ALGEBRA_LEVEL_10_SEEDS = [
  balanceTwoStepLesson(10, "balancing-with-variables", "Balancing with Variables", 2, 1, 9),
  balanceAddLesson(10, "balancing-with-constants", "Balancing with Constants", 5, 12),
  lesson(
    10,
    "balancing-with-two-variables",
    "Balancing with Two Variables",
    "intermediate",
    [
      balanceScene(
        "l10-2v-1",
        "x and y",
        "x + y = 6 with x = 2. Add y on the left to balance 6.",
        { weights: [1, 2, 3, 4, 6], fixedLeft: [2], fixedRight: [6], left: [2, 4], right: [6] },
        "bal_2var_1",
        { correct: "y = 4.", incorrect: "2 + 4 = 6.", hint: "6 − 2." },
      ),
      mcScene(
        "l10-2v-2",
        "Two unknowns",
        "Two unknowns typically need ___ independent equations.",
        ["2", "1", "0", "4"],
        "2",
        "bal_2var_2",
        { correct: "Two constraints.", incorrect: "System size.", hint: "2." },
      ),
      balanceScene(
        "l10-2v-3",
        "Difference",
        "x − y = 2 with x = 5.",
        { weights: [1, 2, 3, 5], fixedLeft: [5], fixedRight: [2], left: [5], right: [3, 2] },
        "bal_2var_3",
        { correct: "y = 3.", incorrect: "5 − 3 = 2.", hint: "5 − y = 2." },
      ),
    ],
    mcScene(
      "l10-2v-final",
      "Mastery check",
      "x + y = 10, x = 6 → y = ?",
      ["4", "6", "10", "16"],
      "4",
      "bal_2var_mastery",
      { correct: "y = 4.", incorrect: "10 − 6.", hint: "4." },
    ),
  ),
  balanceTwoStepLesson(10, "balancing-with-equations", "Balancing with Equations", 3, 2, 17),
  balanceMultLesson(10, "balancing-with-unknown-weights", "Balancing with Unknown Weights", 4, 20),
  lesson(
    10,
    "building-tilted-scales",
    "Building Tilted Scales",
    "intermediate",
    [
      mcScene(
        "l10-tilt-1",
        "Tilt direction",
        "Left 7, right 4 — the scale tilts…",
        ["Toward the left (heavier)", "Toward the right", "Stays level", "Both up"],
        "Toward the left (heavier)",
        "tilt_1",
        { correct: "Left heavier.", incorrect: "7 > 4.", hint: "Left down." },
      ),
      mcScene(
        "l10-tilt-2",
        "Symbol",
        "7 vs 4 tilted left means 7 ___ 4.",
        [">", "<", "=", "≥ only"],
        ">",
        "tilt_2",
        { correct: "7 > 4.", incorrect: "Heavier side lower.", hint: ">" },
      ),
      mcScene(
        "l10-tilt-3",
        "Rebalance",
        "Add 3 to the right: 4 + 3 = 7. Pans are now…",
        ["Equal (=)", "Still left heavy", "Right heavy", "Empty"],
        "Equal (=)",
        "tilt_3",
        { correct: "7 = 7 balanced.", incorrect: "Equal totals.", hint: "Level." },
      ),
    ],
    mcScene(
      "l10-tilt-final",
      "Mastery check",
      "A tilted scale models an…",
      ["Inequality", "Identity", "Fraction", "Area"],
      "Inequality",
      "tilt_mastery",
      { correct: "Unequal → inequality.", incorrect: "Not balanced.", hint: "Inequality." },
    ),
  ),
] as const;
