import { inequalityLesson, lesson, mcScene, nlScene, segScene, sortScene } from "./_helpers";

export const MATH_ALGEBRA_LEVEL_7_SEEDS = [
  inequalityLesson(7, "finding-the-boundary", "Finding the Boundary", 3, "gt"),
  lesson(
    7,
    "solving-inequalities",
    "Solving Inequalities",
    "intermediate",
    [
      sortScene(
        "l7-si-1",
        "Solve 2x + 3 > 9",
        "Order the steps.",
        ["2x > 6", "Subtract 3", "x > 3", "2x + 3 > 9"],
        ["2x + 3 > 9", "Subtract 3", "2x > 6", "x > 3"],
        "solve_ineq_steps",
        {
          correct: "Same as equations — flip sign if × negative.",
          incorrect: "Subtract 3 first.",
          hint: "Undo +3.",
        },
      ),
      mcScene(
        "l7-si-2",
        "Solution",
        "2x + 3 > 9 → x > ?",
        ["3", "6", "9", "12"],
        "3",
        "solve_ineq_1",
        { correct: "x > 3.", incorrect: "2x > 6.", hint: "Divide by 2." },
      ),
      mcScene(
        "l7-si-3",
        "Flip rule",
        "Multiplying both sides by −1 ___ the inequality sign.",
        ["Flips", "Keeps", "Removes", "Doubles"],
        "Flips",
        "solve_ineq_flip",
        { correct: "> becomes < when ×(−1).", incorrect: "Negative reverses order.", hint: "Flip." },
      ),
    ],
    mcScene(
      "l7-si-final",
      "Mastery check",
      "−2x > 8 → x ___ ?",
      ["< −4", "> −4", "< 4", "> 4"],
      "< −4",
      "solve_ineq_mastery",
      { correct: "x < −4 (sign flipped).", incorrect: "Divide by −2, flip.", hint: "Flip > to <." },
    ),
  ),
  lesson(
    7,
    "including-the-boundary",
    "Including the Boundary",
    "intermediate",
    [
      segScene(
        "l7-inc-1",
        "≥ vs >",
        "x ≥ 5 includes x = 5?",
        [
          { id: "yes", label: "Yes" },
          { id: "no", label: "No" },
        ],
        "yes",
        "include_boundary_1",
        { correct: "≥ includes 5.", incorrect: "Or-equal includes boundary.", hint: "Yes." },
      ),
      mcScene(
        "l7-inc-2",
        "Closed circle",
        "A closed circle on the graph means…",
        ["The boundary is included", "The boundary is excluded", "No solutions", "x = 0"],
        "The boundary is included",
        "include_boundary_2",
        { correct: "Closed = included.", incorrect: "≤ or ≥ use closed dots.", hint: "Included." },
      ),
      nlScene(
        "l7-inc-3",
        "Mark ≥",
        "Mark boundary 5 for x ≥ 5.",
        0,
        10,
        1,
        5,
        "include_boundary_3",
        { correct: "Boundary 5.", incorrect: "Mark 5.", hint: "At 5." },
      ),
    ],
    mcScene(
      "l7-inc-final",
      "Mastery check",
      "Which satisfies x ≥ 5?",
      ["5", "4", "3", "2"],
      "5",
      "include_boundary_mastery",
      { correct: "5 satisfies ≥.", incorrect: "Equal allowed.", hint: "5 works." },
    ),
  ),
  lesson(
    7,
    "writing-inequalities",
    "Writing Inequalities",
    "intermediate",
    [
      mcScene(
        "l7-wri-1",
        "At most",
        "‘x is at most 7’ means…",
        ["x ≤ 7", "x ≥ 7", "x < 7", "x = 7 only"],
        "x ≤ 7",
        "write_ineq_1",
        { correct: "At most → ≤.", incorrect: "Includes 7.", hint: "≤." },
      ),
      mcScene(
        "l7-wri-2",
        "At least",
        "‘At least 3’ →",
        ["x ≥ 3", "x ≤ 3", "x > 3 only", "x = 3 only"],
        "x ≥ 3",
        "write_ineq_2",
        { correct: "≥ 3.", incorrect: "Minimum 3.", hint: "≥." },
      ),
      mcScene(
        "l7-wri-3",
        "Context",
        "You need more than 10 points: p ___ 10.",
        [">", "<", "≥", "="],
        ">",
        "write_ineq_3",
        { correct: "p > 10.", incorrect: "More than → >.", hint: "Strict >." },
      ),
    ],
    mcScene(
      "l7-wri-final",
      "Mastery check",
      "‘No more than 8’ →",
      ["x ≤ 8", "x ≥ 8", "x < 8", "x > 8"],
      "x ≤ 8",
      "write_ineq_mastery",
      { correct: "≤ 8.", incorrect: "Cap at 8.", hint: "≤." },
    ),
  ),
  lesson(
    7,
    "negations",
    "Negations",
    "intermediate",
    [
      mcScene(
        "l7-neg-1",
        "Not >",
        "The negation of x > 3 is…",
        ["x ≤ 3", "x ≥ 3", "x < 3", "x = 3"],
        "x ≤ 3",
        "negation_1",
        { correct: "NOT (x > 3) ↔ x ≤ 3.", incorrect: "Flip to ≤.", hint: "Opposite." },
      ),
      mcScene(
        "l7-neg-2",
        "Not ≤",
        "Negation of x ≤ 5?",
        ["x > 5", "x < 5", "x ≥ 5", "x = 5"],
        "x > 5",
        "negation_2",
        { correct: "x > 5.", incorrect: "Strict >.", hint: "Not ≤." },
      ),
      segScene(
        "l7-neg-3",
        "Interval",
        "Solution to NOT (x < 2)?",
        [
          { id: "a", label: "x ≥ 2" },
          { id: "b", label: "x ≤ 2" },
          { id: "c", label: "x = 2 only" },
        ],
        "a",
        "negation_3",
        { correct: "x ≥ 2.", incorrect: "Not less than 2.", hint: "≥ 2." },
      ),
    ],
    mcScene(
      "l7-neg-final",
      "Mastery check",
      "Negation of x ≥ 1?",
      ["x < 1", "x ≤ 1", "x > 1", "x = 1"],
      "x < 1",
      "negation_mastery",
      { correct: "x < 1.", incorrect: "Strict less.", hint: "Not ≥." },
    ),
  ),
  lesson(
    7,
    "putting-it-all-together",
    "Putting It All Together",
    "intermediate",
    [
      sortScene(
        "l7-all-1",
        "Full pipeline",
        "Order: translate → solve → graph → test.",
        ["Test a value", "Write inequality", "Solve", "Graph boundary"],
        ["Write inequality", "Solve", "Graph boundary", "Test a value"],
        "ineq_pipeline",
        {
          correct: "Word → symbol → solution → graph.",
          incorrect: "Start from the story.",
          hint: "Write first.",
        },
      ),
      mcScene(
        "l7-all-2",
        "Story",
        "Score must exceed 80: s ___ 80.",
        [">", "≥", "<", "≤"],
        ">",
        "ineq_story",
        { correct: "s > 80.", incorrect: "Exceed → >.", hint: "Strict." },
      ),
      mcScene(
        "l7-all-3",
        "Check",
        "s > 80 — does 85 work?",
        ["Yes", "No", "Only if s ≤ 80", "Cannot tell"],
        "Yes",
        "ineq_check",
        { correct: "85 > 80.", incorrect: "Test in solution set.", hint: "Yes." },
      ),
    ],
    mcScene(
      "l7-all-final",
      "Mastery check",
      "3x − 2 ≤ 10 → x ≤ ?",
      ["4", "3", "6", "12"],
      "4",
      "ineq_all_mastery",
      { correct: "3x ≤ 12 → x ≤ 4.", incorrect: "Add 2, divide 3.", hint: "x ≤ 4." },
    ),
  ),
] as const;
