import { lesson, mcScene, matchScene, reasoningLesson, balanceScene } from "./_helpers";

export const MATH_ALGEBRA_LEVEL_11_SEEDS = [
  reasoningLesson(11, "reasoning-about-weights", "Reasoning about Weights", "intermediate"),
  lesson(
    11,
    "more-reasoning-about-weights",
    "More Reasoning about Weights",
    "intermediate",
    [
      balanceScene(
        "l11-mrw-1",
        "Compare",
        "Left: 3 + x. Right: 10. If x = 7, balanced?",
        { weights: [1, 3, 7, 10], fixedLeft: [3], fixedRight: [10], left: [3, 7], right: [10] },
        "reason_weight_1",
        { correct: "3 + 7 = 10.", incorrect: "x = 7.", hint: "10 − 3." },
      ),
      mcScene(
        "l11-mrw-2",
        "Without solving",
        "If 2x + 1 = 2x + 3, how many solutions?",
        ["0", "1", "2", "Infinite"],
        "0",
        "reason_weight_2",
        { correct: "1 ≠ 3 — never true.", incorrect: "Contradiction.", hint: "0." },
      ),
      matchScene(
        "l11-mrw-3",
        "Heavier side",
        "Match: 5 + x vs 3 + x + 1.",
        [
          { id: "a", label: "Left heavier" },
          { id: "b", label: "Right heavier" },
          { id: "c", label: "Always equal" },
        ],
        [{ id: "cmp", label: "5 + x vs 4 + x" }],
        { cmp: "a" },
        "reason_weight_3",
        { correct: "5 + x > 4 + x.", incorrect: "5 > 4.", hint: "Left heavier." },
      ),
    ],
    mcScene(
      "l11-mrw-final",
      "Mastery check",
      "Same x on both sides cancels — removes x from…",
      ["Both sides equally", "Left only", "Right only", "Neither"],
      "Both sides equally",
      "reason_weight_mastery",
      { correct: "Subtract x from both.", incorrect: "Cancellation.", hint: "Both sides." },
    ),
  ),
  lesson(
    11,
    "strategic-comparisons",
    "Strategic Comparisons",
    "intermediate",
    [
      mcScene(
        "l11-str-1",
        "Compare",
        "Without full solve: 3x + 2 vs 2x + 5 when x = 4?",
        ["3(4)+2 > 2(4)+5", "Left smaller", "Equal", "Cannot compare"],
        "3(4)+2 > 2(4)+5",
        "strategic_cmp_1",
        { correct: "14 > 13.", incorrect: "Plug x = 4.", hint: "14 vs 13." },
      ),
      mcScene(
        "l11-str-2",
        "Difference",
        "Subtract 2x from both: x + 2 vs 5 → x vs ?",
        ["3", "5", "2", "7"],
        "3",
        "strategic_cmp_2",
        { correct: "x = 3.", incorrect: "5 − 2.", hint: "3." },
      ),
      mcScene(
        "l11-str-3",
        "Strategy",
        "Remove equal weights from both pans…",
        ["Keeps balance / order", "Changes x", "Always false", "Eliminates x always"],
        "Keeps balance / order",
        "strategic_cmp_3",
        { correct: "Same removal preserves relation.", incorrect: "Balance property.", hint: "Preserves." },
      ),
    ],
    mcScene(
      "l11-str-final",
      "Mastery check",
      "If a + 2 = b + 2 then a ___ b.",
      ["=", "<", ">", "≥"],
      "=",
      "strategic_cmp_mastery",
      { correct: "Cancel 2: a = b.", incorrect: "Subtract 2.", hint: "Equal." },
    ),
  ),
  lesson(
    11,
    "reasoning-about-two-scales",
    "Reasoning about Two Scales",
    "intermediate",
    [
      mcScene(
        "l11-2s-1",
        "Two scales",
        "Scale A: x = 3. Scale B: x + y = 8. y = ?",
        ["5", "3", "8", "11"],
        "5",
        "reason_2scale_1",
        { correct: "y = 5.", incorrect: "8 − 3.", hint: "5." },
      ),
      balanceScene(
        "l11-2s-2",
        "Match scales",
        "If scale 1 has x=4 and scale 2 needs x+y=9, y=5.",
        { weights: [1, 4, 5, 9], fixedLeft: [4], fixedRight: [9], left: [4, 5], right: [9] },
        "reason_2scale_2",
        { correct: "4 + 5 = 9.", incorrect: "y = 5.", hint: "9 − 4." },
      ),
      mcScene(
        "l11-2s-3",
        "Consistency",
        "Two scales must agree on…",
        ["Shared unknowns", "Color only", "Pan size", "Nothing"],
        "Shared unknowns",
        "reason_2scale_3",
        { correct: "Same x has one value.", incorrect: "Consistent system.", hint: "Shared x." },
      ),
    ],
    mcScene(
      "l11-2s-final",
      "Mastery check",
      "x + y = 7 and x = 2 on two scales → y = ?",
      ["5", "2", "7", "9"],
      "5",
      "reason_2scale_mastery",
      { correct: "y = 5.", incorrect: "7 − 2.", hint: "5." },
    ),
  ),
  reasoningLesson(11, "reasoning-with-equations", "Reasoning with Equations", "intermediate"),
] as const;

export const MATH_ALGEBRA_LEVEL_12_SEEDS = [
  lesson(
    12,
    "unpacking-boxes",
    "Unpacking Boxes",
    "intermediate",
    [
      mcScene(
        "l12-unp-1",
        "Distribute",
        "3(x + 2) unpacked is…",
        ["3x + 6", "3x + 2", "x + 6", "3x + 5"],
        "3x + 6",
        "unpack_1",
        { correct: "3x + 6.", incorrect: "Distribute 3.", hint: "3×2=6." },
      ),
      mcScene(
        "l12-unp-2",
        "Solve",
        "3(x + 2) = 15 → x = ?",
        ["3", "5", "7", "2"],
        "3",
        "unpack_2",
        { correct: "x + 2 = 5 → x = 3.", incorrect: "Divide by 3.", hint: "x = 3." },
      ),
      mcScene(
        "l12-unp-3",
        "Box metaphor",
        "A box ( ) groups terms so the outside factor multiplies…",
        ["Each term inside", "Only the first", "Only the last", "Nothing"],
        "Each term inside",
        "unpack_3",
        { correct: "Distributive property.", incorrect: "Each inside term.", hint: "Each term." },
      ),
    ],
    mcScene(
      "l12-unp-final",
      "Mastery check",
      "2(x − 1) = 8 → x = ?",
      ["5", "4", "3", "1"],
      "5",
      "unpack_mastery",
      { correct: "x − 1 = 4 → x = 5.", incorrect: "Divide by 2.", hint: "5." },
    ),
  ),
  lesson(
    12,
    "packing-boxes",
    "Packing Boxes",
    "intermediate",
    [
      mcScene(
        "l12-pck-1",
        "Factor",
        "4x + 8 packed as a box?",
        ["4(x + 2)", "4(x + 8)", "(4x)(8)", "x + 12"],
        "4(x + 2)",
        "pack_1",
        { correct: "4(x + 2).", incorrect: "GCF 4.", hint: "4 out." },
      ),
      mcScene(
        "l12-pck-2",
        "Check",
        "4(x + 2) expands to?",
        ["4x + 8", "4x + 2", "x + 8", "4x + 6"],
        "4x + 8",
        "pack_2",
        { correct: "Unpack to verify.", incorrect: "Distribute.", hint: "4x + 8." },
      ),
      mcScene(
        "l12-pck-3",
        "Inverse",
        "Packing and unpacking are…",
        ["Inverse operations", "Unrelated", "Always fractions", "Inequalities"],
        "Inverse operations",
        "pack_3",
        { correct: "Factor ↔ distribute.", incorrect: "Reverse steps.", hint: "Inverses." },
      ),
    ],
    mcScene(
      "l12-pck-final",
      "Mastery check",
      "6x + 9 = 3( ? )",
      ["2x + 3", "6x + 3", "x + 9", "3x + 3"],
      "2x + 3",
      "pack_mastery",
      { correct: "3(2x + 3).", incorrect: "GCF 3.", hint: "2x + 3." },
    ),
  ),
  lesson(
    12,
    "reasoning-about-unpacking",
    "Reasoning about Unpacking",
    "intermediate",
    [
      mcScene(
        "l12-rup-1",
        "When unpack",
        "Unpack before solving when…",
        ["Equation has grouped form a(x+b)=c", "Never", "Always factor first", "x is 0"],
        "Equation has grouped form a(x+b)=c",
        "reason_unpack_1",
        { correct: "Groups suggest distribute.", incorrect: "Parentheses.", hint: "Grouped form." },
      ),
      mcScene(
        "l12-rup-2",
        "Mental math",
        "5(x + 3) = 35 → x + 3 = ?",
        ["7", "35", "5", "3"],
        "7",
        "reason_unpack_2",
        { correct: "Divide by 5 first.", incorrect: "35/5.", hint: "7." },
      ),
      mcScene(
        "l12-rup-3",
        "Finish",
        "x + 3 = 7 → x = ?",
        ["4", "3", "7", "10"],
        "4",
        "reason_unpack_3",
        { correct: "x = 4.", incorrect: "7 − 3.", hint: "4." },
      ),
    ],
    mcScene(
      "l12-rup-final",
      "Mastery check",
      "4(x + 1) = 20 → x = ?",
      ["4", "5", "1", "20"],
      "4",
      "reason_unpack_mastery",
      { correct: "x = 4.", incorrect: "x + 1 = 5.", hint: "4." },
    ),
  ),
  lesson(
    12,
    "reasoning-about-packing-boxes",
    "Reasoning about Packing Boxes",
    "intermediate",
    [
      mcScene(
        "l12-rpk-1",
        "See GCF",
        "6x + 12 → common factor?",
        ["6", "12", "x", "1 only"],
        "6",
        "reason_pack_1",
        { correct: "GCF 6.", incorrect: "6 divides both.", hint: "6." },
      ),
      mcScene(
        "l12-rpk-2",
        "Packed",
        "6x + 12 = 6(x + 2). Solve 6(x + 2) = 30 → x = ?",
        ["3", "2", "5", "6"],
        "3",
        "reason_pack_2",
        { correct: "x + 2 = 5.", incorrect: "x = 3.", hint: "3." },
      ),
      mcScene(
        "l12-rpk-3",
        "Strategy",
        "Packing simplifies…",
        ["Division step", "Addition only", "Graphing only", "Nothing"],
        "Division step",
        "reason_pack_3",
        { correct: "Factor then divide.", incorrect: "See structure.", hint: "Divide." },
      ),
    ],
    mcScene(
      "l12-rpk-final",
      "Mastery check",
      "5(x − 2) = 0 → x = ?",
      ["2", "0", "5", "−2"],
      "2",
      "reason_pack_mastery",
      { correct: "x − 2 = 0.", incorrect: "Divide by 5 first.", hint: "2." },
    ),
  ),
  lesson(
    12,
    "reasoning-about-multiples",
    "Reasoning about Multiples",
    "intermediate",
    [
      mcScene(
        "l12-mult-1",
        "Coefficients",
        "6x and 4x are multiples of…",
        ["x", "6", "4 only", "Nothing"],
        "x",
        "reason_mult_1",
        { correct: "Like terms in x.", incorrect: "Same variable.", hint: "x." },
      ),
      mcScene(
        "l12-mult-2",
        "Combine",
        "6x + 4x = ?",
        ["10x", "10x²", "24x", "6x4x"],
        "10x",
        "reason_mult_2",
        { correct: "10x.", incorrect: "6 + 4.", hint: "10x." },
      ),
      mcScene(
        "l12-mult-3",
        "Equation",
        "6x + 4x = 20 → x = ?",
        ["2", "10", "20", "4"],
        "2",
        "reason_mult_3",
        { correct: "10x = 20.", incorrect: "x = 2.", hint: "2." },
      ),
    ],
    mcScene(
      "l12-mult-final",
      "Mastery check",
      "8x − 3x = 15 → x = ?",
      ["3", "5", "15", "8"],
      "3",
      "reason_mult_mastery",
      { correct: "5x = 15.", incorrect: "x = 3.", hint: "3." },
    ),
  ),
] as const;

export const MATH_ALGEBRA_LEVEL_13_SEEDS = [
  lesson(
    13,
    "constraints",
    "Constraints",
    "intermediate",
    [
      mcScene(
        "l13-con-1",
        "Definition",
        "A constraint is…",
        ["A limit on allowed values", "Any fraction", "A graph color", "Always x = 0"],
        "A limit on allowed values",
        "constraint_1",
        { correct: "Rules variables must satisfy.", incorrect: "Limits solutions.", hint: "Limit." },
      ),
      mcScene(
        "l13-con-2",
        "Example",
        "x + y = 10 is a constraint linking…",
        ["x and y", "x only", "Constants only", "Nothing"],
        "x and y",
        "constraint_2",
        { correct: "Relates two unknowns.", incorrect: "Both variables.", hint: "x and y." },
      ),
      mcScene(
        "l13-con-3",
        "Count",
        "Two unknowns need at least ___ constraints (in general).",
        ["2", "1", "0", "5"],
        "2",
        "constraint_3",
        { correct: "Two equations typically.", incorrect: "Match unknowns.", hint: "2." },
      ),
    ],
    mcScene(
      "l13-con-final",
      "Mastery check",
      "x ≥ 0 is a constraint that…",
      ["Rules out negative x", "Forces x = 0", "Means x > 10", "Has no effect"],
      "Rules out negative x",
      "constraint_mastery",
      { correct: "x must be nonnegative.", incorrect: "Inequality constraint.", hint: "No negative x." },
    ),
  ),
  lesson(
    13,
    "more-constraints",
    "More Constraints",
    "intermediate",
    [
      mcScene(
        "l13-mc-1",
        "System",
        "x + y = 8 and x − y = 2 are ___ constraints.",
        ["Two", "One", "Zero", "Four"],
        "Two",
        "more_constraint_1",
        { correct: "Two equations.", incorrect: "System.", hint: "Two." },
      ),
      mcScene(
        "l13-mc-2",
        "Solve",
        "x + y = 8, x − y = 2 → x = ?",
        ["5", "4", "3", "8"],
        "5",
        "more_constraint_2",
        { correct: "x = 5, y = 3.", incorrect: "Add equations.", hint: "5." },
      ),
      mcScene(
        "l13-mc-3",
        "y",
        "From above, y = ?",
        ["3", "5", "2", "8"],
        "3",
        "more_constraint_3",
        { correct: "y = 3.", incorrect: "8 − 5.", hint: "3." },
      ),
    ],
    mcScene(
      "l13-mc-final",
      "Mastery check",
      "More constraints than unknowns can mean…",
      ["No solution or redundancy", "Always one solution", "Always infinite", "Always x = 0"],
      "No solution or redundancy",
      "more_constraint_mastery",
      { correct: "Overdetermined systems.", incorrect: "May conflict.", hint: "No solution possible." },
    ),
  ),
  reasoningLesson(13, "reasoning-with-balanced-scales", "Reasoning with Balanced Scales", "intermediate"),
  reasoningLesson(13, "reasoning-with-weighted-scales", "Reasoning with Weighted Scales", "intermediate"),
  reasoningLesson(13, "reasoning-with-scale-systems", "Reasoning with Scale Systems", "intermediate"),
  lesson(
    13,
    "constraints-in-scale-systems",
    "Constraints in Scale Systems",
    "intermediate",
    [
      balanceScene(
        "l13-css-1",
        "Two scales",
        "Scale 1: x+y=9. Scale 2: x=4. Find y.",
        { weights: [1, 4, 5, 9], fixedLeft: [4], fixedRight: [9], left: [4, 5], right: [9] },
        "constraint_scale_1",
        { correct: "y = 5.", incorrect: "9 − 4.", hint: "5." },
      ),
      mcScene(
        "l13-css-2",
        "Interpret",
        "Each balanced scale is one…",
        ["Constraint", "Inequality always", "Fraction", "Graph"],
        "Constraint",
        "constraint_scale_2",
        { correct: "Equation = constraint.", incorrect: "Balance = equality.", hint: "Constraint." },
      ),
      mcScene(
        "l13-css-3",
        "Solve",
        "Constraints x=3 and x+y=10 → y=?",
        ["7", "3", "10", "13"],
        "7",
        "constraint_scale_3",
        { correct: "y = 7.", incorrect: "10 − 3.", hint: "7." },
      ),
    ],
    mcScene(
      "l13-css-final",
      "Mastery check",
      "Three unknowns generally need ___ independent constraints.",
      ["3", "1", "2", "0"],
      "3",
      "constraint_scale_mastery",
      { correct: "Match unknown count.", incorrect: "Three equations.", hint: "3." },
    ),
  ),
  lesson(
    13,
    "reasoning-with-an-inequality",
    "Reasoning with an Inequality",
    "intermediate",
    [
      mcScene(
        "l13-ineq-1",
        "Tilt vs balance",
        "Tilted scale → ___ ; level scale with equal unknowns → =.",
        ["Inequality", "Fraction", "Always 0", "No relation"],
        "Inequality",
        "reason_ineq_1",
        { correct: "Unequal totals.", incorrect: "Not balanced.", hint: "Inequality." },
      ),
      mcScene(
        "l13-ineq-2",
        "Combine",
        "x + 2 > 5 → x > ?",
        ["3", "5", "2", "7"],
        "3",
        "reason_ineq_2",
        { correct: "x > 3.", incorrect: "Subtract 2.", hint: "3." },
      ),
      mcScene(
        "l13-ineq-3",
        "And equality",
        "Constraint x + y = 6 with inequality x > 1 limits…",
        ["x", "y only", "Nothing", "Both must be >6"],
        "x",
        "reason_ineq_3",
        { correct: "x must exceed 1 and satisfy sum.", incorrect: "Both constraints apply.", hint: "x > 1." },
      ),
    ],
    mcScene(
      "l13-ineq-final",
      "Mastery check",
      "Level 13 complete: 2x + 1 > 9 → x > ?",
      ["4", "5", "9", "2"],
      "4",
      "reason_ineq_mastery",
      { correct: "x > 4.", incorrect: "2x > 8.", hint: "4." },
    ),
  ),
] as const;
