import {
  balanceTwoStepLesson,
  combineLikeTermsLesson,
  lesson,
  matchScene,
  mcScene,
  sortScene,
} from "./_helpers";

export const MATH_ALGEBRA_LEVEL_5_SEEDS = [
  combineLikeTermsLesson(5, "combining-like-terms", "Combining Like Terms", 3, 5),
  lesson(
    5,
    "combining-in-equations",
    "Combining in Equations",
    "intermediate",
    [
      mcScene(
        "l5-cie-1",
        "Simplify first",
        "2x + 3x + 4 = 19 simplifies to?",
        ["5x + 4 = 19", "6x + 4 = 19", "5x = 19", "2x + 7 = 19"],
        "5x + 4 = 19",
        "combine_in_eq",
        {
          correct: "5x + 4 = 19 — combine x terms first.",
          incorrect: "2 + 3 = 5 on the x terms.",
          hint: "Like terms on the left.",
        },
      ),
      mcScene(
        "l5-cie-2",
        "Solve",
        "5x + 4 = 19 → x = ?",
        ["3", "4", "5", "15"],
        "3",
        "combine_in_eq_solve",
        { correct: "x = 3.", incorrect: "19 − 4 = 15; 15÷5.", hint: "5x = 15." },
      ),
      matchScene(
        "l5-cie-3",
        "Match steps",
        "Match simplified form and solution.",
        [
          { id: "a", label: "5x = 15" },
          { id: "b", label: "x = 3" },
          { id: "c", label: "5x + 4 = 19" },
        ],
        [
          { id: "s1", label: "After subtract 4" },
          { id: "s2", label: "Solution" },
        ],
        { s1: "a", s2: "b" },
        "combine_in_eq_match",
        {
          correct: "Combine, subtract, divide.",
          incorrect: "5x + 4 = 19 → 5x = 15 → x = 3.",
          hint: "Follow the pipeline.",
        },
      ),
    ],
    mcScene(
      "l5-cie-final",
      "Mastery check",
      "7x − 2x + 3 = 18 → x = ?",
      ["3", "5", "6", "15"],
      "3",
      "combine_in_eq_mastery",
      {
        correct: "5x + 3 = 18 → x = 3.",
        incorrect: "Combine to 5x + 3 = 18.",
        hint: "7x − 2x = 5x.",
      },
    ),
  ),
  lesson(
    5,
    "rearranging-terms",
    "Rearranging Terms",
    "intermediate",
    [
      sortScene(
        "l5-rearr-1",
        "Move terms",
        "Order steps to rearrange 3x + 5 = 2x + 8.",
        ["Subtract 2x from both sides", "x + 5 = 8", "Subtract 5 from both sides", "x = 3"],
        ["Subtract 2x from both sides", "x + 5 = 8", "Subtract 5 from both sides", "x = 3"],
        "rearrange_steps",
        {
          correct: "Move variable terms one side, constants the other.",
          incorrect: "Get x terms together first.",
          hint: "Subtract 2x first.",
        },
      ),
      mcScene(
        "l5-rearr-2",
        "After move",
        "3x + 5 = 2x + 8 → x + 5 = 8 → x = ?",
        ["3", "5", "8", "13"],
        "3",
        "rearrange_solve",
        { correct: "x = 3.", incorrect: "8 − 5.", hint: "Subtract 5." },
      ),
      mcScene(
        "l5-rearr-3",
        "Why rearrange?",
        "Moving terms across the = sign changes their…",
        ["Sign", "Value only", "Variable", "Coefficient only"],
        "Sign",
        "rearrange_sign",
        {
          correct: "+5 becomes −5 when moved to the other side.",
          incorrect: "Subtraction undoes addition across the equation.",
          hint: "Think balance — remove from one side, remove from other.",
        },
      ),
    ],
    mcScene(
      "l5-rearr-final",
      "Mastery check",
      "4x − 1 = 2x + 7 → x = ?",
      ["4", "3", "8", "1"],
      "4",
      "rearrange_mastery",
      { correct: "2x = 8 → x = 4.", incorrect: "Subtract 2x, add 1.", hint: "4x − 2x = 8 + 1." },
    ),
  ),
  lesson(
    5,
    "rearranging-terms-in-equations",
    "Rearranging Terms in Equations",
    "intermediate",
    [
      mcScene(
        "l5-rte-1",
        "Both sides",
        "5 − x = 2 → rearrange to x = ?",
        ["3", "−3", "7", "−7"],
        "3",
        "rearrange_eq_1",
        { correct: "x = 3.", incorrect: "5 − x = 2 → x = 5 − 2.", hint: "Isolate x." },
      ),
      mcScene(
        "l5-rte-2",
        "Variables both sides",
        "6x = 4x + 10 → x = ?",
        ["5", "4", "10", "2"],
        "5",
        "rearrange_eq_2",
        { correct: "2x = 10 → x = 5.", incorrect: "Subtract 4x.", hint: "6x − 4x = 10." },
      ),
      sortScene(
        "l5-rte-3",
        "Pipeline",
        "Order: move x terms → move constants → divide.",
        ["x = result", "Collect x terms", "Collect constants", "Original equation"],
        ["Original equation", "Collect x terms", "Collect constants", "x = result"],
        "rearrange_eq_order",
        {
          correct: "Systematic rearranging avoids errors.",
          incorrect: "Start from the given equation.",
          hint: "Original first.",
        },
      ),
    ],
    mcScene(
      "l5-rte-final",
      "Mastery check",
      "7x + 2 = 3x + 18 → x = ?",
      ["4", "5", "16", "2"],
      "4",
      "rearrange_eq_mastery",
      { correct: "4x = 16 → x = 4.", incorrect: "Subtract 3x and 2.", hint: "4x = 16." },
    ),
  ),
  balanceTwoStepLesson(5, "combining-and-solving", "Combining and Solving", 3, 2, 17),
  lesson(
    5,
    "grouping-to-solve",
    "Grouping to Solve",
    "intermediate",
    [
      mcScene(
        "l5-grp-1",
        "Factor then solve",
        "2x + 6 = 0 → factor 2(x + 3) = 0 → x = ?",
        ["−3", "3", "0", "6"],
        "−3",
        "group_solve_1",
        { correct: "x = −3.", incorrect: "x + 3 = 0.", hint: "Zero product." },
      ),
      mcScene(
        "l5-grp-2",
        "Grouped form",
        "3(x − 4) = 9 → x = ?",
        ["7", "4", "3", "1"],
        "7",
        "group_solve_2",
        { correct: "x − 4 = 3 → x = 7.", incorrect: "Divide by 3 first.", hint: "x − 4 = 3." },
      ),
      sortScene(
        "l5-grp-3",
        "Group strategy",
        "Order: factor/group → divide → solve.",
        ["Factor common term", "Isolate grouped expression", "Solve for x", "Original"],
        ["Original", "Factor common term", "Isolate grouped expression", "Solve for x"],
        "group_solve_order",
        {
          correct: "Grouping reveals structure.",
          incorrect: "Start from the original equation.",
          hint: "Original first.",
        },
      ),
    ],
    mcScene(
      "l5-grp-final",
      "Mastery check",
      "4(x + 1) = 20 → x = ?",
      ["4", "5", "1", "20"],
      "4",
      "group_solve_mastery",
      { correct: "x + 1 = 5 → x = 4.", incorrect: "Divide by 4.", hint: "x + 1 = 5." },
    ),
  ),
] as const;
