import { barScene, lesson, matchScene, mcScene, sortScene } from "./_helpers";

/** Level 4 — adding fractions (like denominators, unlike parts, unit fractions). */
export const MATH_FRACTIONS_LEVEL_4_SEEDS = [
  lesson(
    "lesson-fractions-adding-intro",
    "Adding Fractions",
    4,
    "beginner",
    [
      mcScene(
        "l4-add-1",
        "Same parts",
        "1/5 + 2/5 = ?",
        ["3/5", "3/10", "2/5", "1/5"],
        "3/5",
        "l4_add_intro",
        {
          correct: "1/5 + 2/5 = 3/5 — add numerators, keep denominator.",
          incorrect: "Same denominator: add tops only.",
          hint: "1 + 2 = 3, denominator stays 5.",
        },
      ),
      barScene("l4-add-2", "Model 3/5", "Shade 3/5 on a 5-part bar (result of 1/5 + 2/5).", 5, 3, "l4_add_35", {
        correct: "3/5 — three fifths shaded.",
        incorrect: "Shade three of five parts.",
        hint: "Sum of 1 and 2 fifths.",
      }),
      mcScene(
        "l4-add-3",
        "Add quarters",
        "1/4 + 1/4 = ?",
        ["2/4", "2/8", "1/8", "2/2"],
        "2/4",
        "l4_add_quarters",
        {
          correct: "1/4 + 1/4 = 2/4 = 1/2.",
          incorrect: "Add numerators when denominators match.",
          hint: "1 + 1 = 2.",
        },
      ),
    ],
    barScene("l4-add-final", "Mastery check", "Shade 5/8 after adding 2/8 + 3/8.", 8, 5, "l4_add_mastery", {
      correct: "2/8 + 3/8 = 5/8.",
      incorrect: "Shade five of eight parts.",
      hint: "2 + 3 = 5 eighths.",
    }),
  ),
  lesson(
    "lesson-fractions-adding-same-sized",
    "Adding Same-Sized Fractions",
    4,
    "beginner",
    [
      barScene("l4-same-1", "Add thirds", "Shade 1/3 + 1/3 = 2/3 on a 6-part bar (sixths).", 6, 4, "l4_same_23", {
        correct: "2/3 = 4/6 — four sixths shaded.",
        incorrect: "Two thirds is four sixths on a six-part bar.",
        hint: "1/3 = 2/6; add another 2/6.",
      }),
      mcScene(
        "l4-same-2",
        "Add sixths",
        "2/6 + 1/6 = ?",
        ["3/6", "3/12", "2/6", "1/6"],
        "3/6",
        "l4_same_26",
        {
          correct: "2/6 + 1/6 = 3/6 = 1/2.",
          incorrect: "Add numerators: 2 + 1 = 3.",
          hint: "Denominator stays 6.",
        },
      ),
      matchScene(
        "l4-same-3",
        "Match the sum",
        "3/10 + 4/10 = ? Match the result.",
        [
          { id: "s7", label: "7/10" },
          { id: "s7b", label: "7/20" },
          { id: "s1", label: "1/10" },
        ],
        [{ id: "sum", label: "Sum" }],
        { sum: "s7" },
        "l4_same_match",
        {
          correct: "3/10 + 4/10 = 7/10.",
          incorrect: "3 + 4 = 7 tenths.",
          hint: "Same denominator 10.",
        },
      ),
    ],
    mcScene(
      "l4-same-final",
      "Mastery check",
      "5/12 + 4/12 = ?",
      ["9/12", "9/24", "1/12", "9/6"],
      "9/12",
      "l4_same_mastery",
      {
        correct: "9/12 = 3/4.",
        incorrect: "5 + 4 = 9; denominator 12.",
        hint: "Add numerators only.",
      },
    ),
  ),
  lesson(
    "lesson-fractions-adding-unlike-parts",
    "Adding Unlike Parts",
    4,
    "intermediate",
    [
      sortScene(
        "l4-unlike-1",
        "Find common denominator",
        "Order steps to add 1/3 + 1/4.",
        [
          "1/3 + 1/4 = 4/12 + 3/12 = 7/12",
          "Convert 1/4 to 3/12",
          "Convert 1/3 to 4/12",
          "Use LCD 12",
        ],
        ["Use LCD 12", "Convert 1/3 to 4/12", "Convert 1/4 to 3/12", "1/3 + 1/4 = 4/12 + 3/12 = 7/12"],
        "l4_unlike_steps",
        {
          correct: "1/3 + 1/4 = 7/12 via twelfths.",
          incorrect: "Common denominator 12 first.",
          hint: "LCD of 3 and 4 is 12.",
        },
      ),
      matchScene(
        "l4-unlike-2",
        "Convert to twelfths",
        "Match 1/3 and 1/4 on denominator 12.",
        [
          { id: "a", label: "4/12" },
          { id: "b", label: "3/12" },
          { id: "c", label: "1/12" },
        ],
        [
          { id: "t3", label: "1/3 as twelfths" },
          { id: "t4", label: "1/4 as twelfths" },
        ],
        { t3: "a", t4: "b" },
        "l4_unlike_convert",
        {
          correct: "1/3 = 4/12 and 1/4 = 3/12.",
          incorrect: "4/12 + 3/12 = 7/12.",
          hint: "×4 on 1/3; ×3 on 1/4.",
        },
      ),
      mcScene(
        "l4-unlike-3",
        "Add them",
        "1/3 + 1/4 = ?",
        ["7/12", "2/7", "5/12", "2/12"],
        "7/12",
        "l4_unlike_sum",
        {
          correct: "4/12 + 3/12 = 7/12.",
          incorrect: "Add converted numerators.",
          hint: "4 + 3 = 7 twelfths.",
        },
      ),
    ],
    mcScene(
      "l4-unlike-final",
      "Mastery check",
      "1/2 + 1/8 = ?",
      ["5/8", "2/10", "3/8", "2/8"],
      "5/8",
      "l4_unlike_mastery",
      {
        correct: "4/8 + 1/8 = 5/8.",
        incorrect: "1/2 = 4/8 on eighths.",
        hint: "Convert 1/2 to 4/8.",
      },
    ),
  ),
  lesson(
    "lesson-fractions-adding-unit-fractions",
    "Adding Unit Fractions",
    4,
    "beginner",
    [
      mcScene(
        "l4-unit-1",
        "Unit fractions",
        "1/6 + 1/6 = ?",
        ["2/6", "2/12", "1/6", "1/12"],
        "2/6",
        "l4_unit_66",
        {
          correct: "2/6 = 1/3.",
          incorrect: "Two sixths combined.",
          hint: "1 + 1 = 2.",
        },
      ),
      barScene("l4-unit-2", "Three unit fifths", "Shade 1/5 + 1/5 + 1/5 = 3/5.", 5, 3, "l4_unit_35", {
        correct: "3/5 — three unit fifths.",
        incorrect: "Shade three of five parts.",
        hint: "Add three 1/5 pieces.",
      }),
      mcScene(
        "l4-unit-3",
        "Different denominators",
        "1/2 + 1/4 = ?",
        ["3/4", "2/6", "2/4", "1/6"],
        "3/4",
        "l4_unit_24",
        {
          correct: "2/4 + 1/4 = 3/4.",
          incorrect: "1/2 = 2/4.",
          hint: "Convert 1/2 to fourths.",
        },
      ),
    ],
    mcScene(
      "l4-unit-final",
      "Mastery check",
      "1/3 + 1/6 = ?",
      ["3/6", "2/9", "1/2", "2/6"],
      "1/2",
      "l4_unit_mastery",
      {
        correct: "2/6 + 1/6 = 3/6 = 1/2.",
        incorrect: "1/3 = 2/6.",
        hint: "Common denominator 6.",
      },
    ),
  ),
  lesson(
    "lesson-fractions-adding-any-fractions",
    "Adding Any Fractions",
    4,
    "intermediate",
    [
      sortScene(
        "l4-any-1",
        "Full add pipeline",
        "Order steps to add 2/5 + 1/3.",
        [
          "2/5 + 1/3 = 6/15 + 5/15 = 11/15",
          "Convert 2/5 to 6/15",
          "Convert 1/3 to 5/15",
          "LCD is 15",
        ],
        ["LCD is 15", "Convert 2/5 to 6/15", "Convert 1/3 to 5/15", "2/5 + 1/3 = 6/15 + 5/15 = 11/15"],
        "l4_any_steps",
        {
          correct: "11/15 — convert, add numerators.",
          incorrect: "Find LCD 15 before adding.",
          hint: "5×3 = 15.",
        },
      ),
      mcScene(
        "l4-any-2",
        "Compute sum",
        "2/5 + 1/3 = ?",
        ["11/15", "3/8", "3/15", "7/15"],
        "11/15",
        "l4_any_sum",
        {
          correct: "6/15 + 5/15 = 11/15.",
          incorrect: "6 + 5 = 11 fifteenths.",
          hint: "Use converted fractions.",
        },
      ),
      matchScene(
        "l4-any-3",
        "Simplify if needed",
        "3/4 + 1/8 = ? Match the sum.",
        [
          { id: "s7", label: "7/8" },
          { id: "s4", label: "4/12" },
          { id: "s1", label: "1/8" },
        ],
        [{ id: "ans", label: "Sum" }],
        { ans: "s7" },
        "l4_any_78",
        {
          correct: "6/8 + 1/8 = 7/8.",
          incorrect: "3/4 = 6/8.",
          hint: "Convert 3/4 to eighths.",
        },
      ),
    ],
    mcScene(
      "l4-any-final",
      "Mastery check",
      "3/4 + 2/3 = ?",
      ["17/12", "5/7", "6/12", "5/12"],
      "17/12",
      "l4_any_mastery",
      {
        correct: "9/12 + 8/12 = 17/12 — improper fraction OK.",
        incorrect: "LCD 12: 3/4 = 9/12, 2/3 = 8/12.",
        hint: "9 + 8 = 17.",
      },
    ),
  ),
] as const;
