import { barScene, gridScene, lesson, matchScene, mcScene, nlScene, segScene, sortScene } from "./_helpers";

/** Level 2 — equivalent fractions, simplifying, sixths/twelfths, eighths/sixteenths. */
export const MATH_FRACTIONS_LEVEL_2_SEEDS = [
  lesson(
    "lesson-fractions-equivalent-intro",
    "Equivalent Fractions",
    2,
    "beginner",
    [
      barScene("l2-eq-1", "Two fourths", "Shade 2/4 on a 4-part bar.", 4, 2, "l2_eq_24", {
        correct: "2/4 — two of four equal parts.",
        incorrect: "Shade two of the four slices.",
        hint: "Numerator 2, denominator 4.",
      }),
      mcScene(
        "l2-eq-2",
        "Same amount?",
        "2/4 is the same amount as which fraction?",
        ["1/2", "2/1", "4/2", "1/4"],
        "1/2",
        "l2_eq_same",
        {
          correct: "2/4 = 1/2 — equivalent fractions, different names.",
          incorrect: "Cover half the bar with 2/4; that’s also 1/2.",
          hint: "Half of four is two.",
        },
      ),
      barScene("l2-eq-3", "One half again", "Shade 1/2 on an 8-part bar (4/8).", 8, 4, "l2_eq_48", {
        correct: "4/8 = 1/2 — same shaded amount, more parts.",
        incorrect: "Half of 8 is 4 shaded slices.",
        hint: "8 ÷ 2 = 4.",
      }),
    ],
    matchScene(
      "l2-eq-final",
      "Mastery check",
      "Match equivalent fractions to the same amount.",
      [
        { id: "h", label: "1/2" },
        { id: "f24", label: "2/4" },
        { id: "f48", label: "4/8" },
        { id: "f18", label: "1/8" },
      ],
      [
        { id: "half", label: "Half of a whole" },
        { id: "twoq", label: "Two quarters" },
      ],
      { half: "h", twoq: "f24" },
      "l2_eq_mastery",
      {
        correct: "1/2 and 2/4 name the same amount.",
        incorrect: "Two fourths equals one half.",
        hint: "2/4 simplifies to 1/2.",
      },
    ),
  ),
  lesson(
    "lesson-fractions-sixths-twelfths",
    "Sixths and Twelfths",
    2,
    "beginner",
    [
      barScene("l2-612-1", "Three sixths", "Shade 3/6 on a 6-part bar.", 6, 3, "l2_36", {
        correct: "3/6 — three of six equal parts.",
        incorrect: "Shade three slices of six.",
        hint: "3 out of 6.",
      }),
      barScene("l2-612-2", "Six twelfths", "Shade 6/12 on a 12-part bar.", 12, 6, "l2_612", {
        correct: "6/12 — same half, finer slices.",
        incorrect: "Half of 12 is 6 shaded parts.",
        hint: "12 ÷ 2 = 6.",
      }),
      mcScene(
        "l2-612-3",
        "Compare",
        "Which equals 3/6?",
        ["6/12", "3/12", "6/6", "1/12"],
        "6/12",
        "l2_612_equiv",
        {
          correct: "3/6 = 6/12 = 1/2 — scale numerator and denominator by 2.",
          incorrect: "Double both parts of 3/6 to get 6/12.",
          hint: "3×2 = 6 and 6×2 = 12.",
        },
      ),
    ],
    barScene("l2-612-final", "Mastery check", "Shade 4/12 on a 12-part bar.", 12, 4, "l2_612_mastery", {
      correct: "4/12 = 1/3 — four twelfths.",
      incorrect: "Shade four of twelve equal parts.",
      hint: "Count four slices on a bar of twelve.",
    }),
  ),
  lesson(
    "lesson-fractions-eighths-sixteenths",
    "Eighths and Sixteenths",
    2,
    "beginner",
    [
      barScene("l2-816-1", "Two eighths", "Shade 2/8 on an 8-part bar.", 8, 2, "l2_28", {
        correct: "2/8 — two eighths.",
        incorrect: "Shade two of eight slices.",
        hint: "2 shaded, 8 total.",
      }),
      barScene("l2-816-2", "Four sixteenths", "Shade 4/16 on a 16-part bar.", 16, 4, "l2_416", {
        correct: "4/16 — same as 2/8 when the whole is the same size.",
        incorrect: "Shade four of sixteen parts.",
        hint: "4 out of 16.",
      }),
      mcScene(
        "l2-816-3",
        "Equivalence",
        "2/8 equals which sixteenth fraction?",
        ["4/16", "2/16", "8/16", "16/2"],
        "4/16",
        "l2_816_equiv",
        {
          correct: "2/8 = 4/16 — multiply top and bottom by 2.",
          incorrect: "Double 2 and 8 to get 4 and 16.",
          hint: "×2 on numerator and denominator.",
        },
      ),
    ],
    nlScene(
      "l2-816-final",
      "Mastery check",
      "Place 4/8 (= 1/2) on the number line.",
      0,
      1,
      0.125,
      0.5,
      "l2_816_mastery",
      {
        correct: "4/8 = 1/2 at the midpoint.",
        incorrect: "Halfway between 0 and 1.",
        hint: "4/8 simplifies to 1/2.",
      },
    ),
  ),
  lesson(
    "lesson-fractions-making-equivalent",
    "Making Equivalent Fractions",
    2,
    "beginner",
    [
      sortScene(
        "l2-make-1",
        "Scale up",
        "Order the steps to make an equivalent fraction for 1/3 with denominator 12.",
        [
          "1/3 = 4/12",
          "Multiply denominator: 3 × 4 = 12",
          "Multiply numerator: 1 × 4 = 4",
          "Choose multiplier: 12 ÷ 3 = 4",
        ],
        [
          "Choose multiplier: 12 ÷ 3 = 4",
          "Multiply numerator: 1 × 4 = 4",
          "Multiply denominator: 3 × 4 = 12",
          "1/3 = 4/12",
        ],
        "l2_make_steps",
        {
          correct: "1/3 = 4/12 — same value, twelfth-sized parts.",
          incorrect: "Find how many times 3 fits in 12, then scale both.",
          hint: "Start with the multiplier 12 ÷ 3.",
        },
      ),
      matchScene(
        "l2-make-2",
        "Build 2/5 = ?/10",
        "Match the scaled numerator and denominator.",
        [
          { id: "n4", label: "4" },
          { id: "d10", label: "10" },
          { id: "n2", label: "2" },
          { id: "d5", label: "5" },
        ],
        [
          { id: "num", label: "New numerator" },
          { id: "den", label: "New denominator" },
        ],
        { num: "n4", den: "d10" },
        "l2_make_25",
        {
          correct: "2/5 = 4/10 — multiply by 2.",
          incorrect: "5 × 2 = 10, so 2 × 2 = 4.",
          hint: "10 ÷ 5 = 2; scale the top by 2.",
        },
      ),
      barScene("l2-make-3", "Shade 4/10", "Shade 4/10 on a 10-part bar.", 10, 4, "l2_make_shade", {
        correct: "4/10 = 2/5 — same amount as two fifths.",
        incorrect: "Shade four of ten parts.",
        hint: "Four shaded slices on a ten-part bar.",
      }),
    ],
    mcScene(
      "l2-make-final",
      "Mastery check",
      "1/4 = ?/8. What is the missing numerator?",
      ["2", "4", "1", "8"],
      "2",
      "l2_make_mastery",
      {
        correct: "1/4 = 2/8 — multiply by 2.",
        incorrect: "4 × 2 = 8, so 1 × 2 = 2.",
        hint: "Scale numerator the same way as denominator.",
      },
    ),
  ),
  lesson(
    "lesson-fractions-simplifying",
    "Simplifying Fractions",
    2,
    "beginner",
    [
      sortScene(
        "l2-simp-1",
        "Simplify 6/8",
        "Order the steps to simplify 6/8.",
        [
          "6/8 = 3/4",
          "Divide numerator and denominator by 2",
          "Find GCF of 6 and 8 is 2",
        ],
        ["Find GCF of 6 and 8 is 2", "Divide numerator and denominator by 2", "6/8 = 3/4"],
        "l2_simp_steps",
        {
          correct: "6/8 = 3/4 in lowest terms.",
          incorrect: "Find the common factor first, then divide.",
          hint: "What divides both 6 and 8?",
        },
      ),
      barScene("l2-simp-2", "Shade 3/4", "Shade 3/4 on a 4-part bar (simplified form of 6/8).", 4, 3, "l2_simp_34", {
        correct: "3/4 — lowest terms for 6/8.",
        incorrect: "Three of four equal parts.",
        hint: "6÷2 = 3, 8÷2 = 4.",
      }),
      mcScene(
        "l2-simp-3",
        "Simplest form",
        "Which is 8/12 in lowest terms?",
        ["2/3", "4/6", "8/12", "3/2"],
        "2/3",
        "l2_simp_812",
        {
          correct: "8/12 = 2/3 — divide by 4.",
          incorrect: "Divide top and bottom by their GCF 4.",
          hint: "8÷4 = 2, 12÷4 = 3.",
        },
      ),
    ],
    mcScene(
      "l2-simp-final",
      "Mastery check",
      "Simplify 10/15.",
      ["2/3", "5/3", "10/5", "1/3"],
      "2/3",
      "l2_simp_mastery",
      {
        correct: "10/15 = 2/3 — divide by 5.",
        incorrect: "GCF of 10 and 15 is 5.",
        hint: "10÷5 = 2, 15÷5 = 3.",
      },
    ),
  ),
  lesson(
    "lesson-fractions-equivalent-recognize",
    "Equivalent Fractions",
    2,
    "beginner",
    [
      gridScene("l2-rec-1", "Half the grid", "Shade 1/2 of a 2×4 grid.", 2, 4, 4, "l2_rec_half", {
        correct: "4/8 = 1/2 of the grid.",
        incorrect: "Half of 8 cells is 4.",
        hint: "8 cells total; shade 4.",
      }),
      matchScene(
        "l2-rec-2",
        "Match equivalents",
        "Match fractions that name the same amount.",
        [
          { id: "a", label: "1/2" },
          { id: "b", label: "3/6" },
          { id: "c", label: "2/3" },
          { id: "d", label: "4/8" },
        ],
        [
          { id: "s1", label: "Half" },
          { id: "s2", label: "Also half" },
        ],
        { s1: "a", s2: "d" },
        "l2_rec_match",
        {
          correct: "1/2 = 4/8 — both are half the whole.",
          incorrect: "Pick two fractions equal to one half.",
          hint: "3/6 is also half, but match 1/2 and 4/8 here.",
        },
      ),
      barScene("l2-rec-3", "Nine twelfths", "Shade 9/12. What simpler fraction matches?", 12, 9, "l2_rec_912", {
        correct: "9/12 = 3/4 — nine twelfths.",
        incorrect: "Shade nine of twelve parts.",
        hint: "9/12 simplifies to 3/4.",
      }),
    ],
    mcScene(
      "l2-rec-final",
      "Mastery check",
      "Which is equivalent to 5/10?",
      ["1/2", "5/5", "10/5", "1/5"],
      "1/2",
      "l2_rec_mastery",
      {
        correct: "5/10 = 1/2.",
        incorrect: "Divide numerator and denominator by 5.",
        hint: "5÷5 = 1, 10÷5 = 2.",
      },
    ),
  ),
  lesson(
    "lesson-fractions-identifying-equivalents",
    "Identifying Equivalents",
    2,
    "beginner",
    [
      segScene(
        "l2-id-1",
        "Same or different?",
        "Are 2/3 and 4/6 the same amount?",
        [
          { id: "same", label: "Equivalent" },
          { id: "diff", label: "Not equivalent" },
          { id: "unk", label: "Cannot tell" },
        ],
        "same",
        "l2_id_23",
        {
          correct: "2/3 = 4/6 — multiply 2/3 by 2/2.",
          incorrect: "4/6 simplifies to 2/3.",
          hint: "Scale 2/3 up or simplify 4/6.",
        },
      ),
      matchScene(
        "l2-id-2",
        "Find the pair",
        "Which fraction matches 3/4?",
        [
          { id: "a", label: "6/8" },
          { id: "b", label: "2/4" },
          { id: "c", label: "9/12" },
          { id: "d", label: "1/4" },
        ],
        [{ id: "match", label: "Equivalent to 3/4" }],
        { match: "c" },
        "l2_id_34",
        {
          correct: "3/4 = 9/12 — multiply by 3.",
          incorrect: "9/12 = 3/4 when simplified.",
          hint: "3×3 = 9 and 4×3 = 12.",
        },
      ),
      barScene("l2-id-3", "Shade 6/8", "Shade 6/8 and think: what simpler fraction matches?", 8, 6, "l2_id_68", {
        correct: "6/8 = 3/4 — six eighths.",
        incorrect: "Shade six of eight slices.",
        hint: "6/8 simplifies to 3/4.",
      }),
    ],
    matchScene(
      "l2-id-final",
      "Mastery check",
      "Match 1/3 to its equivalent.",
      [
        { id: "third", label: "1/3" },
        { id: "t2", label: "2/6" },
        { id: "t4", label: "4/12" },
      ],
      [
        { id: "orig", label: "Starting fraction" },
        { id: "eq", label: "Equivalent" },
      ],
      { orig: "third", eq: "t4" },
      "l2_id_mastery",
      {
        correct: "1/3 = 2/6 = 4/12.",
        incorrect: "Pick fractions that scale from 1/3.",
        hint: "Multiply 1/3 by 2/2 and by 4/4.",
      },
    ),
  ),
  lesson(
    "lesson-fractions-level-2-check",
    "Level 2 Check",
    2,
    "beginner",
    [
      mcScene(
        "l2-check-1",
        "Quick equivalent",
        "4/6 simplifies to?",
        ["2/3", "3/2", "4/3", "6/4"],
        "2/3",
        "l2_check_simp",
        {
          correct: "4/6 = 2/3.",
          incorrect: "Divide by 2.",
          hint: "4÷2 and 6÷2.",
        },
      ),
      barScene("l2-check-2", "Shade 5/10", "Shade 5/10 on a 10-part bar.", 10, 5, "l2_check_510", {
        correct: "5/10 = 1/2.",
        incorrect: "Five of ten parts.",
        hint: "Half the bar.",
      }),
      matchScene(
        "l2-check-3",
        "Match scale",
        "2/5 = 6/15. Match the multiplier used.",
        [
          { id: "m3", label: "×3" },
          { id: "m2", label: "×2" },
          { id: "m5", label: "×5" },
        ],
        [{ id: "mult", label: "Scale factor" }],
        { mult: "m3" },
        "l2_check_mult",
        {
          correct: "×3 on 2/5 gives 6/15.",
          incorrect: "15 ÷ 5 = 3.",
          hint: "Denominator 5 → 15 is ×3.",
        },
      ),
    ],
    mcScene(
      "l2-check-final",
      "Level 2 mastery",
      "Which is NOT equivalent to 1/2?",
      ["3/6", "4/8", "5/9", "6/12"],
      "5/9",
      "l2_check_mastery",
      {
        correct: "5/9 ≠ 1/2 — Level 2 complete!",
        incorrect: "5/9 is less than one half.",
        hint: "1/2 = 0.5; test each fraction.",
      },
    ),
  ),
] as const;
