import { barScene, gridScene, lesson, matchScene, mcScene, sortScene } from "./_helpers";

/** Level 5 — multiplying fractions (multiples, unit fractions, general products). */
export const MATH_FRACTIONS_LEVEL_5_SEEDS = [
  lesson(
    "lesson-fractions-multiplying-intro",
    "Multiplying Fractions",
    5,
    "beginner",
    [
      mcScene(
        "l5-mul-1",
        "Multiply numerators",
        "1/2 × 1/3 = ?",
        ["1/6", "2/5", "1/5", "2/6"],
        "1/6",
        "l5_mul_intro",
        {
          correct: "1/2 × 1/3 = 1/6 — multiply tops and bottoms.",
          incorrect: "1×1 = 1, 2×3 = 6.",
          hint: "Numerator × numerator; denominator × denominator.",
        },
      ),
      gridScene("l5-mul-2", "Half of a third", "Shade 1/6 on a 2×3 grid (half of one row).", 2, 3, 1, "l5_mul_grid", {
        correct: "1/6 — one cell of six is 1/2 × 1/3.",
        incorrect: "Shade one cell of the 6-cell grid.",
        hint: "Area model: 1/2 by 1/3.",
      }),
      mcScene(
        "l5-mul-3",
        "Another product",
        "2/3 × 1/4 = ?",
        ["2/12", "3/7", "2/7", "1/12"],
        "2/12",
        "l5_mul_234",
        {
          correct: "2/12 = 1/6 — multiply then simplify.",
          incorrect: "2×1 = 2, 3×4 = 12.",
          hint: "Top×top, bottom×bottom.",
        },
      ),
    ],
    mcScene(
      "l5-mul-final",
      "Mastery check",
      "1/4 × 2/5 = ?",
      ["2/20", "3/9", "2/9", "3/20"],
      "2/20",
      "l5_mul_mastery",
      {
        correct: "2/20 = 1/10.",
        incorrect: "1×2 = 2, 4×5 = 20.",
        hint: "Multiply straight across.",
      },
    ),
  ),
  lesson(
    "lesson-fractions-multiples-of-fractions",
    "Multiples of Fractions",
    5,
    "beginner",
    [
      mcScene(
        "l5-mult-1",
        "Double a fraction",
        "2 × 1/5 = ?",
        ["2/5", "1/10", "3/5", "2/10"],
        "2/5",
        "l5_mult_25",
        {
          correct: "2 × 1/5 = 2/5 — scale the numerator.",
          incorrect: "Two copies of one fifth.",
          hint: "2 × 1 = 2 on top.",
        },
      ),
      barScene("l5-mult-2", "Shade 2/5", "Shade 2/5 on a 5-part bar (2 × 1/5).", 5, 2, "l5_mult_shade", {
        correct: "2/5 — two fifths.",
        incorrect: "Shade two of five parts.",
        hint: "Two unit fifths.",
      }),
      mcScene(
        "l5-mult-3",
        "Triple",
        "3 × 2/7 = ?",
        ["6/7", "5/7", "6/14", "2/21"],
        "6/7",
        "l5_mult_327",
        {
          correct: "3 × 2/7 = 6/7.",
          incorrect: "3 × 2 = 6; denominator stays 7.",
          hint: "Multiply whole number by numerator.",
        },
      ),
    ],
    mcScene(
      "l5-mult-final",
      "Mastery check",
      "4 × 1/6 = ?",
      ["4/6", "4/24", "5/6", "1/24"],
      "4/6",
      "l5_mult_mastery",
      {
        correct: "4/6 = 2/3.",
        incorrect: "Four sixths.",
        hint: "4 × 1 = 4 on top.",
      },
    ),
  ),
  lesson(
    "lesson-fractions-expressing-multiples",
    "Expressing Multiples",
    5,
    "beginner",
    [
      matchScene(
        "l5-exp-1",
        "Match the multiple",
        "3 × 1/4 equals which fraction?",
        [
          { id: "a", label: "3/4" },
          { id: "b", label: "1/12" },
          { id: "c", label: "4/3" },
        ],
        [{ id: "prod", label: "Product" }],
        { prod: "a" },
        "l5_exp_34",
        {
          correct: "3 × 1/4 = 3/4.",
          incorrect: "Three quarters.",
          hint: "3 copies of 1/4.",
        },
      ),
      barScene("l5-exp-2", "Shade 3/4", "Shade 3/4 on a 4-part bar.", 4, 3, "l5_exp_shade", {
        correct: "3/4 — three fourths.",
        incorrect: "Shade three of four parts.",
        hint: "3 × 1/4.",
      }),
      mcScene(
        "l5-exp-3",
        "Write as fraction",
        "5 × 1/8 written as one fraction is?",
        ["5/8", "5/40", "1/40", "6/8"],
        "5/8",
        "l5_exp_58",
        {
          correct: "5/8 — five eighths.",
          incorrect: "5 × 1 = 5 on numerator.",
          hint: "Denominator unchanged.",
        },
      ),
    ],
    matchScene(
      "l5-exp-final",
      "Mastery check",
      "Match 2 × 3/5 to its product.",
      [
        { id: "p", label: "6/5" },
        { id: "q", label: "5/6" },
        { id: "r", label: "6/10" },
      ],
      [{ id: "ans", label: "2 × 3/5" }],
      { ans: "p" },
      "l5_exp_mastery",
      {
        correct: "2 × 3/5 = 6/5.",
        incorrect: "2 × 3 = 6; denominator 5.",
        hint: "Scale numerator by 2.",
      },
    ),
  ),
  lesson(
    "lesson-fractions-fraction-of-unit-fraction",
    "Fractions of Unit Fractions",
    5,
    "beginner",
    [
      mcScene(
        "l5-fo-1",
        "Half of a third",
        "1/2 of 1/3 = ?",
        ["1/6", "2/5", "1/5", "2/3"],
        "1/6",
        "l5_fo_12of13",
        {
          correct: "1/2 × 1/3 = 1/6 — ‘of’ means multiply.",
          incorrect: "Half of a third splits into sixths.",
          hint: "Multiply the fractions.",
        },
      ),
      gridScene("l5-fo-2", "Area model", "Shade 1/6 on a 3×2 grid.", 3, 2, 1, "l5_fo_grid", {
        correct: "1/6 cell — half of one third column.",
        incorrect: "One of six equal cells.",
        hint: "3 columns × 2 rows = 6.",
      }),
      mcScene(
        "l5-fo-3",
        "Third of a half",
        "1/3 of 1/2 = ?",
        ["1/6", "2/5", "1/5", "2/6"],
        "1/6",
        "l5_fo_13of12",
        {
          correct: "1/3 × 1/2 = 1/6 — same result, order doesn’t matter.",
          incorrect: "1×1 = 1, 3×2 = 6.",
          hint: "Multiply numerators and denominators.",
        },
      ),
    ],
    mcScene(
      "l5-fo-final",
      "Mastery check",
      "1/4 of 1/2 = ?",
      ["1/8", "2/6", "1/6", "3/8"],
      "1/8",
      "l5_fo_mastery",
      {
        correct: "1/4 × 1/2 = 1/8.",
        incorrect: "1×1 = 1, 4×2 = 8.",
        hint: "‘Of’ → multiply.",
      },
    ),
  ),
  lesson(
    "lesson-fractions-products-unit-fractions",
    "Products of Unit Fractions",
    5,
    "beginner",
    [
      mcScene(
        "l5-prod-1",
        "Unit × unit",
        "1/5 × 1/2 = ?",
        ["1/10", "2/7", "1/7", "2/10"],
        "1/10",
        "l5_prod_52",
        {
          correct: "1/10 — one tenth of the whole.",
          incorrect: "1×1 = 1, 5×2 = 10.",
          hint: "Multiply denominators.",
        },
      ),
      matchScene(
        "l5-prod-2",
        "Match products",
        "Match each unit-fraction product.",
        [
          { id: "a", label: "1/12" },
          { id: "b", label: "1/8" },
          { id: "c", label: "1/6" },
        ],
        [
          { id: "p1", label: "1/3 × 1/4" },
          { id: "p2", label: "1/2 × 1/4" },
        ],
        { p1: "a", p2: "b" },
        "l5_prod_match",
        {
          correct: "1/3×1/4 = 1/12; 1/2×1/4 = 1/8.",
          incorrect: "Multiply tops and bottoms for each.",
          hint: "3×4 = 12; 2×4 = 8.",
        },
      ),
      mcScene(
        "l5-prod-3",
        "Smallest product",
        "Which product is smallest: 1/2×1/3, 1/2×1/4, 1/3×1/4?",
        ["1/3 × 1/4", "1/2 × 1/3", "1/2 × 1/4"],
        "1/3 × 1/4",
        "l5_prod_smallest",
        {
          correct: "1/12 < 1/6 < 1/8.",
          incorrect: "1/3×1/4 = 1/12 is the tiniest piece.",
          hint: "Compute each: 1/6, 1/8, 1/12.",
        },
      ),
    ],
    mcScene(
      "l5-prod-final",
      "Mastery check",
      "1/7 × 1/3 = ?",
      ["1/21", "2/10", "1/10", "3/21"],
      "1/21",
      "l5_prod_mastery",
      {
        correct: "1/21.",
        incorrect: "7 × 3 = 21 denominator.",
        hint: "1×1 over 7×3.",
      },
    ),
  ),
  lesson(
    "lesson-fractions-fraction-of-any-fraction",
    "Fraction of Any Fraction",
    5,
    "intermediate",
    [
      mcScene(
        "l5-any-1",
        "General product",
        "2/3 × 3/4 = ?",
        ["6/12", "5/7", "6/7", "5/12"],
        "6/12",
        "l5_any_234",
        {
          correct: "6/12 = 1/2.",
          incorrect: "2×3 = 6, 3×4 = 12.",
          hint: "Multiply across.",
        },
      ),
      barScene("l5-any-2", "Shade half", "Shade 1/2 on a 4-part bar (6/12 simplified).", 4, 2, "l5_any_half", {
        correct: "1/2 — simplified form of 6/12.",
        incorrect: "Two of four parts.",
        hint: "6/12 ÷ 6 = 1/2.",
      }),
      sortScene(
        "l5-any-3",
        "Multiply then simplify",
        "Order: 3/5 × 10/9 → simplify.",
        [
          "3/5 × 10/9 = 30/45 = 2/3",
          "Multiply: 30/45",
          "Simplify by 15",
          "3×10 = 30, 5×9 = 45",
        ],
        ["3×10 = 30, 5×9 = 45", "Multiply: 30/45", "Simplify by 15", "3/5 × 10/9 = 30/45 = 2/3"],
        "l5_any_steps",
        {
          correct: "30/45 = 2/3 after dividing by 15.",
          incorrect: "Multiply first, then simplify.",
          hint: "30 and 45 share factor 15.",
        },
      ),
    ],
    mcScene(
      "l5-any-final",
      "Mastery check",
      "4/5 × 1/2 = ?",
      ["4/10", "5/7", "4/7", "5/10"],
      "4/10",
      "l5_any_mastery",
      {
        correct: "4/10 = 2/5.",
        incorrect: "4×1 = 4, 5×2 = 10.",
        hint: "Multiply numerators and denominators.",
      },
    ),
  ),
  lesson(
    "lesson-fractions-multiplying-fractions",
    "Multiplying Fractions",
    5,
    "intermediate",
    [
      mcScene(
        "l5-mf-1",
        "Mixed numbers prep",
        "2/3 × 4/5 = ?",
        ["8/15", "6/8", "8/8", "6/15"],
        "8/15",
        "l5_mf_2345",
        {
          correct: "8/15 — multiply 2×4 and 3×5.",
          incorrect: "8 over 15.",
          hint: "Straight across.",
        },
      ),
      matchScene(
        "l5-mf-2",
        "Match simplified",
        "12/18 × 1/2 = ? Match the simplified answer.",
        [
          { id: "a", label: "1/3" },
          { id: "b", label: "12/36" },
          { id: "c", label: "2/3" },
        ],
        [{ id: "ans", label: "Simplified product" }],
        { ans: "a" },
        "l5_mf_simplify",
        {
          correct: "12/36 = 1/3 after simplifying.",
          incorrect: "12×1 = 12, 18×2 = 36 → 12/36 = 1/3.",
          hint: "Divide 12/36 by 12.",
        },
      ),
      gridScene("l5-mf-3", "Area of 2/3 by 1/2", "Shade 1/3 of a 3×2 grid (2/3 × 1/2 = 1/3).", 3, 2, 2, "l5_mf_area", {
        correct: "2/6 = 1/3 — two of six cells.",
        incorrect: "Area model: 2 columns of 3, half the row.",
        hint: "2/3 × 1/2 = 2/6.",
      }),
    ],
    mcScene(
      "l5-mf-final",
      "Level 5 mastery",
      "5/6 × 3/10 = ? (simplest form)",
      ["1/4", "15/60", "8/16", "1/3"],
      "1/4",
      "l5_mf_mastery",
      {
        correct: "15/60 = 1/4 — fractions curriculum complete!",
        incorrect: "5×3 = 15, 6×10 = 60; simplify.",
        hint: "Divide 15/60 by 15.",
      },
    ),
  ),
] as const;
