import { barScene, gridScene, lesson, matchScene, mcScene, nlScene, sortScene } from "./_helpers";

/** Level 1 — parts of a whole: half, combine, split, equal parts. */
export const MATH_FRACTIONS_LEVEL_1_SEEDS = [
  lesson(
    "lesson-fractions-finding-half",
    "Finding Half",
    1,
    "beginner",
    [
      barScene(
        "l1-half-bar",
        "Half the bar",
        "Shade exactly half of this 8-part bar.",
        8,
        4,
        "l1_half_bar",
        {
          correct: "4 of 8 parts is 1/2 — two equal groups of four.",
          incorrect: "Half means the same number of parts in each group: 8 ÷ 2 = 4.",
          hint: "Shade four slices.",
        },
      ),
      nlScene(
        "l1-half-line",
        "Half on the line",
        "Place 1/2 on the number line from 0 to 1.",
        0,
        1,
        0.125,
        0.5,
        "l1_half_number_line",
        {
          correct: "1/2 is halfway between 0 and 1.",
          incorrect: "Move the marker to the midpoint.",
          hint: "Four eighths from zero lands at 1/2.",
        },
      ),
      mcScene(
        "l1-half-pick",
        "Which is half?",
        "Which fraction shows exactly half of a whole?",
        ["1/2", "1/4", "2/1", "1/8"],
        "1/2",
        "l1_half_symbol",
        {
          correct: "1/2 means one of two equal parts.",
          incorrect: "Half splits the whole into two equal pieces.",
          hint: "Denominator 2 → two equal parts.",
        },
      ),
    ],
    barScene(
      "l1-half-final",
      "Mastery check",
      "Shade 1/2 of a 10-piece bar.",
      10,
      5,
      "l1_half_mastery",
      {
        correct: "5/10 = 1/2 — five shaded out of ten.",
        incorrect: "Half of 10 is 5 pieces.",
        hint: "10 ÷ 2 = 5.",
      },
    ),
  ),
  lesson(
    "lesson-fractions-combining-parts",
    "Combining Parts",
    1,
    "beginner",
    [
      barScene(
        "l1-combine-1",
        "Combine two quarters",
        "Shade 1/4, then another 1/4 on this 8-part bar (2/8 total).",
        8,
        2,
        "l1_combine_two_quarters",
        {
          correct: "2/8 — two one-eighth parts combine into two eighths.",
          incorrect: "Shade two separate one-eighth slices.",
          hint: "Each slice is 1/8; you need two of them.",
        },
      ),
      matchScene(
        "l1-combine-match",
        "Match the sum",
        "1/4 + 1/4 equals which fraction? Match the combined amount.",
        [
          { id: "q1a", label: "1/4" },
          { id: "q1b", label: "1/4" },
          { id: "half", label: "1/2" },
          { id: "e2", label: "2/8" },
          { id: "e3", label: "3/8" },
        ],
        [
          { id: "part_a", label: "First part" },
          { id: "part_b", label: "Second part" },
          { id: "total", label: "Combined" },
        ],
        { part_a: "q1a", part_b: "q1b", total: "e2" },
        "l1_combine_match",
        {
          correct: "1/4 + 1/4 = 2/8 — same amount, counted together.",
          incorrect: "Both parts are 1/4; together they make 2/8 on an eighth bar.",
          hint: "Place 1/4 in each part slot, then pick 2/8 for the total.",
        },
      ),
      gridScene(
        "l1-combine-grid",
        "Combine on a grid",
        "Shade 1/8 + 1/8 on this 2×4 grid (2 cells total).",
        2,
        4,
        2,
        "l1_combine_grid",
        {
          correct: "2 of 8 cells — combining two eighths.",
          incorrect: "Tap exactly two cells.",
          hint: "One eighth of 8 is 1 cell; you need two.",
        },
      ),
    ],
    mcScene(
      "l1-combine-final",
      "Mastery check",
      "You combine two equal 1/6 parts. What fraction do you have?",
      ["2/6", "1/12", "2/12", "1/6"],
      "2/6",
      "l1_combine_mastery",
      {
        correct: "2/6 — two sixth-sized parts joined together.",
        incorrect: "Adding same-sized parts adds numerators: 1 + 1 = 2.",
        hint: "Same denominator, add the numerators.",
      },
    ),
  ),
  lesson(
    "lesson-fractions-splitting-parts",
    "Splitting Parts",
    1,
    "beginner",
    [
      barScene(
        "l1-split-half",
        "Split a half",
        "This bar shows 1/2 shaded (4 of 8). Split each half into quarters — shade 4/8 as two groups of 2/8.",
        8,
        4,
        "l1_split_half",
        {
          correct: "4/8 still — but now you see two groups of 2/8 in each half.",
          incorrect: "Keep four shaded; think of them as two pairs.",
          hint: "Half the bar is 4 slices; each half contains 2 slices.",
        },
      ),
      sortScene(
        "l1-split-steps",
        "Splitting steps",
        "Order the steps to split 1/2 into two 1/4 pieces.",
        [
          "Each quarter is 1/4 of the whole.",
          "Start with 1/2 of the whole shaded.",
          "Split the shaded half into two equal pieces.",
          "Each piece is 1/4 of the whole.",
        ],
        [
          "Start with 1/2 of the whole shaded.",
          "Split the shaded half into two equal pieces.",
          "Each piece is 1/4 of the whole.",
          "Each quarter is 1/4 of the whole.",
        ],
        "l1_split_steps",
        {
          correct: "Splitting doubles the number of equal parts in that region.",
          incorrect: "Begin with the half, then split it in two.",
          hint: "What do you start with before splitting?",
        },
      ),
      mcScene(
        "l1-split-count",
        "Count after split",
        "After splitting 1/2 into two equal parts, how many fourths do you have?",
        ["2/4", "1/4", "4/2", "2/2"],
        "2/4",
        "l1_split_count",
        {
          correct: "Two fourths — 2/4 equals 1/2.",
          incorrect: "Two quarter-sized pieces sit inside the original half.",
          hint: "Each new piece is one fourth of the whole.",
        },
      ),
    ],
    barScene(
      "l1-split-final",
      "Mastery check",
      "Split the whole into 6 equal parts. Shade 1/6.",
      6,
      1,
      "l1_split_mastery",
      {
        correct: "1/6 — one of six equal parts after splitting the whole.",
        incorrect: "Shade exactly one slice of six.",
        hint: "Six equal parts → shade one.",
      },
    ),
  ),
  lesson(
    "lesson-fractions-splitting-combining",
    "Splitting and Combining",
    1,
    "beginner",
    [
      barScene(
        "l1-sc-shade",
        "Shade three eighths",
        "Shade 3/8 on the bar.",
        8,
        3,
        "l1_sc_shade",
        {
          correct: "3/8 — three equal eighth parts.",
          incorrect: "Shade exactly three of eight slices.",
          hint: "Count three slices from one end.",
        },
      ),
      matchScene(
        "l1-sc-rearrange",
        "Split and recombine",
        "Match: two 1/8 parts combine to make 2/8.",
        [
          { id: "a1", label: "1/8" },
          { id: "a2", label: "1/8" },
          { id: "t", label: "2/8" },
          { id: "h", label: "1/2" },
        ],
        [
          { id: "p1", label: "Part 1" },
          { id: "p2", label: "Part 2" },
          { id: "sum", label: "Total" },
        ],
        { p1: "a1", p2: "a2", sum: "t" },
        "l1_sc_match",
        {
          correct: "1/8 + 1/8 = 2/8 — combine without changing the whole.",
          incorrect: "Two eighths together make 2/8.",
          hint: "Same-sized parts add numerators.",
        },
      ),
      nlScene(
        "l1-sc-line",
        "Locate 3/8",
        "Place 3/8 on the number line (0 to 1, step 1/8).",
        0,
        1,
        0.125,
        0.375,
        "l1_sc_line",
        {
          correct: "3/8 = 0.375 — three eighths from zero.",
          incorrect: "Count three steps of size 1/8.",
          hint: "3 × 1/8 = 3/8.",
        },
      ),
    ],
    gridScene(
      "l1-sc-final",
      "Mastery check",
      "On a 4×2 grid (8 cells), shade 5/8.",
      4,
      2,
      5,
      "l1_sc_mastery",
      {
        correct: "5/8 of 8 cells — five shaded squares.",
        incorrect: "Shade five of the eight cells.",
        hint: "Eight total cells; shade five.",
      },
    ),
  ),
  lesson(
    "lesson-fractions-equal-parts",
    "Equal Parts",
    1,
    "beginner",
    [
      mcScene(
        "l1-equal-def",
        "Equal parts",
        "A fraction only works when parts are what?",
        ["Equal in size", "Different colors", "As large as possible", "Always in a row"],
        "Equal in size",
        "l1_equal_definition",
        {
          correct: "Equal parts — same size — make fractions fair and meaningful.",
          incorrect: "Fractions count equal-sized pieces of a whole.",
          hint: "Would unequal slices make 1/2 ambiguous?",
        },
      ),
      barScene(
        "l1-equal-shade",
        "Five equal parts",
        "Shade 2/5 of a bar split into 5 equal parts.",
        5,
        2,
        "l1_equal_shade",
        {
          correct: "2/5 — two of five equal parts.",
          incorrect: "Shade exactly two of the five equal slices.",
          hint: "Denominator 5 → five equal parts.",
        },
      ),
      matchScene(
        "l1-equal-compare",
        "Same whole, equal parts",
        "Match each description to the correct fraction of the same whole.",
        [
          { id: "f12", label: "1/2" },
          { id: "f14", label: "1/4" },
          { id: "f34", label: "3/4" },
        ],
        [
          { id: "half", label: "2 of 4 equal parts" },
          { id: "quarter", label: "1 of 4 equal parts" },
          { id: "threeq", label: "3 of 4 equal parts" },
        ],
        { half: "f12", quarter: "f14", threeq: "f34" },
        "l1_equal_match",
        {
          correct: "Same whole, equal parts — different numerators count different amounts.",
          incorrect: "2/4 = 1/2; 1/4 is one quarter; 3/4 is three quarters.",
          hint: "Read ‘of 4 equal parts’ as denominator 4.",
        },
      ),
    ],
    barScene(
      "l1-equal-final",
      "Mastery check",
      "Shade 3/6 of a bar with 6 equal parts.",
      6,
      3,
      "l1_equal_mastery",
      {
        correct: "3/6 — three equal sixths.",
        incorrect: "Shade three of six equal slices.",
        hint: "Six equal parts; take three.",
      },
    ),
  ),
  lesson(
    "lesson-fractions-level-1-check",
    "Level 1 Check",
    1,
    "beginner",
    [
      barScene(
        "l1-check-half",
        "Quick half",
        "Shade 1/2 of a 6-part bar.",
        6,
        3,
        "l1_check_half",
        {
          correct: "3/6 = 1/2.",
          incorrect: "Half of 6 is 3.",
          hint: "6 ÷ 2 = 3.",
        },
      ),
      mcScene(
        "l1-check-name",
        "Name it",
        "You shaded 4 of 8 equal parts. What fraction?",
        ["4/8", "8/4", "4/4", "8/8"],
        "4/8",
        "l1_check_name",
        {
          correct: "4/8 — four shaded, eight total.",
          incorrect: "Numerator = shaded; denominator = total equal parts.",
          hint: "Shaded first, total second.",
        },
      ),
      nlScene(
        "l1-check-line",
        "On the line",
        "Mark 1/4 on the number line (0 to 1).",
        0,
        1,
        0.125,
        0.25,
        "l1_check_line",
        {
          correct: "1/4 — one quarter of the way from 0 to 1.",
          incorrect: "One step of size 1/4 from zero.",
          hint: "Split 0–1 into four equal jumps.",
        },
      ),
    ],
    matchScene(
      "l1-check-final",
      "Level 1 mastery",
      "Match: combining two 1/8 parts gives which total?",
      [
        { id: "e1a", label: "1/8" },
        { id: "e1b", label: "1/8" },
        { id: "e2", label: "2/8" },
        { id: "e4", label: "4/8" },
      ],
      [
        { id: "p1", label: "First 1/8" },
        { id: "p2", label: "Second 1/8" },
        { id: "tot", label: "Combined" },
      ],
      { p1: "e1a", p2: "e1b", tot: "e2" },
      "l1_check_mastery",
      {
        correct: "1/8 + 1/8 = 2/8 — Level 1 complete!",
        incorrect: "Two eighths combine to 2/8.",
        hint: "Same denominator; add numerators.",
      },
    ),
  ),
] as const;
