import { barScene, lesson, matchScene, mcScene, segScene } from "./_helpers";

/** Level 3 — comparing fractions (numerators, denominators, equivalents). */
export const MATH_FRACTIONS_LEVEL_3_SEEDS = [
  lesson(
    "lesson-fractions-comparing-intro",
    "Comparing Fractions",
    3,
    "beginner",
    [
      barScene("l3-cmp-1", "Shade 2/5", "Shade 2/5 on a 5-part bar.", 5, 2, "l3_cmp_25", {
        correct: "2/5 — two fifths of the whole.",
        incorrect: "Shade two of five parts.",
        hint: "2 shaded, 5 total.",
      }),
      barScene("l3-cmp-2", "Shade 3/5", "Shade 3/5 on a 5-part bar.", 5, 3, "l3_cmp_35", {
        correct: "3/5 — more than 2/5.",
        incorrect: "Shade three of five parts.",
        hint: "Three slices on a five-part bar.",
      }),
      mcScene(
        "l3-cmp-3",
        "Which is larger?",
        "Which is greater: 2/5 or 3/5?",
        ["3/5", "2/5", "They are equal", "Cannot compare"],
        "3/5",
        "l3_cmp_same_den",
        {
          correct: "3/5 > 2/5 — same denominator, larger numerator wins.",
          incorrect: "More fifths means more of the whole.",
          hint: "Same-sized parts; compare shaded counts.",
        },
      ),
    ],
    segScene(
      "l3-cmp-final",
      "Mastery check",
      "Compare 1/4 and 3/4 (same denominator).",
      [
        { id: "a", label: "1/4 < 3/4" },
        { id: "b", label: "1/4 > 3/4" },
        { id: "c", label: "1/4 = 3/4" },
      ],
      "a",
      "l3_cmp_mastery",
      {
        correct: "1/4 < 3/4 — three quarters is more than one.",
        incorrect: "Same denominator 4; compare 1 vs 3.",
        hint: "More fourths → larger fraction.",
      },
    ),
  ),
  lesson(
    "lesson-fractions-comparing-numerators",
    "Comparing Numerators",
    3,
    "beginner",
    [
      mcScene(
        "l3-num-1",
        "Same denominator",
        "Which is greater: 5/8 or 3/8?",
        ["5/8", "3/8", "Equal", "Neither"],
        "5/8",
        "l3_num_58",
        {
          correct: "5/8 > 3/8 — five eighths beats three.",
          incorrect: "Larger numerator with same denominator.",
          hint: "5 > 3.",
        },
      ),
      barScene("l3-num-2", "Model 7/10", "Shade 7/10 on a 10-part bar.", 10, 7, "l3_num_710", {
        correct: "7/10 — a large portion of the whole.",
        incorrect: "Shade seven of ten parts.",
        hint: "Seven slices.",
      }),
      mcScene(
        "l3-num-3",
        "Compare to 1/2",
        "Is 3/8 greater or less than 1/2 (4/8)?",
        ["Less than 1/2", "Greater than 1/2", "Equal to 1/2"],
        "Less than 1/2",
        "l3_num_38half",
        {
          correct: "3/8 < 4/8 = 1/2.",
          incorrect: "3 eighths is less than 4 eighths.",
          hint: "Compare to 4/8.",
        },
      ),
    ],
    mcScene(
      "l3-num-final",
      "Mastery check",
      "Which is smallest: 2/6, 4/6, 5/6?",
      ["2/6", "4/6", "5/6"],
      "2/6",
      "l3_num_mastery",
      {
        correct: "2/6 is smallest — fewest sixths.",
        incorrect: "Same denominator; pick smallest numerator.",
        hint: "2 < 4 < 5.",
      },
    ),
  ),
  lesson(
    "lesson-fractions-comparing-denominators",
    "Comparing Denominators",
    3,
    "beginner",
    [
      mcScene(
        "l3-den-1",
        "Same numerator",
        "Which is larger: 1/3 or 1/5? (Same numerator, different denominators.)",
        ["1/3", "1/5", "Equal", "Neither"],
        "1/3",
        "l3_den_13",
        {
          correct: "1/3 > 1/5 — bigger pieces when the denominator is smaller.",
          incorrect: "Thirds are larger pieces than fifths.",
          hint: "Fewer splits → larger each part.",
        },
      ),
      matchScene(
        "l3-den-2",
        "Order unit fractions",
        "Match the order from smallest to largest piece size.",
        [
          { id: "u12", label: "1/12" },
          { id: "u8", label: "1/8" },
          { id: "u4", label: "1/4" },
        ],
        [
          { id: "small", label: "Smallest piece" },
          { id: "mid", label: "Middle" },
          { id: "large", label: "Largest piece" },
        ],
        { small: "u12", mid: "u8", large: "u4" },
        "l3_den_order",
        {
          correct: "1/12 < 1/8 < 1/4 — more splits → smaller pieces.",
          incorrect: "Smaller denominator → larger unit fraction.",
          hint: "Twelfths are tiny; fourths are big.",
        },
      ),
      mcScene(
        "l3-den-3",
        "Compare 2/3 and 2/7",
        "Which is greater: 2/3 or 2/7?",
        ["2/3", "2/7", "Equal"],
        "2/3",
        "l3_den_23",
        {
          correct: "2/3 > 2/7 — same count, but thirds are bigger pieces.",
          incorrect: "Thirds beat sevenths when numerators match.",
          hint: "Compare piece sizes: 1/3 vs 1/7.",
        },
      ),
    ],
    mcScene(
      "l3-den-final",
      "Mastery check",
      "Which is less: 3/4 or 3/10?",
      ["3/10", "3/4", "Equal"],
      "3/10",
      "l3_den_mastery",
      {
        correct: "3/10 < 3/4 — tenths are smaller pieces.",
        incorrect: "Same numerator; smaller denominator means larger fraction.",
        hint: "1/10 < 1/4.",
      },
    ),
  ),
  lesson(
    "lesson-fractions-comparing-equivalents",
    "Comparing Equivalents",
    3,
    "beginner",
    [
      mcScene(
        "l3-eq-1",
        "Use equivalence",
        "Compare 1/2 and 3/6.",
        ["Equal", "1/2 is greater", "3/6 is greater"],
        "Equal",
        "l3_eq_126",
        {
          correct: "1/2 = 3/6 — equivalent fractions compare equal.",
          incorrect: "3/6 simplifies to 1/2.",
          hint: "Simplify 3/6.",
        },
      ),
      matchScene(
        "l3-eq-2",
        "Common denominator",
        "Compare 1/3 and 2/5 using 15 as common denominator.",
        [
          { id: "a", label: "5/15" },
          { id: "b", label: "6/15" },
          { id: "c", label: "1/3" },
          { id: "d", label: "2/5" },
        ],
        [
          { id: "f13", label: "1/3 as fifteenths" },
          { id: "f25", label: "2/5 as fifteenths" },
        ],
        { f13: "a", f25: "b" },
        "l3_eq_common",
        {
          correct: "1/3 = 5/15 and 2/5 = 6/15 — now compare numerators.",
          incorrect: "5/15 vs 6/15 → 2/5 is larger.",
          hint: "1/3 × 5/5 = 5/15.",
        },
      ),
      mcScene(
        "l3-eq-3",
        "Who wins?",
        "Using 5/15 and 6/15, which original fraction is greater?",
        ["2/5", "1/3", "Equal"],
        "2/5",
        "l3_eq_winner",
        {
          correct: "6/15 > 5/15 so 2/5 > 1/3.",
          incorrect: "6 > 5 on the common denominator.",
          hint: "Larger numerator on fifteenths wins.",
        },
      ),
    ],
    segScene(
      "l3-eq-final",
      "Mastery check",
      "Compare 2/4 and 3/6.",
      [
        { id: "eq", label: "Equal" },
        { id: "a", label: "2/4 is greater" },
        { id: "b", label: "3/6 is greater" },
      ],
      "eq",
      "l3_eq_mastery",
      {
        correct: "2/4 = 3/6 = 1/2.",
        incorrect: "Simplify both fractions.",
        hint: "2/4 = 1/2 and 3/6 = 1/2.",
      },
    ),
  ),
  lesson(
    "lesson-fractions-comparing-more-equivalents",
    "Comparing More Equivalents",
    3,
    "intermediate",
    [
      mcScene(
        "l3-more-1",
        "Cross compare",
        "Which is greater: 3/4 or 5/6?",
        ["5/6", "3/4", "Equal"],
        "5/6",
        "l3_more_34",
        {
          correct: "5/6 > 3/4 — common denominator 12: 9/12 vs 10/12.",
          incorrect: "3/4 = 9/12 and 5/6 = 10/12.",
          hint: "Convert to twelfths.",
        },
      ),
      matchScene(
        "l3-more-2",
        "Match on twelfths",
        "Place 3/4 and 5/6 on a common denominator of 12.",
        [
          { id: "n9", label: "9/12" },
          { id: "n10", label: "10/12" },
          { id: "n8", label: "8/12" },
        ],
        [
          { id: "s34", label: "3/4 as twelfths" },
          { id: "s56", label: "5/6 as twelfths" },
        ],
        { s34: "n9", s56: "n10" },
        "l3_more_12",
        {
          correct: "3/4 = 9/12 and 5/6 = 10/12.",
          incorrect: "Multiply 3/4 and 5/6 to denominator 12.",
          hint: "3/4 × 3/3 = 9/12.",
        },
      ),
      barScene("l3-more-3", "Shade 10/12", "Shade 10/12 on a 12-part bar.", 12, 10, "l3_more_shade", {
        correct: "10/12 = 5/6 — the larger fraction in the comparison.",
        incorrect: "Shade ten of twelve parts.",
        hint: "10/12 is five sixths.",
      }),
    ],
    mcScene(
      "l3-more-final",
      "Mastery check",
      "Which is greater: 4/9 or 1/2?",
      ["1/2", "4/9", "Equal"],
      "1/2",
      "l3_more_mastery",
      {
        correct: "1/2 = 4.5/9 > 4/9.",
        incorrect: "Half of 9 is 4.5; 4/9 is less.",
        hint: "1/2 = 4.5/9.",
      },
    ),
  ),
  lesson(
    "lesson-fractions-identifying-greatest",
    "Identifying the Greatest",
    3,
    "intermediate",
    [
      mcScene(
        "l3-max-1",
        "Pick the greatest",
        "Which is greatest: 2/3, 3/5, 1/2?",
        ["2/3", "3/5", "1/2"],
        "2/3",
        "l3_max_set1",
        {
          correct: "2/3 ≈ 0.67 — largest of the three.",
          incorrect: "Compare with common denominator 30: 20/30, 18/30, 15/30.",
          hint: "2/3 is more than two thirds of a half.",
        },
      ),
      matchScene(
        "l3-max-2",
        "Rank three fractions",
        "Match the greatest and least from: 1/4, 3/8, 1/2.",
        [
          { id: "q14", label: "1/4" },
          { id: "q38", label: "3/8" },
          { id: "q12", label: "1/2" },
        ],
        [
          { id: "max", label: "Greatest" },
          { id: "min", label: "Least" },
        ],
        { max: "q12", min: "q14" },
        "l3_max_rank",
        {
          correct: "1/2 greatest; 1/4 least (3/8 in the middle).",
          incorrect: "1/2 = 4/8 > 3/8 > 2/8 = 1/4.",
          hint: "Convert to eighths.",
        },
      ),
      segScene(
        "l3-max-3",
        "Middle value",
        "Which is in the middle: 1/4, 3/8, 1/2?",
        [
          { id: "a", label: "3/8" },
          { id: "b", label: "1/4" },
          { id: "c", label: "1/2" },
        ],
        "a",
        "l3_max_mid",
        {
          correct: "3/8 is between 1/4 (2/8) and 1/2 (4/8).",
          incorrect: "Order: 1/4 < 3/8 < 1/2.",
          hint: "2/8 < 3/8 < 4/8.",
        },
      ),
    ],
    mcScene(
      "l3-max-final",
      "Mastery check",
      "Which is greatest: 5/6, 7/8, 2/3?",
      ["7/8", "5/6", "2/3"],
      "7/8",
      "l3_max_mastery",
      {
        correct: "7/8 is closest to 1 — the greatest.",
        incorrect: "Compare on 24ths: 20/24, 21/24, 16/24.",
        hint: "7/8 leaves only 1/8 below the whole.",
      },
    ),
  ),
] as const;
