import {
  addIntegersLesson,
  lesson,
  levelReviewLesson,
  mcScene,
  sortScene,
  subIntegersLesson,
} from "./_helpers";

/** Level 4 — Subtraction and Addition */
export const MATH_INTEGERS_LEVEL_4_SEEDS = [
  lesson(
    4,
    "adding-the-opposite",
    "Adding The Opposite",
    "beginner",
    [
      mcScene(
        "l4-opp-1",
        "Rewrite",
        "8 − 3 = 8 + (?) ",
        ["−3", "3", "−8", "8"],
        "−3",
        "l4_add_opp",
        { correct: "8 − 3 = 8 + (−3).", incorrect: "Subtract → add opposite.", hint: "−3." },
      ),
      mcScene(
        "l4-opp-2",
        "Negative subtracted",
        "5 − (−2) = 5 + (?) ",
        ["2", "−2", "7", "−7"],
        "2",
        "l4_add_opp2",
        { correct: "5 − (−2) = 5 + 2 = 7.", incorrect: "Minus a negative → plus.", hint: "+2." },
      ),
      mcScene(
        "l4-opp-3",
        "Compute",
        "4 − (−1) = ?",
        ["5", "3", "−5", "−3"],
        "5",
        "l4_add_opp3",
        { correct: "4 + 1 = 5.", incorrect: "Add the opposite.", hint: "5." },
      ),
    ],
    mcScene(
      "l4-opp-final",
      "Mastery check",
      "−2 − (−6) = ?",
      ["4", "−4", "8", "−8"],
      "4",
      "l4_opp_mastery",
      { correct: "−2 + 6 = 4.", incorrect: "−(−6) = +6.", hint: "4." },
    ),
  ),
  addIntegersLesson(4, "subtracting-using-addition", "Subtracting Using Addition", 6, -4),
  subIntegersLesson(4, "subtracting-the-opposite", "Subtracting the Opposite", 3, -5),
  lesson(
    4,
    "order-in-subtraction",
    "Order in Subtraction",
    "intermediate",
    [
      mcScene(
        "l4-order-1",
        "Not commutative",
        "Is 5 − 3 the same as 3 − 5?",
        ["No", "Yes", "Sometimes", "Only for positives"],
        "No",
        "l4_order_sub",
        { correct: "5 − 3 = 2 but 3 − 5 = −2.", incorrect: "Order matters in subtraction.", hint: "Try both." },
      ),
      mcScene(
        "l4-order-2",
        "Compare",
        "Which is larger: 7 − 2 or 2 − 7?",
        ["7 − 2", "2 − 7", "Equal", "Cannot tell"],
        "7 − 2",
        "l4_order_compare",
        { correct: "5 > −5.", incorrect: "7 − 2 = 5.", hint: "Compute each." },
      ),
      sortScene(
        "l4-order-3",
        "Steps to subtract",
        "Order the steps: rewrite 9 − (−4) as addition, then compute.",
        ["9 + 4", "9 − (−4)", "Compute 13", "Flip −4 to +4"],
        ["9 − (−4)", "Flip −4 to +4", "9 + 4", "Compute 13"],
        "l4_order_steps",
        {
          correct: "Rewrite, flip sign, add, compute.",
          incorrect: "First rewrite as addition.",
          hint: "Start with the expression.",
        },
      ),
    ],
    mcScene(
      "l4-order-final",
      "Mastery check",
      "3 − 8 vs 8 − 3 — which equals −5?",
      ["3 − 8", "8 − 3", "Both", "Neither"],
      "3 − 8",
      "l4_order_mastery",
      { correct: "3 − 8 = −5.", incorrect: "Smaller minus larger → negative.", hint: "3 − 8." },
    ),
  ),
  addIntegersLesson(4, "adding-in-any-order", "Adding in Any Order", -3, 8),
  levelReviewLesson(4, "level-review", "Level Review", [
    { prompt: "10 − 4 as addition?", choices: ["10 + (−4)", "10 + 4", "−10 + 4", "4 + 10"], answer: "10 + (−4)" },
    { prompt: "7 − (−3) = ?", choices: ["10", "4", "−10", "−4"], answer: "10" },
    { prompt: "Is a − b = b − a?", choices: ["No", "Yes", "Always zero", "Only if a = b"], answer: "No" },
    { prompt: "−1 + 6 + (−2) = ?", choices: ["3", "−3", "9", "−9"], answer: "3" },
  ]),
];
