import {
  addIntegersLesson,
  expressionOrderLesson,
  levelReviewLesson,
  lesson,
  mcScene,
  sortScene,
} from "./_helpers";

/** Level 8 — Order in Expressions */
export const MATH_INTEGERS_LEVEL_8_SEEDS = [
  expressionOrderLesson(
    8,
    "order-and-addition",
    "Order and Addition",
    ["−5", "+3", "−2", "+7"],
    ["−5", "−2", "+3", "+7"],
    "−3 + 8 + (−2) = ?",
    "3",
    ["3", "−3", "13", "−13"],
  ),
  expressionOrderLesson(
    8,
    "order-and-subtraction",
    "Order and Subtraction",
    ["Rewrite −4 − 3", "As −4 + (−3)", "Combine", "Compute −7"],
    ["Rewrite −4 − 3", "As −4 + (−3)", "Combine", "Compute −7"],
    "6 − 9 − 2 = ?",
    "−5",
    ["−5", "5", "−1", "1"],
  ),
  lesson(
    8,
    "rewriting-subtraction-as-addition",
    "Rewriting Subtraction as Addition",
    "intermediate",
    [
      mcScene(
        "l8-rew-1",
        "Single flip",
        "12 − 5 = 12 + (?) ",
        ["−5", "5", "−12", "7"],
        "−5",
        "l8_rewrite",
        { correct: "12 + (−5) = 7.", incorrect: "Add the opposite.", hint: "−5." },
      ),
      mcScene(
        "l8-rew-2",
        "Chain",
        "3 − 7 − 2 rewritten as addition?",
        ["3 + (−7) + (−2)", "3 + 7 + 2", "3 − 7 + 2", "−3 − 7 − 2"],
        "3 + (−7) + (−2)",
        "l8_rewrite2",
        { correct: "Each subtraction becomes + opposite.", incorrect: "Flip every subtracted term.", hint: "All + opposites." },
      ),
      sortScene(
        "l8-rew-3",
        "Steps",
        "Order steps to evaluate 1 − (−4).",
        ["1 − (−4)", "1 + 4", "Compute 5"],
        ["1 − (−4)", "1 + 4", "Compute 5"],
        "l8_rewrite_steps",
        { correct: "Rewrite, then add.", incorrect: "Flip −4 to +4 first.", hint: "Expression → rewrite → compute." },
      ),
    ],
    mcScene(
      "l8-rew-final",
      "Mastery check",
      "−2 − (−8) = ?",
      ["6", "−6", "10", "−10"],
      "6",
      "l8_rewrite_mastery",
      { correct: "−2 + 8 = 6.", incorrect: "−(−8) = +8.", hint: "6." },
    ),
  ),
  addIntegersLesson(8, "strategic-rearrangement", "Strategic Rearrangement", -6, 10),
  lesson(
    8,
    "longer-expressions",
    "Longer Expressions",
    "intermediate",
    [
      mcScene(
        "l8-long-1",
        "Group first",
        "−1 + 4 + (−3) + 6 = ?",
        ["6", "−6", "14", "−14"],
        "6",
        "l8_long1",
        { correct: "(−1 + −3) + (4 + 6) = −4 + 10 = 6.", incorrect: "Group negatives and positives.", hint: "6." },
      ),
      mcScene(
        "l8-long-2",
        "With subtraction",
        "5 − 8 + 3 − 1 = ?",
        ["−1", "1", "−15", "15"],
        "−1",
        "l8_long2",
        { correct: "5 + (−8) + 3 + (−1) = −1.", incorrect: "Rewrite all subtractions.", hint: "−1." },
      ),
      mcScene(
        "l8-long-3",
        "Cancel opposites",
        "−7 + 2 + 7 + (−2) = ?",
        ["0", "14", "−14", "4"],
        "0",
        "l8_long3",
        { correct: "−7 + 7 = 0 and 2 + (−2) = 0.", incorrect: "Pair opposites.", hint: "Everything cancels." },
      ),
    ],
    mcScene(
      "l8-long-final",
      "Mastery check",
      "−4 + 9 − 6 + 1 = ?",
      ["0", "−2", "2", "−20"],
      "0",
      "l8_long_mastery",
      { correct: "5 − 6 + 1 = 0.", incorrect: "Work left to right or group.", hint: "0." },
    ),
  ),
  levelReviewLesson(8, "level-review", "Level Review", [
    { prompt: "−2 + 5 + (−8) = ?", choices: ["−5", "5", "−15", "15"], answer: "−5" },
    { prompt: "4 − (−3) = ?", choices: ["7", "1", "−7", "−1"], answer: "7" },
    { prompt: "Order helps because…", choices: ["You can group friendly pairs", "Subtraction changes", "Zero disappears", "Signs flip randomly"], answer: "You can group friendly pairs" },
    { prompt: "−3 − 4 − (−2) = ?", choices: ["−5", "5", "−9", "9"], answer: "−5" },
  ]),
];
