import { distanceLesson, levelReviewLesson, lesson, mcScene } from "./_helpers";

/** Level 7 — Distance */
export const MATH_INTEGERS_LEVEL_7_SEEDS = [
  distanceLesson(7, "distance-between-integers", "Distance Between Integers", 2, 8),
  lesson(
    7,
    "a-pair-at-every-distance",
    "A Pair at Every Distance",
    "intermediate",
    [
      mcScene(
        "l7-pair-1",
        "Two points",
        "Distance 3 from 0: which pair works?",
        ["3 and −3", "3 and 0", "0 and −3", "3 and 3"],
        "3 and −3",
        "l7_pair",
        { correct: "Both are 3 units from 0.", incorrect: "Opposites at distance 3.", hint: "±3." },
      ),
      mcScene(
        "l7-pair-2",
        "Not from zero",
        "Points 2 apart: which pair?",
        ["5 and 3", "5 and −5", "3 and 3", "0 and 2"],
        "5 and 3",
        "l7_pair2",
        { correct: "|5 − 3| = 2.", incorrect: "Difference of 2.", hint: "5 and 3." },
      ),
      mcScene(
        "l7-pair-3",
        "Count pairs",
        "How many integer pairs have distance 4 from each other and include 1?",
        ["2", "1", "4", "0"],
        "2",
        "l7_pair3",
        { correct: "1 with 5 and 1 with −3.", incorrect: "1 ± 4.", hint: "5 and −3." },
      ),
    ],
    mcScene(
      "l7-pair-final",
      "Mastery check",
      "Distance 6 from −1 includes which value?",
      ["5", "6", "0", "−6"],
      "5",
      "l7_pair_mastery",
      { correct: "−1 + 6 = 5 or −1 − 6 = −7.", incorrect: "5 is 6 from −1.", hint: "5." },
    ),
  ),
  distanceLesson(7, "subtracting-to-find-distance", "Subtracting to Find Distance", -4, 3),
  distanceLesson(7, "absolute-value-and-distance", "Absolute Value and Distance", -6, 2),
  lesson(
    7,
    "reasoning-about-distance",
    "Reasoning About Distance",
    "intermediate",
    [
      mcScene(
        "l7-reason-1",
        "Same distance",
        "a and b have distance 0. Then a…",
        ["Equals b", "Is opposite of b", "Is 0", "Is positive"],
        "Equals b",
        "l7_dist_zero",
        { correct: "Zero distance → same point.", incorrect: "a = b.", hint: "Same location." },
      ),
      mcScene(
        "l7-reason-2",
        "Midpoint intuition",
        "Integers 2 apart centered at 0?",
        ["−1 and 1", "−2 and 2", "0 and 2", "−1 and 0"],
        "−1 and 1",
        "l7_dist_mid",
        { correct: "−1 and 1 are 2 apart, symmetric.", incorrect: "Symmetric about 0.", hint: "−1 and 1." },
      ),
      mcScene(
        "l7-reason-3",
        "Find unknown",
        "Distance from 4 to x is 3. x could be…",
        ["7 or 1", "7 only", "1 only", "3"],
        "7 or 1",
        "l7_dist_unknown",
        { correct: "4 + 3 = 7, 4 − 3 = 1.", incorrect: "Add/subtract the distance.", hint: "7 or 1." },
      ),
    ],
    mcScene(
      "l7-reason-final",
      "Mastery check",
      "|−2 − 5| = ?",
      ["7", "−7", "3", "−3"],
      "7",
      "l7_reason_mastery",
      { correct: "|−7| = 7.", incorrect: "−2 − 5 = −7.", hint: "7." },
    ),
  ),
  levelReviewLesson(7, "level-review", "Level Review", [
    { prompt: "Distance 3 to 8?", choices: ["5", "11", "−5", "3"], answer: "5" },
    { prompt: "|−4 − 1| = ?", choices: ["5", "−5", "3", "−3"], answer: "5" },
    { prompt: "Distance 0 means?", choices: ["Same point", "Opposites", "Positive", "Zero only"], answer: "Same point" },
    { prompt: "Distance from −3 to 2?", choices: ["5", "−5", "1", "−1"], answer: "5" },
  ]),
];
