import {
  absValueLesson,
  levelReviewLesson,
  lesson,
  mcScene,
  orderIntegersLesson,
} from "./_helpers";

/** Level 6 — Order and Absolute Value */
export const MATH_INTEGERS_LEVEL_6_SEEDS = [
  orderIntegersLesson(6, "ordering-integers", "Ordering Integers", [3, -1, 0, 5]),
  orderIntegersLesson(6, "ordering-negatives", "Ordering Negatives", [-2, -7, -1, -4]),
  absValueLesson(6, "absolute-value", "Absolute Value", -8),
  lesson(
    6,
    "adding-and-absolute-value",
    "Adding and Absolute Value",
    "intermediate",
    [
      mcScene(
        "l6-addabs-1",
        "Sum then abs",
        "|−3 + 5| = ?",
        ["2", "−2", "8", "−8"],
        "2",
        "l6_add_abs",
        { correct: "−3 + 5 = 2, |2| = 2.", incorrect: "Compute inside first.", hint: "2." },
      ),
      mcScene(
        "l6-addabs-2",
        "Different grouping",
        "|−3| + |5| = ?",
        ["8", "2", "−8", "−2"],
        "8",
        "l6_add_abs2",
        { correct: "3 + 5 = 8.", incorrect: "|−3| = 3, |5| = 5.", hint: "8." },
      ),
      mcScene(
        "l6-addabs-3",
        "Compare",
        "Is |−4 + 1| equal to |−4| + |1|?",
        ["No", "Yes", "Always", "Never defined"],
        "No",
        "l6_add_abs3",
        { correct: "|−3| = 3 but 4 + 1 = 5.", incorrect: "Order of | | matters.", hint: "3 ≠ 5." },
      ),
    ],
    mcScene(
      "l6-addabs-final",
      "Mastery check",
      "|−6 + 2| = ?",
      ["4", "−4", "8", "−8"],
      "4",
      "l6_addabs_mastery",
      { correct: "|−4| = 4.", incorrect: "−6 + 2 = −4 first.", hint: "4." },
    ),
  ),
  lesson(
    6,
    "absolute-value-inequalities",
    "Absolute Value Inequalities",
    "intermediate",
    [
      mcScene(
        "l6-ineq-1",
        "Within distance",
        "|x| < 3 means x is…",
        ["Between −3 and 3", "Greater than 3", "Less than −3", "Exactly 3"],
        "Between −3 and 3",
        "l6_abs_ineq",
        { correct: "Closer than 3 units from 0.", incorrect: "Strictly inside −3 and 3.", hint: "−3 < x < 3." },
      ),
      mcScene(
        "l6-ineq-2",
        "Far from zero",
        "|x| > 2 means…",
        ["x > 2 or x < −2", "x between −2 and 2", "x = 2", "x = −2"],
        "x > 2 or x < −2",
        "l6_abs_ineq2",
        { correct: "More than 2 units from 0.", incorrect: "Outside the −2 to 2 band.", hint: "Both tails." },
      ),
      mcScene(
        "l6-ineq-3",
        "Which satisfies |x| ≤ 1?",
        "Which value satisfies |x| ≤ 1?",
        ["0", "2", "−3", "5"],
        "0",
        "l6_abs_ineq3",
        { correct: "|0| = 0 ≤ 1.", incorrect: "Distance from 0 at most 1.", hint: "0 works." },
      ),
    ],
    mcScene(
      "l6-ineq-final",
      "Mastery check",
      "Which value satisfies |x| < 4?",
      ["−2", "5", "−5", "4"],
      "−2",
      "l6_ineq_mastery",
      { correct: "|−2| = 2 < 4.", incorrect: "Check distance from 0.", hint: "−2." },
    ),
  ),
  lesson(
    6,
    "reasoning-with-absolute-value",
    "Reasoning with Absolute Value",
    "intermediate",
    [
      mcScene(
        "l6-reason-1",
        "Same distance",
        "|a| = |b| means a and b are…",
        ["Same distance from 0", "Equal", "Both positive", "Both negative"],
        "Same distance from 0",
        "l6_abs_reason",
        { correct: "Could be opposites, e.g. 3 and −3.", incorrect: "Equal distance, not necessarily equal.", hint: "Mirror across 0." },
      ),
      mcScene(
        "l6-reason-2",
        "Solve |x| = 5",
        "Solutions to |x| = 5?",
        ["5 and −5", "5 only", "−5 only", "0"],
        "5 and −5",
        "l6_abs_solve",
        { correct: "Both 5 and −5 are 5 units from 0.", incorrect: "Two solutions.", hint: "±5." },
      ),
      mcScene(
        "l6-reason-3",
        "Distance match",
        "|x| = |−4|. What could x be?",
        ["4 or −4", "4 only", "−4 only", "0"],
        "4 or −4",
        "l6_abs_match",
        { correct: "Same absolute value → opposites.", incorrect: "±4.", hint: "4 or −4." },
      ),
    ],
    mcScene(
      "l6-reason-final",
      "Mastery check",
      "|x| = 7 → x = ?",
      ["7 or −7", "7 only", "−7 only", "0"],
      "7 or −7",
      "l6_reason_mastery",
      { correct: "±7.", incorrect: "Two values.", hint: "7 or −7." },
    ),
  ),
  levelReviewLesson(6, "level-review", "Level Review", [
    { prompt: "Order: −3, 1, −5", choices: ["−5, −3, 1", "1, −3, −5", "−3, −5, 1", "1, −5, −3"], answer: "−5, −3, 1" },
    { prompt: "|−9| = ?", choices: ["9", "−9", "0", "18"], answer: "9" },
    { prompt: "|−2 + 3| = ?", choices: ["1", "−1", "5", "−5"], answer: "1" },
    { prompt: "|x| < 2 includes?", choices: ["1", "3", "−3", "2"], answer: "1" },
  ]),
];
