import { levelReviewLesson, lesson, mcScene, negativeCoefLesson, sortScene } from "./_helpers";

/** Level 6 — Solving with negatives */
export const ALGEBRA_LINEQ_LEVEL_6_SEEDS = [
  negativeCoefLesson(6, "negative-solutions", "Negative Solutions", -4, 1, 9),
  negativeCoefLesson(6, "subtraction-and-negative-coefficients", "Subtraction and Negative Coefficients", -3, -2, 10),
  lesson(
    6,
    "rewriting-negative-x",
    "Rewriting -x",
    "intermediate",
    [
      mcScene(
        "l6-rewx-1",
        "Meaning",
        "−x equals…",
        ["−1 · x", "x − 1", "1 − x", "x + (−x)"],
        "−1 · x",
        "l6_rewx_mean",
        { correct: "−x = (−1)x.", incorrect: "Coefficient −1.", hint: "−1 · x." },
      ),
      mcScene(
        "l6-rewx-2",
        "Solve",
        "−x = 6 → x = ?",
        ["−6", "6", "1/6", "−1/6"],
        "−6",
        "l6_rewx_solve",
        { correct: "Multiply both sides by −1: x = −6.", incorrect: "Divide or multiply by −1.", hint: "−6." },
      ),
      mcScene(
        "l6-rewx-3",
        "Equivalent",
        "−x = 6 is equivalent to x = ?",
        ["−6", "6", "−x − 6 = 0", "x + 6 = 0"],
        "−6",
        "l6_rewx_equiv",
        { correct: "x = −6.", incorrect: "Solve for x.", hint: "−6." },
      ),
    ],
    mcScene(
      "l6-rewx-final",
      "Mastery check",
      "−2x = 8 → x = ?",
      ["−4", "4", "−16", "16"],
      "−4",
      "l6_rewx_mastery",
      { correct: "x = −4.", incorrect: "Divide by −2.", hint: "−4." },
    ),
  ),
  lesson(
    6,
    "combining-negatives",
    "Combining Negatives",
    "intermediate",
    [
      mcScene(
        "l6-combn-1",
        "Sum",
        "−4x + 2x = ?",
        ["−2x", "6x", "−6x", "2x"],
        "−2x",
        "l6_combn_sum",
        { correct: "−4 + 2 = −2.", incorrect: "Add coefficients.", hint: "−2x." },
      ),
      sortScene(
        "l6-combn-2",
        "Steps",
        "Order: solve −3x + 6 = 0.",
        ["x = −2", "Subtract 6", "Divide by −3", "−3x = −6"],
        ["Subtract 6", "−3x = −6", "Divide by −3", "x = −2"],
        "l6_combn_steps",
        { correct: "Isolate, then divide.", incorrect: "Undo +6 then ÷(−3).", hint: "Subtract 6 first." },
      ),
      mcScene(
        "l6-combn-3",
        "Both sides",
        "−x + 5 = x + 1 → combine →",
        ["−2x = −4", "2x = 4", "x = 2", "−x = −4"],
        "−2x = −4",
        "l6_combn_both",
        { correct: "Subtract x: −2x + 5 = 1 → −2x = −4.", incorrect: "Move x terms one side.", hint: "−2x = −4." },
      ),
    ],
    mcScene(
      "l6-combn-final",
      "Mastery check",
      "−2x = −4 → x = ?",
      ["2", "−2", "8", "−8"],
      "2",
      "l6_combn_mastery",
      { correct: "x = 2.", incorrect: "Divide by −2.", hint: "2." },
    ),
  ),
  levelReviewLesson(6, "level-review", "Level Review", [
    { prompt: "−5x + 3 = −7 → first move?", choices: ["Subtract 3", "Add 5x", "Divide by 5", "Square"], answer: "Subtract 3" },
    { prompt: "−x = −9 → x = ?", choices: ["9", "−9", "1/9", "−1/9"], answer: "9" },
    { prompt: "−3 + (−4) = ?", choices: ["−7", "7", "−1", "1"], answer: "−7" },
    { prompt: "Product of two negatives is…", choices: ["Positive", "Negative", "Zero", "Undefined"], answer: "Positive" },
  ]),
];
