import { distributeLesson, levelReviewLesson, lesson, mcScene, sortScene } from "./_helpers";

/** Level 8 — Distributing */
export const ALGEBRA_LINEQ_LEVEL_8_SEEDS = [
  lesson(
    8,
    "multiples",
    "Multiples",
    "beginner",
    [
      mcScene(
        "l8-mult-1",
        "Repeated addition",
        "3(x + 2) means…",
        ["3 copies of (x + 2)", "3 + x + 2", "x + 6", "3x + 2 only"],
        "3 copies of (x + 2)",
        "l8_mult_mean",
        { correct: "Multiply the group by 3.", incorrect: "Distributive idea.", hint: "3 copies." },
      ),
      mcScene(
        "l8-mult-2",
        "Expand",
        "3(x + 2) = ?",
        ["3x + 6", "3x + 2", "x + 6", "5x"],
        "3x + 6",
        "l8_mult_expand",
        { correct: "3·x + 3·2 = 3x + 6.", incorrect: "Distribute 3.", hint: "3x + 6." },
      ),
      mcScene(
        "l8-mult-3",
        "Factor back",
        "3x + 6 = ?",
        ["3(x + 2)", "3(x + 6)", "x(3 + 6)", "6(x + 3)"],
        "3(x + 2)",
        "l8_mult_factor",
        { correct: "GCF 3.", incorrect: "Factor out 3.", hint: "3(x + 2)." },
      ),
    ],
    mcScene(
      "l8-mult-final",
      "Mastery check",
      "2(x + 5) = ?",
      ["2x + 10", "2x + 5", "x + 10", "7x"],
      "2x + 10",
      "l8_mult_mastery",
      { correct: "2x + 10.", incorrect: "Distribute 2.", hint: "2x + 10." },
    ),
  ),
  distributeLesson(8, "distributing", "Distributing", 4, 3, 28),
  distributeLesson(8, "distributing-with-negatives", "Distributing with Negatives", -2, 5, 8),
  distributeLesson(8, "distributing-to-solve", "Distributing to Solve", 3, 4, 21),
  lesson(
    8,
    "distribute-or-divide",
    "Distribute or Divide",
    "intermediate",
    [
      mcScene(
        "l8-dod-1",
        "Choice",
        "6x + 12 = 30. Efficient first step?",
        ["Divide all terms by 6", "Add 12", "Subtract x", "Square both sides"],
        "Divide all terms by 6",
        "l8_dod_choice",
        { correct: "Common factor 6 on left.", incorrect: "Sometimes divide first.", hint: "Divide by 6." },
      ),
      mcScene(
        "l8-dod-2",
        "After divide",
        "6x + 12 = 30 → divide by 6 →",
        ["x + 2 = 5", "x + 12 = 5", "6x = 18", "x = 5"],
        "x + 2 = 5",
        "l8_dod_after",
        { correct: "Each term ÷ 6.", incorrect: "x + 2 = 5.", hint: "x + 2 = 5." },
      ),
      mcScene(
        "l8-dod-3",
        "Finish",
        "x + 2 = 5 → x = ?",
        ["3", "7", "2.5", "10"],
        "3",
        "l8_dod_finish",
        { correct: "x = 3.", incorrect: "Subtract 2.", hint: "3." },
      ),
    ],
    mcScene(
      "l8-dod-final",
      "Mastery check",
      "4(x − 1) = 20 → divide by 4 first gives?",
      ["x − 1 = 5", "x = 5", "4x = 21", "x − 4 = 5"],
      "x − 1 = 5",
      "l8_dod_mastery",
      { correct: "x − 1 = 5.", incorrect: "Divide every term.", hint: "x − 1 = 5." },
    ),
  ),
  distributeLesson(8, "more-distributing-to-solve", "More Distributing to Solve", 5, -2, 15),
  lesson(
    8,
    "combining-groups",
    "Combining Groups",
    "intermediate",
    [
      mcScene(
        "l8-cg-1",
        "Two groups",
        "2(x + 1) + 3(x + 2) → first step?",
        ["Distribute both", "Add 2 + 3", "Divide by x", "Remove parentheses only"],
        "Distribute both",
        "l8_cg_step",
        { correct: "Expand each group.", incorrect: "Distribute 2 and 3.", hint: "Distribute both." },
      ),
      mcScene(
        "l8-cg-2",
        "Expanded",
        "2(x + 1) + 3(x + 2) = ?",
        ["5x + 8", "5x + 3", "6x + 8", "5x + 6"],
        "5x + 8",
        "l8_cg_expanded",
        { correct: "2x + 2 + 3x + 6 = 5x + 8.", incorrect: "Combine like terms.", hint: "5x + 8." },
      ),
      sortScene(
        "l8-cg-3",
        "Order",
        "Order: solve 2(x + 1) + 3(x + 2) = 18.",
        ["5x + 8 = 18", "Distribute", "5x = 10", "x = 2"],
        ["Distribute", "5x + 8 = 18", "5x = 10", "x = 2"],
        "l8_cg_order",
        { correct: "Expand, combine, solve.", incorrect: "Distribute first.", hint: "Distribute first." },
      ),
    ],
    mcScene(
      "l8-cg-final",
      "Mastery check",
      "5x + 8 = 18 → x = ?",
      ["2", "3.6", "10", "26"],
      "2",
      "l8_cg_mastery",
      { correct: "x = 2.", incorrect: "5x = 10.", hint: "2." },
    ),
  ),
  levelReviewLesson(8, "level-review", "Level Review", [
    { prompt: "a(b + c) = ?", choices: ["ab + ac", "ab + c", "a + bc", "abc"], answer: "ab + ac" },
    { prompt: "−2(x − 3) = ?", choices: ["−2x + 6", "−2x − 6", "−2x + 3", "x − 6"], answer: "−2x + 6" },
    { prompt: "3(x + 4) = 21 → x = ?", choices: ["3", "7", "5", "17"], answer: "3" },
    { prompt: "GCF of 4x and 8?", choices: ["4", "8", "x", "4x"], answer: "4" },
  ]),
];
