import { levelReviewLesson, lesson, mcScene, sortScene } from "./_helpers";

/** Level 11 — Working with fractions */
export const ALGEBRA_LINEQ_LEVEL_11_SEEDS = [
  lesson(
    11,
    "reciprocals",
    "Reciprocals",
    "intermediate",
    [
      mcScene(
        "l11-rec-1",
        "Definition",
        "Reciprocal of 4 is…",
        ["1/4", "4", "−4", "0"],
        "1/4",
        "l11_rec_def",
        { correct: "1 ÷ 4 = 1/4.", incorrect: "Flip the number.", hint: "1/4." },
      ),
      mcScene(
        "l11-rec-2",
        "Multiply",
        "4 × (1/4) = ?",
        ["1", "4", "1/16", "0"],
        "1",
        "l11_rec_mult",
        { correct: "Number times reciprocal = 1.", incorrect: "4 × 1/4 = 1.", hint: "1." },
      ),
      mcScene(
        "l11-rec-3",
        "Solve",
        "(1/3)x = 4 → multiply both sides by…",
        ["3", "1/3", "4", "12"],
        "3",
        "l11_rec_solve",
        { correct: "Multiply by reciprocal 3.", incorrect: "Undo ÷3.", hint: "3." },
      ),
    ],
    mcScene(
      "l11-rec-final",
      "Mastery check",
      "(1/2)x = 6 → x = ?",
      ["12", "3", "6", "1/12"],
      "12",
      "l11_rec_mastery",
      { correct: "x = 12.", incorrect: "Multiply by 2.", hint: "12." },
    ),
  ),
  lesson(
    11,
    "same-denominator",
    "Same Denominator",
    "intermediate",
    [
      mcScene(
        "l11-sd-1",
        "Add fractions",
        "x/5 + 2/5 = ?",
        ["(x + 2)/5", "(x + 2)/10", "x/10 + 2/5", "2x/5"],
        "(x + 2)/5",
        "l11_sd_add",
        { correct: "Same denominator — add numerators.", incorrect: "(x+2)/5.", hint: "(x + 2)/5." },
      ),
      mcScene(
        "l11-sd-2",
        "Solve",
        "x/5 + 2/5 = 3 → x = ?",
        ["13", "3", "5", "15"],
        "13",
        "l11_sd_solve",
        { correct: "(x+2)/5 = 3 → x+2 = 15 → x = 13.", incorrect: "Multiply by 5.", hint: "13." },
      ),
      mcScene(
        "l11-sd-3",
        "Clear denom",
        "Multiply both sides by 5 to clear…",
        ["The denominator", "The numerator only", "x only", "Nothing"],
        "The denominator",
        "l11_sd_clear",
        { correct: "Clear fractions with LCD.", incorrect: "Multiply by 5.", hint: "Denominator." },
      ),
    ],
    mcScene(
      "l11-sd-final",
      "Mastery check",
      "x/4 = 3 → x = ?",
      ["12", "7", "3", "1/12"],
      "12",
      "l11_sd_mastery",
      { correct: "x = 12.", incorrect: "×4 both sides.", hint: "12." },
    ),
  ),
  lesson(
    11,
    "different-denominators",
    "Different Denominators",
    "intermediate",
    [
      mcScene(
        "l11-dd-1",
        "LCD",
        "LCD of 2 and 3?",
        ["6", "5", "2", "3"],
        "6",
        "l11_dd_lcd",
        { correct: "Least common multiple 6.", incorrect: "LCM of 2 and 3.", hint: "6." },
      ),
      mcScene(
        "l11-dd-2",
        "Convert",
        "1/2 + 1/3 = ?",
        ["5/6", "2/5", "1/5", "2/3"],
        "5/6",
        "l11_dd_convert",
        { correct: "3/6 + 2/6 = 5/6.", incorrect: "Common denominator 6.", hint: "5/6." },
      ),
      mcScene(
        "l11-dd-3",
        "Equation",
        "x/2 + x/3 = 5 → LCD 6 gives…",
        ["3x + 2x = 30", "x + x = 5", "5x = 5", "6x = 5"],
        "3x + 2x = 30",
        "l11_dd_eq",
        { correct: "Multiply each term by 6.", incorrect: "3x + 2x = 30.", hint: "3x + 2x = 30." },
      ),
    ],
    mcScene(
      "l11-dd-final",
      "Mastery check",
      "5x = 30 → x = ?",
      ["6", "5", "30", "150"],
      "6",
      "l11_dd_mastery",
      { correct: "x = 6.", incorrect: "Divide by 5.", hint: "6." },
    ),
  ),
  lesson(
    11,
    "eliminating-denominators",
    "Eliminating Denominators",
    "intermediate",
    [
      sortScene(
        "l11-ed-1",
        "Steps",
        "Order: solve x/3 + 1 = 4.",
        ["x = 9", "Multiply by 3", "x + 3 = 12", "x/3 = 3"],
        ["x/3 = 3", "Multiply by 3", "x + 3 = 12", "x = 9"],
        "l11_ed_steps",
        { correct: "Isolate fraction, clear, solve.", incorrect: "Subtract 1 first.", hint: "x/3 = 3 first." },
      ),
      mcScene(
        "l11-ed-2",
        "Why multiply",
        "Multiply by LCD to…",
        ["Remove fractions", "Make x bigger", "Add denominators", "Graph"],
        "Remove fractions",
        "l11_ed_why",
        { correct: "Clear denominators.", incorrect: "LCD clears fractions.", hint: "Remove fractions." },
      ),
      mcScene(
        "l11-ed-3",
        "Result",
        "x/2 = 7 → x = ?",
        ["14", "7", "3.5", "9"],
        "14",
        "l11_ed_result",
        { correct: "x = 14.", incorrect: "×2.", hint: "14." },
      ),
    ],
    mcScene(
      "l11-ed-final",
      "Mastery check",
      "(2/3)x = 8 → x = ?",
      ["12", "8", "16/3", "4"],
      "12",
      "l11_ed_mastery",
      { correct: "x = 12.", incorrect: "×3/2.", hint: "12." },
    ),
  ),
  lesson(
    11,
    "fractions-outside-and-inside",
    "Fractions Outside and Inside",
    "intermediate",
    [
      mcScene(
        "l11-foi-1",
        "Both sides",
        "(x + 2)/4 = 3/2 → first step?",
        ["Cross-multiply or ×4", "Add 2", "Divide x", "Ignore fractions"],
        "Cross-multiply or ×4",
        "l11_foi_step",
        { correct: "Clear denominators.", incorrect: "Multiply by 4.", hint: "×4 or cross-multiply." },
      ),
      mcScene(
        "l11-foi-2",
        "Multiply",
        "×4: (x + 2)/4 = 3/2 →",
        ["x + 2 = 6", "x + 2 = 3/2", "4x + 2 = 6", "x = 6"],
        "x + 2 = 6",
        "l11_foi_mult",
        { correct: "4 · (x+2)/4 = 4 · 3/2 → x+2 = 6.", incorrect: "x + 2 = 6.", hint: "x + 2 = 6." },
      ),
      mcScene(
        "l11-foi-3",
        "Solve",
        "x + 2 = 6 → x = ?",
        ["4", "8", "3", "6"],
        "4",
        "l11_foi_solve",
        { correct: "x = 4.", incorrect: "Subtract 2.", hint: "4." },
      ),
    ],
    mcScene(
      "l11-foi-final",
      "Mastery check",
      "x/2 + 1/2 = 2 → x = ?",
      ["3", "2", "4", "1"],
      "3",
      "l11_foi_mastery",
      { correct: "(x+1)/2 = 2 → x+1 = 4 → x = 3.", incorrect: "Clear fractions.", hint: "3." },
    ),
  ),
  levelReviewLesson(11, "level-review", "Level Review", [
    { prompt: "Reciprocal of 1/3?", choices: ["3", "1/3", "−3", "0"], answer: "3" },
    { prompt: "LCD of 4 and 6?", choices: ["12", "24", "2", "10"], answer: "12" },
    { prompt: "x/5 = 2 → x = ?", choices: ["10", "7", "2", "2/5"], answer: "10" },
    { prompt: "Clear fractions by…", choices: ["Multiplying by LCD", "Adding LCD", "Dividing x", "Factoring"], answer: "Multiplying by LCD" },
  ]),
];
