import {
  graphScene,
  lesson,
  mcScene,
  pythagorasSideLesson,
  segScene,
  sortScene,
} from "./_helpers";

/** Level 6 — Pythagoras */
export const ALGEBRA_CGEO_LEVEL_6_SEEDS = [
  lesson(
    6,
    "pythagoras",
    "Pythagoras",
    "beginner",
    [
      mcScene(
        "l6-pyth-1",
        "Right triangle",
        "Pythagorean theorem applies to…",
        ["Right triangles", "All triangles", "Circles only", "Squares only"],
        "Right triangles",
        "l6_pyth_intro",
        { correct: "Needs a 90° angle.", incorrect: "Right triangle only.", hint: "Right triangles." },
      ),
      mcScene(
        "l6-pyth-2",
        "Named for",
        "The theorem a² + b² = c² is named after…",
        ["Pythagoras", "Euclid", "Descartes", "Newton"],
        "Pythagoras",
        "l6_pyth_name",
        { correct: "Ancient Greek mathematician.", incorrect: "Pythagoras.", hint: "Pythagoras." },
      ),
      segScene(
        "l6-pyth-3",
        "Hypotenuse",
        "Which side is the hypotenuse?",
        [
          { id: "hyp", label: "Longest side, opposite the right angle" },
          { id: "leg", label: "Either leg" },
          { id: "alt", label: "The altitude" },
          { id: "base", label: "Always the bottom" },
        ],
        "hyp",
        "l6_pyth_hyp",
        { correct: "Opposite the right angle.", incorrect: "Longest side.", hint: "Hypotenuse." },
      ),
    ],
    mcScene(
      "l6-pyth-final",
      "Mastery check",
      "a² + b² = c² — c is the…",
      ["Hypotenuse", "Shorter leg", "Area", "Perimeter"],
      "Hypotenuse",
      "l6_pyth_mastery",
      { correct: "c is longest.", incorrect: "Hypotenuse.", hint: "Hypotenuse." },
    ),
  ),
  pythagorasSideLesson(6, "pythagoras-theorem", "Pythagoras' Theorem", 3, 4, true),
  lesson(
    6,
    "direct-distance",
    "Direct Distance",
    "intermediate",
    [
      mcScene(
        "l6-dir-1",
        "Diagonal",
        "Walk 6 east and 8 north. Direct distance?",
        ["10", "14", "6", "8"],
        "10",
        "l6_dir_diag",
        { correct: "6-8-10 triangle.", incorrect: "√(36+64) = 10.", hint: "10" },
      ),
      graphScene(
        "l6-dir-2",
        "Plot corner",
        "Plot the corner of a path 6 east and 8 north from (0,0).",
        6,
        8,
        "l6_dir_plot",
        { correct: "(6, 8).", incorrect: "6 right, 8 up.", hint: "(6, 8)" },
        { xMin: 0, xMax: 10, yMin: 0, yMax: 10 },
        [{ x1: 0, y1: 0, x2: 6, y2: 0 }, { x1: 0, y1: 0, x2: 0, y2: 8 }],
      ),
      mcScene(
        "l6-dir-3",
        "Not the sum",
        "Direct distance 6 east + 8 north is NOT…",
        ["14", "10", "√(36+64)", "Hypotenuse"],
        "14",
        "l6_dir_not",
        { correct: "14 = 6+8 is the path length, not direct.", incorrect: "Legs add for path, not diagonal.", hint: "14" },
      ),
    ],
    mcScene(
      "l6-dir-final",
      "Mastery check",
      "Legs 5 and 12 → hypotenuse?",
      ["13", "17", "7", "60"],
      "13",
      "l6_dir_mastery",
      { correct: "5-12-13 triangle.", incorrect: "169 = 25 + 144.", hint: "13" },
    ),
  ),
  lesson(
    6,
    "squares-and-sides",
    "Squares and Sides",
    "intermediate",
    [
      mcScene(
        "l6-sq-1",
        "Square on side",
        "Square on side length 3 has area…",
        ["9", "6", "3", "12"],
        "9",
        "l6_sq_area",
        { correct: "3² = 9.", incorrect: "Side squared.", hint: "9" },
      ),
      mcScene(
        "l6-sq-2",
        "Pythagorean squares",
        "a² + b² = c² means areas of squares on legs sum to…",
        ["Square on hypotenuse", "Perimeter", "One leg", "Zero"],
        "Square on hypotenuse",
        "l6_sq_sum",
        { correct: "Visual proof with squares.", incorrect: "Areas of squares.", hint: "Hypotenuse square." },
      ),
      mcScene(
        "l6-sq-3",
        "Find leg squared",
        "c² = 25, a² = 9 → b² = ?",
        ["16", "34", "9", "25"],
        "16",
        "l6_sq_leg",
        { correct: "25 − 9 = 16.", incorrect: "Subtract squares.", hint: "16" },
      ),
    ],
    mcScene(
      "l6-sq-final",
      "Mastery check",
      "Leg squared 16 → leg = ?",
      ["4", "8", "16", "2"],
      "4",
      "l6_sq_mastery",
      { correct: "√16 = 4.", incorrect: "Square root.", hint: "4" },
    ),
  ),
  lesson(
    6,
    "demonstrating-pythagoras",
    "Demonstrating Pythagoras",
    "intermediate",
    [
      mcScene(
        "l6-demo-1",
        "3-4-5",
        "Verify: 3² + 4² = ?",
        ["25", "7", "12", "5"],
        "25",
        "l6_demo_verify",
        { correct: "9 + 16 = 25 = 5².", incorrect: "Sum of squares.", hint: "25" },
      ),
      sortScene(
        "l6-demo-2",
        "Steps",
        "Order: find legs → square each → sum → square root.",
        ["Square each leg", "Sum the squares", "Take square root of sum", "Identify legs a and b"],
        ["Identify legs a and b", "Square each leg", "Sum the squares", "Take square root of sum"],
        "l6_demo_order",
        { correct: "Standard procedure.", incorrect: "Legs → squares → sum → √.", hint: "Legs first." },
      ),
      graphScene(
        "l6-demo-3",
        "Draw triangle",
        "Plot (3, 4) to complete a 3-4-5 triangle from (0,0).",
        3,
        4,
        "l6_demo_plot",
        { correct: "(3, 4).", incorrect: "3 right, 4 up.", hint: "(3, 4)" },
        { xMin: 0, xMax: 6, yMin: 0, yMax: 6 },
        [{ x1: 0, y1: 0, x2: 3, y2: 0 }, { x1: 0, y1: 0, x2: 0, y2: 4 }],
      ),
    ],
    mcScene(
      "l6-demo-final",
      "Mastery check",
      "Demonstrate: legs 8 and 15 → c = ?",
      ["17", "23", "7", "120"],
      "17",
      "l6_demo_mastery",
      { correct: "8-15-17 triangle.", incorrect: "289 = 64 + 225.", hint: "17" },
    ),
  ),
  lesson(
    6,
    "proving-pythagoras",
    "Proving Pythagoras",
    "intermediate",
    [
      mcScene(
        "l6-prf-1",
        "Rearrangement proof",
        "Four congruent triangles in a square can prove…",
        ["a² + b² = c²", "Area of circle", "Parallel lines", "Slope formula"],
        "a² + b² = c²",
        "l6_prf_rearr",
        { correct: "Classic dissection proof.", incorrect: "Area rearrangement.", hint: "Pythagorean theorem." },
      ),
      mcScene(
        "l6-prf-2",
        "Converse",
        "If a² + b² = c² for sides of a triangle, the triangle is…",
        ["Right", "Equilateral", "Obtuse always", "Impossible"],
        "Right",
        "l6_prf_conv",
        { correct: "Converse of Pythagorean theorem.", incorrect: "Right angle opposite c.", hint: "Right." },
      ),
      mcScene(
        "l6-prf-3",
        "Must be right",
        "Sides 5, 12, 13 form a…",
        ["Right triangle", "Equilateral", "Line", "Circle"],
        "Right triangle",
        "l6_prf_check",
        { correct: "25 + 144 = 169.", incorrect: "5-12-13.", hint: "Right triangle." },
      ),
    ],
    mcScene(
      "l6-prf-final",
      "Mastery check",
      "Proof shows leg squares sum equals…",
      ["Hypotenuse square", "Perimeter", "Smallest side", "Diameter"],
      "Hypotenuse square",
      "l6_prf_mastery",
      { correct: "Area relationship.", incorrect: "Square on c.", hint: "Hypotenuse square." },
    ),
  ),
];
