import {
  lesson,
  levelCheckLesson,
  mcScene,
  rectangleAreaLesson,
  triangleAreaLesson,
} from "./_helpers";

/** Level 3 — Measuring area */
export const ALGEBRA_CGEO_LEVEL_3_SEEDS = [
  lesson(
    3,
    "measuring-area",
    "Measuring Area",
    "beginner",
    [
      mcScene(
        "l3-meas-1",
        "Square units",
        "Area measures…",
        ["Square units covered", "Length only", "Perimeter", "Volume"],
        "Square units covered",
        "l3_meas_intro",
        { correct: "Area counts square units.", incorrect: "Think grid squares.", hint: "Square units." },
      ),
      mcScene(
        "l3-meas-2",
        "Count squares",
        "A 3 × 4 grid covers how many unit squares?",
        ["12", "7", "3", "4"],
        "12",
        "l3_meas_count",
        { correct: "3 × 4 = 12.", incorrect: "Multiply rows × columns.", hint: "12" },
      ),
      mcScene(
        "l3-meas-3",
        "Compare areas",
        "Which shape has greater area?",
        ["4 × 5 rectangle", "3 × 6 rectangle", "Same", "Cannot tell"],
        "4 × 5 rectangle",
        "l3_meas_compare",
        { correct: "20 > 18.", incorrect: "Compare products.", hint: "4 × 5." },
      ),
    ],
    mcScene(
      "l3-meas-final",
      "Mastery check",
      "Area is always in…",
      ["Square units", "Linear units", "Cubic units", "Degrees"],
      "Square units",
      "l3_meas_mastery",
      { correct: "Square units.", incorrect: "Units².", hint: "Square units." },
    ),
  ),
  rectangleAreaLesson(3, "rectangle-area", "Rectangle Area", 4, 5),
  lesson(
    3,
    "calculating-side-lengths",
    "Calculating Side Lengths",
    "beginner",
    [
      mcScene(
        "l3-side-1",
        "Find width",
        "Area = 24, length = 6. Width = ?",
        ["4", "6", "24", "18"],
        "4",
        "l3_side_w",
        { correct: "24 ÷ 6 = 4.", incorrect: "Area ÷ known side.", hint: "4" },
      ),
      mcScene(
        "l3-side-2",
        "Find length",
        "Area = 35, width = 5. Length = ?",
        ["7", "5", "35", "30"],
        "7",
        "l3_side_l",
        { correct: "35 ÷ 5 = 7.", incorrect: "Area ÷ width.", hint: "7" },
      ),
      mcScene(
        "l3-side-3",
        "Grid side",
        "Rectangle area 20 on a grid — possible dimensions?",
        ["4 × 5", "2 × 3", "1 × 1", "20 × 0"],
        "4 × 5",
        "l3_side_grid",
        { correct: "4 × 5 = 20.", incorrect: "Find factor pair.", hint: "4 × 5" },
      ),
    ],
    mcScene(
      "l3-side-final",
      "Mastery check",
      "Area 48, width 8 → length?",
      ["6", "8", "48", "40"],
      "6",
      "l3_side_mastery",
      { correct: "48 ÷ 8 = 6.", incorrect: "Divide.", hint: "6" },
    ),
  ),
  lesson(
    3,
    "absolute-values",
    "Absolute Values",
    "beginner",
    [
      mcScene(
        "l3-abs-1",
        "Side length",
        "A side from x = −2 to x = 3 has length…",
        ["5", "1", "−5", "6"],
        "5",
        "l3_abs_side",
        { correct: "|3 − (−2)| = 5.", incorrect: "Use absolute difference.", hint: "5" },
      ),
      mcScene(
        "l3-abs-2",
        "Height",
        "Vertical side from y = −1 to y = 4 has length…",
        ["5", "3", "−5", "4"],
        "5",
        "l3_abs_h",
        { correct: "|4 − (−1)| = 5.", incorrect: "Absolute difference in y.", hint: "5" },
      ),
      mcScene(
        "l3-abs-3",
        "Rectangle with negatives",
        "Rectangle corners (−2, −1) and (3, 4): width = ?",
        ["5", "1", "7", "3"],
        "5",
        "l3_abs_rect",
        { correct: "|3 − (−2)| = 5.", incorrect: "Width = |Δx|.", hint: "5" },
      ),
    ],
    mcScene(
      "l3-abs-final",
      "Mastery check",
      "From x = −4 to x = 2, horizontal length?",
      ["6", "2", "−6", "8"],
      "6",
      "l3_abs_mastery",
      { correct: "|2 − (−4)| = 6.", incorrect: "Absolute difference.", hint: "6" },
    ),
  ),
  triangleAreaLesson(3, "triangle-area", "Triangle Area", 6, 4),
  lesson(
    3,
    "combining-rectangles",
    "Combining Rectangles",
    "beginner",
    [
      mcScene(
        "l3-comb-1",
        "Add areas",
        "Two rectangles: 3×4 and 2×5. Combined area?",
        ["22", "12", "10", "7"],
        "22",
        "l3_comb_add",
        { correct: "12 + 10 = 22.", incorrect: "Sum the areas.", hint: "22" },
      ),
      mcScene(
        "l3-comb-2",
        "L-shape",
        "L-shape: 4×3 rectangle plus 2×2 rectangle. Total area?",
        ["16", "12", "4", "8"],
        "16",
        "l3_comb_l",
        { correct: "12 + 4 = 16.", incorrect: "Split and add.", hint: "16" },
      ),
      mcScene(
        "l3-comb-3",
        "Subtract overlap",
        "Two overlapping 3×3 squares share a 1×3 strip. Overcount by…",
        ["3", "9", "6", "0"],
        "3",
        "l3_comb_overlap",
        { correct: "Shared strip area 3.", incorrect: "Don't double-count.", hint: "3" },
      ),
    ],
    mcScene(
      "l3-comb-final",
      "Mastery check",
      "5×2 plus 3×4 area?",
      ["22", "10", "12", "26"],
      "22",
      "l3_comb_mastery",
      { correct: "10 + 12 = 22.", incorrect: "Add areas.", hint: "22" },
    ),
  ),
  lesson(
    3,
    "polygon-area",
    "Polygon Area",
    "intermediate",
    [
      mcScene(
        "l3-poly-1",
        "Split shape",
        "Best strategy for irregular polygon area on a grid?",
        ["Split into rectangles/triangles", "Guess", "Perimeter only", "One side"],
        "Split into rectangles/triangles",
        "l3_poly_split",
        { correct: "Decompose into known shapes.", incorrect: "Break apart.", hint: "Split." },
      ),
      mcScene(
        "l3-poly-2",
        "Trapezoid",
        "Trapezoid as average of parallel sides × height: (3+5)/2 × 4 = ?",
        ["16", "32", "8", "20"],
        "16",
        "l3_poly_trap",
        { correct: "4 × 4 = 16.", incorrect: "Average bases × height.", hint: "16" },
      ),
      mcScene(
        "l3-poly-3",
        "Triangle in rectangle",
        "Triangle half of 6×4 rectangle → area?",
        ["12", "24", "6", "10"],
        "12",
        "l3_poly_half",
        { correct: "½ × 24 = 12.", incorrect: "Half the rectangle.", hint: "12" },
      ),
    ],
    mcScene(
      "l3-poly-final",
      "Mastery check",
      "Hexagon on grid — first step?",
      ["Decompose into simpler shapes", "Measure one side", "Ignore", "Use volume"],
      "Decompose into simpler shapes",
      "l3_poly_mastery",
      { correct: "Decompose.", incorrect: "Split the shape.", hint: "Decompose." },
    ),
  ),
];
