import {
  dist,
  lesson,
  mcScene,
  pair,
  separationLesson,
} from "./_helpers";

/** Level 4 — Unknown values (expressions) */
export const ALGEBRA_CGEO_LEVEL_4_SEEDS = [
  lesson(
    4,
    "unknown-values",
    "Unknown Values",
    "beginner",
    [
      mcScene(
        "l4-unk-1",
        "Variable side",
        "A rectangle has width x and length 5. Area expression?",
        ["5x", "x + 5", "5/x", "x²"],
        "5x",
        "l4_unk_intro",
        { correct: "Area = length × width = 5x.", incorrect: "Multiply.", hint: "5x" },
      ),
      mcScene(
        "l4-unk-2",
        "Solve for x",
        "5x = 20 → x = ?",
        ["4", "5", "20", "100"],
        "4",
        "l4_unk_solve",
        { correct: "x = 4.", incorrect: "Divide both sides by 5.", hint: "4" },
      ),
      mcScene(
        "l4-unk-3",
        "Expression distance",
        "Horizontal from x = 2 to x = a (a > 2): distance = ?",
        ["a − 2", "2 − a", "a + 2", "2a"],
        "a − 2",
        "l4_unk_dist",
        { correct: "a − 2 when a > 2.", incorrect: "Difference in x.", hint: "a − 2" },
      ),
    ],
    mcScene(
      "l4-unk-final",
      "Mastery check",
      "Triangle area ½ × b × h with b = x, h = 6?",
      ["3x", "6x", "x + 6", "12x"],
      "3x",
      "l4_unk_mastery",
      { correct: "½ × x × 6 = 3x.", incorrect: "½bh.", hint: "3x" },
    ),
  ),
  separationLesson(4, "distances-with-variables", "Distances with Variables", 0, 0, 3, 4),
  lesson(
    4,
    "rectangle-area-expressions",
    "Rectangle Area Expressions",
    "intermediate",
    [
      mcScene(
        "l4-rect-1",
        "Expression",
        "Length (x + 2), width 4. Area?",
        ["4(x + 2)", "x + 6", "4x + 2", "x + 8"],
        "4(x + 2)",
        "l4_rect_expr",
        { correct: "4(x + 2) = 4x + 8.", incorrect: "Multiply length × width.", hint: "4(x + 2)" },
      ),
      mcScene(
        "l4-rect-2",
        "Expand",
        "4(x + 2) = ?",
        ["4x + 8", "4x + 2", "x + 8", "4x"],
        "4x + 8",
        "l4_rect_expand",
        { correct: "Distribute 4.", incorrect: "4×x + 4×2.", hint: "4x + 8" },
      ),
      mcScene(
        "l4-rect-3",
        "Solve",
        "4x + 8 = 32 → x = ?",
        ["6", "8", "4", "24"],
        "6",
        "l4_rect_solve",
        { correct: "4x = 24 → x = 6.", incorrect: "Subtract 8, divide by 4.", hint: "6" },
      ),
    ],
    mcScene(
      "l4-rect-final",
      "Mastery check",
      "(x + 3)(x + 2) is not area unless…",
      ["Both are side lengths", "Always", "Never valid", "x = 0 only"],
      "Both are side lengths",
      "l4_rect_mastery",
      { correct: "Both factors must be lengths.", incorrect: "Area = product of sides.", hint: "Side lengths." },
    ),
  ),
  lesson(
    4,
    "triangle-area-expressions",
    "Triangle Area Expressions",
    "intermediate",
    [
      mcScene(
        "l4-tri-1",
        "Expression",
        "Base x, height 8. Area?",
        ["4x", "8x", "x + 8", "½x"],
        "4x",
        "l4_tri_expr",
        { correct: "½ × x × 8 = 4x.", incorrect: "½bh.", hint: "4x" },
      ),
      mcScene(
        "l4-tri-2",
        "Both variable",
        "Base x, height y. Area?",
        ["xy/2", "xy", "x + y", "2xy"],
        "xy/2",
        "l4_tri_both",
        { correct: "½xy.", incorrect: "½ × base × height.", hint: "xy/2" },
      ),
      mcScene(
        "l4-tri-3",
        "Solve",
        "4x = 20 → x = ?",
        ["5", "4", "20", "16"],
        "5",
        "l4_tri_solve",
        { correct: "x = 5.", incorrect: "Divide by 4.", hint: "5" },
      ),
    ],
    mcScene(
      "l4-tri-final",
      "Mastery check",
      "Area ½ × 6 × x = 15 → x = ?",
      ["5", "6", "15", "3"],
      "5",
      "l4_tri_mastery",
      { correct: "3x = 15 → x = 5.", incorrect: "3x = 15.", hint: "5" },
    ),
  ),
  lesson(
    4,
    "variable-side-lengths",
    "Variable Side Lengths",
    "intermediate",
    [
      mcScene(
        "l4-var-1",
        "Perimeter",
        "Square side s. Perimeter?",
        ["4s", "s²", "2s", "s + 4"],
        "4s",
        "l4_var_perim",
        { correct: "4 equal sides.", incorrect: "4 × s.", hint: "4s" },
      ),
      mcScene(
        "l4-var-2",
        "Distance expression",
        `From ${pair(0, 0)} to ${pair(3, 4)}: if x-coordinate is a, horizontal leg = ?`,
        ["3", "a", "4", "5"],
        "3",
        "l4_var_leg",
        { correct: "Horizontal leg is 3.", incorrect: "Run = |Δx|.", hint: "3" },
      ),
      mcScene(
        "l4-var-3",
        "Solve side",
        "Rectangle area x(x + 2) = 24 with x = 4 works because…",
        ["4 × 6 = 24", "4 + 6 = 24", "4² = 24", "2 × 4 = 24"],
        "4 × 6 = 24",
        "l4_var_check",
        { correct: "x = 4, x + 2 = 6.", incorrect: "Substitute x = 4.", hint: "4 × 6." },
      ),
    ],
    mcScene(
      "l4-var-final",
      "Mastery check",
      `Distance ${pair(0, 0)} to ${pair(3, 4)} = ?`,
      [String(dist(0, 0, 3, 4)), "7", "3", "4"],
      String(dist(0, 0, 3, 4)),
      "l4_var_mastery",
      { correct: "5 units.", incorrect: "3-4-5 triangle.", hint: "5" },
    ),
  ),
];
