import {
  dist,
  distanceFromOriginLesson,
  graphScene,
  lesson,
  mcScene,
  pair,
  pythagorasSideLesson,
} from "./_helpers";

/** Level 7 — Using Pythagoras */
export const ALGEBRA_CGEO_LEVEL_7_SEEDS = [
  lesson(
    7,
    "using-pythagoras",
    "Using Pythagoras",
    "intermediate",
    [
      mcScene(
        "l7-use-1",
        "When to use",
        "Use Pythagorean theorem when you have…",
        ["A right triangle with two sides known", "Any triangle", "A circle only", "No numbers"],
        "A right triangle with two sides known",
        "l7_use_when",
        { correct: "Right triangle needed.", incorrect: "Two sides → find third.", hint: "Right triangle." },
      ),
      mcScene(
        "l7-use-2",
        "Coordinate plane",
        "Distance between points uses Pythagoras because…",
        ["Horizontal and vertical legs form a right triangle", "All points are right angles", "No reason", "Circles only"],
        "Horizontal and vertical legs form a right triangle",
        "l7_use_coord",
        { correct: "Δx and Δy are legs.", incorrect: "Run and rise.", hint: "Right triangle." },
      ),
      mcScene(
        "l7-use-3",
        "Formula link",
        "Distance √((x₂−x₁)² + (y₂−y₁)²) comes from…",
        ["Pythagorean theorem", "Adding coordinates", "Multiplying", "Absolute value only"],
        "Pythagorean theorem",
        "l7_use_formula",
        { correct: "Legs Δx and Δy.", incorrect: "a² + b² = c².", hint: "Pythagoras." },
      ),
    ],
    mcScene(
      "l7-use-final",
      "Mastery check",
      "Find third side of right triangle: use…",
      ["a² + b² = c²", "a + b = c", "ab = c", "a − b = c"],
      "a² + b² = c²",
      "l7_use_mastery",
      { correct: "Pythagorean theorem.", incorrect: "Not addition.", hint: "a² + b² = c²" },
    ),
  ),
  pythagorasSideLesson(7, "the-unknown-side", "The Unknown Side", 3, 4, false),
  distanceFromOriginLesson(7, "distance-from-the-origin", "Distance from the Origin", 6, 8),
  lesson(
    7,
    "distance-from-the-grid",
    "Distance from the Grid",
    "intermediate",
    [
      mcScene(
        "l7-grid-1",
        "To x-axis",
        "Point (4, −3) distance to x-axis?",
        ["3", "4", "5", "7"],
        "3",
        "l7_grid_xaxis",
        { correct: "|y| = 3.", incorrect: "Vertical distance to axis.", hint: "3" },
      ),
      mcScene(
        "l7-grid-2",
        "To y-axis",
        "Point (−5, 2) distance to y-axis?",
        ["5", "2", "7", "3"],
        "5",
        "l7_grid_yaxis",
        { correct: "|x| = 5.", incorrect: "Horizontal distance.", hint: "5" },
      ),
      graphScene(
        "l7-grid-3",
        "Plot point",
        "Plot (4, −3).",
        4,
        -3,
        "l7_grid_plot",
        { correct: "(4, −3).", incorrect: "4 right, 3 down.", hint: "(4, −3)" },
      ),
    ],
    mcScene(
      "l7-grid-final",
      "Mastery check",
      "(−6, 1) distance to y-axis?",
      ["6", "1", "7", "5"],
      "6",
      "l7_grid_mastery",
      { correct: "|−6| = 6.", incorrect: "|x|.", hint: "6" },
    ),
  ),
  lesson(
    7,
    "distance-from-coordinates",
    "Distance from Coordinates",
    "intermediate",
    [
      mcScene(
        "l7-coord-1",
        "Two points",
        `Distance ${pair(1, 2)} to ${pair(4, 6)}?`,
        [String(dist(1, 2, 4, 6)), "7", "3", "4"],
        String(dist(1, 2, 4, 6)),
        "l7_coord_dist",
        { correct: "√(9+16) = 5.", incorrect: "Δx=3, Δy=4.", hint: "5" },
      ),
      mcScene(
        "l7-coord-2",
        "Horizontal only",
        `Distance ${pair(2, 5)} to ${pair(8, 5)}?`,
        ["6", "13", "3", "5"],
        "6",
        "l7_coord_horiz",
        { correct: "|8−2| = 6.", incorrect: "Same y → horizontal.", hint: "6" },
      ),
      graphScene(
        "l7-coord-3",
        "Plot second",
        `Plot ${pair(4, 6)} given ${pair(1, 2)}.`,
        4,
        6,
        "l7_coord_plot",
        { correct: "(4, 6).", incorrect: "Plot the second point.", hint: "(4, 6)" },
      ),
    ],
    mcScene(
      "l7-coord-final",
      "Mastery check",
      `Distance ${pair(0, 0)} to ${pair(5, 12)}?`,
      ["13", "17", "7", "5"],
      "13",
      "l7_coord_mastery",
      { correct: "5-12-13.", incorrect: "25+144=169.", hint: "13" },
    ),
  ),
];
