import { lesson, matchScene, mcScene, segScene } from "./_helpers";

/** Level 5 — Selecting shapes */
export const ALGEBRA_CGEO_LEVEL_5_SEEDS = [
  lesson(
    5,
    "selecting-shapes-intro",
    "Selecting Shapes",
    "beginner",
    [
      mcScene(
        "l5-sel-1",
        "Pick the shape",
        "A garden is 8 m long and 5 m wide. Best model?",
        ["Rectangle", "Circle", "Triangle only", "Point"],
        "Rectangle",
        "l5_sel_intro",
        { correct: "Length × width rectangle.", incorrect: "Four right angles.", hint: "Rectangle." },
      ),
      mcScene(
        "l5-sel-2",
        "When triangle?",
        "Roof gable with base and height — best shape?",
        ["Triangle", "Rectangle", "Circle", "Line"],
        "Triangle",
        "l5_sel_tri",
        { correct: "Triangle area ½bh.", incorrect: "Peak and base.", hint: "Triangle." },
      ),
      segScene(
        "l5-sel-3",
        "Compound shape",
        "L-shaped floor plan — strategy?",
        [
          { id: "split", label: "Split into rectangles" },
          { id: "circle", label: "Use circle formula" },
          { id: "one", label: "One triangle only" },
          { id: "ignore", label: "Ignore part of shape" },
        ],
        "split",
        "l5_sel_compound",
        { correct: "Split into rectangles.", incorrect: "Decompose.", hint: "Split." },
      ),
    ],
    mcScene(
      "l5-sel-final",
      "Mastery check",
      "Round pool — best model?",
      ["Circle", "Square", "Triangle", "Line"],
      "Circle",
      "l5_sel_mastery",
      { correct: "Circle for round objects.", incorrect: "Radius and π.", hint: "Circle." },
    ),
  ),
  lesson(
    5,
    "selecting-shapes",
    "Selecting Shapes",
    "intermediate",
    [
      matchScene(
        "l5-sel2-1",
        "Match situation",
        "Match each situation to the best shape model.",
        [
          { id: "a", label: "Picture frame" },
          { id: "b", label: "Pizza" },
          { id: "c", label: "Ramp side view" },
        ],
        [
          { id: "s1", label: "Rectangle" },
          { id: "s2", label: "Circle" },
          { id: "s3", label: "Triangle" },
        ],
        { s1: "a", s2: "b", s3: "c" },
        "l5_sel2_match",
        { correct: "Frame→rect, pizza→circle, ramp→triangle.", incorrect: "Match context.", hint: "Each fits." },
      ),
      mcScene(
        "l5-sel2-2",
        "Wrong model",
        "Using a single rectangle for a donut shape would…",
        ["Overestimate area", "Be exact", "Underestimate always", "Give zero"],
        "Overestimate area",
        "l5_sel2_wrong",
        { correct: "Includes the hole.", incorrect: "Hole not subtracted.", hint: "Overestimate." },
      ),
      mcScene(
        "l5-sel2-3",
        "Best choice",
        "Field with semicircular end — model as…",
        ["Rectangle + semicircle", "Square only", "One triangle", "Point"],
        "Rectangle + semicircle",
        "l5_sel2_best",
        { correct: "Combine shapes.", incorrect: "Decompose.", hint: "Rectangle + semicircle." },
      ),
    ],
    mcScene(
      "l5-sel2-final",
      "Mastery check",
      "Hexagonal tile — first step for area?",
      ["Split into triangles", "Use circle", "Ignore", "Perimeter only"],
      "Split into triangles",
      "l5_sel2_mastery",
      { correct: "Triangulate.", incorrect: "Split.", hint: "Triangles." },
    ),
  ),
  lesson(
    5,
    "area-expressions",
    "Area Expressions",
    "intermediate",
    [
      mcScene(
        "l5-area-1",
        "Write expression",
        "Rectangle: length (2x + 1), width 3. Area?",
        ["3(2x + 1)", "2x + 4", "6x", "2x + 1"],
        "3(2x + 1)",
        "l5_area_expr",
        { correct: "3(2x + 1) = 6x + 3.", incorrect: "Multiply.", hint: "3(2x + 1)" },
      ),
      mcScene(
        "l5-area-2",
        "Expand",
        "3(2x + 1) = ?",
        ["6x + 3", "6x + 1", "5x + 3", "2x + 3"],
        "6x + 3",
        "l5_area_expand",
        { correct: "Distribute.", incorrect: "3×2x + 3×1.", hint: "6x + 3" },
      ),
      mcScene(
        "l5-area-3",
        "Set equal",
        "6x + 3 = 27 → x = ?",
        ["4", "3", "27", "6"],
        "4",
        "l5_area_solve",
        { correct: "6x = 24 → x = 4.", incorrect: "Solve linear.", hint: "4" },
      ),
    ],
    mcScene(
      "l5-area-final",
      "Mastery check",
      "Square side (x + 2). Area?",
      ["(x + 2)²", "2x + 4", "x² + 2", "4x"],
      "(x + 2)²",
      "l5_area_mastery",
      { correct: "Side squared.", incorrect: "(x + 2)².", hint: "(x + 2)²" },
    ),
  ),
  lesson(
    5,
    "compound-shape-expressions",
    "Compound Shape Expressions",
    "intermediate",
    [
      mcScene(
        "l5-comp-1",
        "L-shape",
        "L-shape: x×4 rectangle plus x×2 rectangle. Total area?",
        ["6x", "4x", "2x", "x + 6"],
        "6x",
        "l5_comp_expr",
        { correct: "4x + 2x = 6x.", incorrect: "Add areas.", hint: "6x" },
      ),
      mcScene(
        "l5-comp-2",
        "Subtract",
        "x×x square minus x×1 strip. Area?",
        ["x² − x", "x² + x", "x", "x²"],
        "x² − x",
        "l5_comp_sub",
        { correct: "Subtract overlapping strip.", incorrect: "x² − x.", hint: "x² − x" },
      ),
      mcScene(
        "l5-comp-3",
        "Solve",
        "6x = 30 → x = ?",
        ["5", "6", "30", "24"],
        "5",
        "l5_comp_solve",
        { correct: "x = 5.", incorrect: "Divide.", hint: "5" },
      ),
    ],
    mcScene(
      "l5-comp-final",
      "Mastery check",
      "Two rectangles x×3 and x×5 — total area?",
      ["8x", "3x", "5x", "15x"],
      "8x",
      "l5_comp_mastery",
      { correct: "3x + 5x = 8x.", incorrect: "Add.", hint: "8x" },
    ),
  ),
  lesson(
    5,
    "equating-areas",
    "Equating Areas",
    "intermediate",
    [
      mcScene(
        "l5-eq-1",
        "Set equal",
        "Rectangle x×5 and square x×x have equal area when…",
        ["x² = 5x", "x = 5 always", "x = 0 only", "Never"],
        "x² = 5x",
        "l5_eq_setup",
        { correct: "5x = x² → x = 0 or 5.", incorrect: "Set areas equal.", hint: "x² = 5x" },
      ),
      mcScene(
        "l5-eq-2",
        "Solve",
        "x² = 5x → nonzero x = ?",
        ["5", "0", "25", "1"],
        "5",
        "l5_eq_solve",
        { correct: "x = 5 (and x = 0).", incorrect: "Divide by x (x ≠ 0).", hint: "5" },
      ),
      mcScene(
        "l5-eq-3",
        "Triangle vs rectangle",
        "Triangle ½×4×x equals rectangle 2×x when…",
        ["2x = 2x (always)", "Never", "x = 0 only", "x = 4"],
        "2x = 2x (always)",
        "l5_eq_tri",
        { correct: "Both equal 2x for all x.", incorrect: "½×4×x = 2x.", hint: "Always equal." },
      ),
    ],
    mcScene(
      "l5-eq-final",
      "Mastery check",
      "x×6 = x×x → x = ? (x > 0)",
      ["6", "0", "1", "36"],
      "6",
      "l5_eq_mastery",
      { correct: "x = 6.", incorrect: "6x = x².", hint: "6" },
    ),
  ),
];
