import {
  circlePlotLesson,
  circleRadiusLesson,
  graphScene,
  lesson,
  mcScene,
  pair,
} from "./_helpers";

/** Level 9 — Circles */
export const ALGEBRA_CGEO_LEVEL_9_SEEDS = [
  lesson(
    9,
    "circles",
    "Circles",
    "intermediate",
    [
      mcScene(
        "l9-circ-1",
        "Definition",
        "A circle is all points…",
        ["Equidistant from a center", "On a line", "In a square", "At the origin only"],
        "Equidistant from a center",
        "l9_circ_def",
        { correct: "Fixed radius from center.", incorrect: "Same distance r.", hint: "Equidistant." },
      ),
      mcScene(
        "l9-circ-2",
        "Parts",
        "Radius connects center to…",
        ["Any point on the circle", "Diameter only", "Circumference midpoint", "Origin always"],
        "Any point on the circle",
        "l9_circ_radius",
        { correct: "Center to edge.", incorrect: "Any point on circle.", hint: "Edge point." },
      ),
      mcScene(
        "l9-circ-3",
        "Standard form",
        "Circle equation (x − h)² + (y − k)² = r² gives…",
        ["Center (h, k) and radius r", "Only area", "Diameter", "Slope"],
        "Center (h, k) and radius r",
        "l9_circ_form",
        { correct: "Read h, k, and r.", incorrect: "Standard form.", hint: "Center and radius." },
      ),
    ],
    mcScene(
      "l9-circ-final",
      "Mastery check",
      "All points on a circle are…",
      ["Same distance from center", "On the x-axis", "At (0,0)", "Equal to radius squared"],
      "Same distance from center",
      "l9_circ_mastery",
      { correct: "Radius constant.", incorrect: "Equidistant.", hint: "Same distance." },
    ),
  ),
  circleRadiusLesson(9, "circle-radius", "Circle Radius", 0, 0, 4),
  circleRadiusLesson(9, "equation-of-a-circle", "The Equation of a Circle", 2, 3, 5),
  lesson(
    9,
    "missing-coordinate",
    "The Missing Coordinate",
    "intermediate",
    [
      mcScene(
        "l9-miss-1",
        "On circle",
        "On x² + y² = 25, if x = 3, y = ? (positive)",
        ["4", "5", "3", "16"],
        "4",
        "l9_miss_y",
        { correct: "9 + y² = 25 → y = ±4.", incorrect: "3-4-5.", hint: "4" },
      ),
      mcScene(
        "l9-miss-2",
        "Substitute",
        "(x − 1)² + (y − 2)² = 9, point (1, 5) — y coordinate of top?",
        ["5", "2", "3", "1"],
        "5",
        "l9_miss_sub",
        { correct: "(1, 5) is 3 above center (1, 2).", incorrect: "Center (1,2), r=3.", hint: "5" },
      ),
      graphScene(
        "l9-miss-3",
        "Plot point",
        "Plot (3, 4) on x² + y² = 25.",
        3,
        4,
        "l9_miss_plot",
        { correct: "(3, 4) on the circle.", incorrect: "3² + 4² = 25.", hint: "(3, 4)" },
      ),
    ],
    mcScene(
      "l9-miss-final",
      "Mastery check",
      "x² + y² = 16, x = 0 → y = ?",
      ["±4", "4 only always", "0", "16"],
      "±4",
      "l9_miss_mastery",
      { correct: "y² = 16.", incorrect: "Two solutions.", hint: "±4" },
    ),
  ),
  lesson(
    9,
    "naming-circles",
    "Naming Circles",
    "intermediate",
    [
      mcScene(
        "l9-name-1",
        "Read center",
        "(x + 2)² + (y − 1)² = 16 → center?",
        [pair(-2, 1), pair(2, -1), pair(0, 0), pair(4, 1)],
        pair(-2, 1),
        "l9_name_center",
        { correct: "x − (−2) and y − 1.", incorrect: "Signs flip.", hint: "(-2, 1)" },
      ),
      mcScene(
        "l9-name-2",
        "Read radius",
        "(x + 2)² + (y − 1)² = 16 → radius?",
        ["4", "16", "2", "8"],
        "4",
        "l9_name_r",
        { correct: "r² = 16.", incorrect: "√16 = 4.", hint: "4" },
      ),
      mcScene(
        "l9-name-3",
        "Describe",
        "Circle center (0, −3), radius 2:",
        ["x² + (y + 3)² = 4", "x² + y² = 4", "(x − 3)² + y² = 2", "x + y = 2"],
        "x² + (y + 3)² = 4",
        "l9_name_write",
        { correct: "h=0, k=−3, r=2.", incorrect: "Standard form.", hint: "x² + (y + 3)² = 4" },
      ),
    ],
    mcScene(
      "l9-name-final",
      "Mastery check",
      "(x − 4)² + (y + 1)² = 9 → center?",
      [pair(4, -1), pair(-4, 1), pair(4, 1), pair(0, 0)],
      pair(4, -1),
      "l9_name_mastery",
      { correct: "(4, −1).", incorrect: "h=4, k=−1.", hint: "(4, -1)" },
    ),
  ),
  circlePlotLesson(9, "plotting-circles", "Plotting Circles", 0, 0, 3, { x: 3, y: 0 }),
];
