import {
  circlePlotLesson,
  graphScene,
  lesson,
  mcScene,
  pair,
} from "./_helpers";

/** Level 10 — Circle equations from coordinates */
export const ALGEBRA_CGEO_LEVEL_10_SEEDS = [
  lesson(
    10,
    "leaving-the-origin",
    "Leaving the Origin",
    "intermediate",
    [
      mcScene(
        "l10-leave-1",
        "Shifted center",
        "Circle center (3, 2) differs from origin because…",
        ["h and k are not both 0", "Radius is 0", "No equation exists", "It is a line"],
        "h and k are not both 0",
        "l10_leave_intro",
        { correct: "Translated circle.", incorrect: "Center moved.", hint: "h, k nonzero." },
      ),
      mcScene(
        "l10-leave-2",
        "Equation form",
        "Center (3, 2), radius 4:",
        ["(x − 3)² + (y − 2)² = 16", "x² + y² = 16", "(x + 3)² + (y + 2)² = 4", "x + y = 4"],
        "(x − 3)² + (y − 2)² = 16",
        "l10_leave_eq",
        { correct: "Substitute h=3, k=2, r=4.", incorrect: "Standard form.", hint: "(x − 3)² + (y − 2)² = 16" },
      ),
      graphScene(
        "l10-leave-3",
        "Plot center",
        "Plot the center (3, 2).",
        3,
        2,
        "l10_leave_plot",
        { correct: "(3, 2).", incorrect: "Center point.", hint: "(3, 2)" },
      ),
    ],
    mcScene(
      "l10-leave-final",
      "Mastery check",
      "Origin-centered circle equation?",
      ["x² + y² = r²", "(x − 1)² + y² = r²", "x + y = r", "x = y"],
      "x² + y² = r²",
      "l10_leave_mastery",
      { correct: "h = 0, k = 0.", incorrect: "No shift.", hint: "x² + y² = r²" },
    ),
  ),
  lesson(
    10,
    "radius-from-coordinates",
    "Radius from Coordinates",
    "intermediate",
    [
      mcScene(
        "l10-rad-1",
        "Compute r",
        "Center (0, 0), point (3, 4) on circle → r = ?",
        ["5", "7", "3", "4"],
        "5",
        "l10_rad_compute",
        { correct: "Distance 5.", incorrect: "3-4-5.", hint: "5" },
      ),
      mcScene(
        "l10-rad-2",
        "Shifted center",
        "Center (1, 2), point (4, 6) on circle → r = ?",
        ["5", "7", "3", "4"],
        "5",
        "l10_rad_shift",
        { correct: "√(9+16) = 5.", incorrect: "Distance from (1,2) to (4,6).", hint: "5" },
      ),
      mcScene(
        "l10-rad-3",
        "Write equation",
        "Center (0,0), through (3, 4):",
        ["x² + y² = 25", "x² + y² = 5", "x + y = 5", "(x − 3)² + (y − 4)² = 0"],
        "x² + y² = 25",
        "l10_rad_eq",
        { correct: "r² = 25.", incorrect: "r = 5.", hint: "x² + y² = 25" },
      ),
    ],
    mcScene(
      "l10-rad-final",
      "Mastery check",
      "Center (2, −1), point (2, 3) → r = ?",
      ["4", "2", "3", "5"],
      "4",
      "l10_rad_mastery",
      { correct: "Vertical distance |3 − (−1)| = 4.", incorrect: "Same x.", hint: "4" },
    ),
  ),
  lesson(
    10,
    "general-circle-equations",
    "General Circle Equations",
    "intermediate",
    [
      mcScene(
        "l10-gen-1",
        "Expand",
        "(x − 2)² + (y + 1)² = 9 expanded has…",
        ["x² − 4x + y² + 2y + constant", "x + y = 3", "No x² term", "Only linear terms"],
        "x² − 4x + y² + 2y + constant",
        "l10_gen_expand",
        { correct: "Quadratic in x and y.", incorrect: "Expand squares.", hint: "Quadratic." },
      ),
      mcScene(
        "l10-gen-2",
        "Complete square",
        "x² + y² − 6x + 4y = 12 → center after completing square?",
        [pair(3, -2), pair(-3, 2), pair(6, -4), pair(0, 0)],
        pair(3, -2),
        "l10_gen_complete",
        { correct: "(3, −2) from −6/2 and 4/2.", incorrect: "Complete the square.", hint: "(3, -2)" },
      ),
      mcScene(
        "l10-gen-3",
        "Identify",
        "x² + y² = 49 describes circle with r = ?",
        ["7", "49", "14", "24.5"],
        "7",
        "l10_gen_identify",
        { correct: "r² = 49.", incorrect: "√49 = 7.", hint: "7" },
      ),
    ],
    mcScene(
      "l10-gen-final",
      "Mastery check",
      "(x − 5)² + (y + 2)² = 36 → r = ?",
      ["6", "36", "5", "2"],
      "6",
      "l10_gen_mastery",
      { correct: "r = 6.", incorrect: "r² = 36.", hint: "6" },
    ),
  ),
  circlePlotLesson(10, "plotting-from-the-equation", "Plotting from the Equation", 1, -2, 3, { x: 4, y: -2 }),
];
