import { circlePlotLesson, dist, graphScene, lesson, mcScene, pair, withinDistanceLesson } from "./_helpers";

/** Level 8 — Radial distance */
export const ALGEBRA_CGEO_LEVEL_8_SEEDS = [
  lesson(
    8,
    "radial-distance",
    "Radial Distance",
    "intermediate",
    [
      mcScene(
        "l8-rad-1",
        "Radius",
        "Radial distance from center means…",
        ["Distance to any point on the circle", "Diameter always", "Area", "Circumference only"],
        "Distance to any point on the circle",
        "l8_rad_intro",
        { correct: "Radius = center to edge.", incorrect: "Same in all directions.", hint: "Radius." },
      ),
      mcScene(
        "l8-rad-2",
        "From center",
        "Center (0,0), radius 4 — point on circle?",
        [pair(4, 0), pair(5, 0), pair(0, 0), pair(2, 2)],
        pair(4, 0),
        "l8_rad_on",
        { correct: "Distance 4 from center.", incorrect: "Check distance = 4.", hint: "(4, 0)" },
      ),
      mcScene(
        "l8-rad-3",
        "Not radial",
        "Which is NOT a radial distance?",
        ["Perimeter of square", "Radius of circle", "Distance center to point", "Spoke length"],
        "Perimeter of square",
        "l8_rad_not",
        { correct: "Perimeter goes around, not from center.", incorrect: "Radial = from center.", hint: "Perimeter." },
      ),
    ],
    mcScene(
      "l8-rad-final",
      "Mastery check",
      "Radial distance is measured from…",
      ["Center", "Edge", "Corner", "Origin only always"],
      "Center",
      "l8_rad_mastery",
      { correct: "Center outward.", incorrect: "From center.", hint: "Center." },
    ),
  ),
  lesson(
    8,
    "exact-distance",
    "Exact Distance",
    "intermediate",
    [
      mcScene(
        "l8-ex-1",
        "Exact vs estimate",
        "Distance (0,0) to (1, 1) exact form?",
        ["√2", "2", "1", "1.4 only"],
        "√2",
        "l8_ex_exact",
        { correct: "√(1²+1²) = √2.", incorrect: "Leave in radical form.", hint: "√2" },
      ),
      mcScene(
        "l8-ex-2",
        "Simplify radical",
        "√50 simplified?",
        ["5√2", "25", "10", "√25"],
        "5√2",
        "l8_ex_simp",
        { correct: "√(25×2) = 5√2.", incorrect: "Factor perfect square.", hint: "5√2" },
      ),
      graphScene(
        "l8-ex-3",
        "Plot",
        "Plot (1, 1).",
        1,
        1,
        "l8_ex_plot",
        { correct: "(1, 1).", incorrect: "One right, one up.", hint: "(1, 1)" },
      ),
    ],
    mcScene(
      "l8-ex-final",
      "Mastery check",
      "(0,0) to (3, 3) exact distance?",
      ["3√2", "6", "3", "9"],
      "3√2",
      "l8_ex_mastery",
      { correct: "√(9+9) = √18 = 3√2.", incorrect: "Legs both 3.", hint: "3√2" },
    ),
  ),
  withinDistanceLesson(8, "minimum-distance", "Minimum Distance", 3),
  lesson(
    8,
    "minimum-and-maximum-distance",
    "Minimum and Maximum Distance",
    "intermediate",
    [
      mcScene(
        "l8-minmax-1",
        "Min from origin",
        "Minimum distance from (0,0) to any point?",
        ["0", "1", "Undefined", "∞"],
        "0",
        "l8_minmax_min",
        { correct: "At the origin itself.", incorrect: "Origin point.", hint: "0" },
      ),
      mcScene(
        "l8-minmax-2",
        "Max in box",
        "Farthest point from (0,0) in 0 ≤ x ≤ 3, 0 ≤ y ≤ 4?",
        [pair(3, 4), pair(0, 4), pair(3, 0), pair(0, 0)],
        pair(3, 4),
        "l8_minmax_max",
        { correct: "Corner (3,4) — distance 5.", incorrect: "Farthest corner.", hint: "(3, 4)" },
      ),
      mcScene(
        "l8-minmax-3",
        "Range",
        "Distances from (0,0) to points in unit square [0,1]×[0,1] range from…",
        ["0 to √2", "0 to 1", "1 to 2", "0 to 2"],
        "0 to √2",
        "l8_minmax_range",
        { correct: "Min 0 at origin corner, max √2 at (1,1).", incorrect: "Corner (1,1) farthest.", hint: "0 to √2" },
      ),
    ],
    mcScene(
      "l8-minmax-final",
      "Mastery check",
      `Max distance from (0,0) to ${pair(3, 4)}?`,
      ["5", "7", "3", "4"],
      "5",
      "l8_minmax_mastery",
      { correct: "Fixed point — distance is 5.", incorrect: "Single point.", hint: "5" },
    ),
  ),
  circlePlotLesson(8, "points-on-a-circle", "Points on a Circle", 0, 0, 5, { x: 3, y: 4 }),
];
